### ISSUE TITLE
Electrs port 3000 not working

### ISSUE THREAD

**Issue by Ericalvin** [romanz/electrs#1013]
Hello everyone
I have a weird problem, my electrs were working well, but I found that its 3000 port was not working. The following is my configuration. Please tell me what the problem is. Thank you.

[Unit]
Description=electrs from blockstream
After=network.target
Requires=bitcoind.service
After=bitcoind.service
 
[Service]
ExecStart=/home/bitcoin/.cargo/bin/cargo run --release --bin electrs -- -vv --daemon-dir /home/bitcoin/bitcoind --tx-cache-size 100000 --index-batch-size 1000 --bulk-index-threads 14 --precache-scripts ./contrib/popular-scripts.txt **--http-addr 0.0.0.0:3000**
WorkingDirectory=/home/bitcoin/electrs
User=bitcoin
Group=bitcoin
Type=simple
Restart=on-failure
LimitNOFILE=65535
 
#Disallow the process and all of its children to gain
#new privileges through execve().
NoNewPrivileges=true
 
#Use a new /dev namespace only populated with API pseudo devices
#such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true
 
[Install]
WantedBy=multi-user.target

**Comment by romanz** [comment]
I think that you are running https://github.com/Blockstream/electrs or https://github.com/mempool/electrs

https://github.com/search?q=repo%3Aromanz%2Felectrs+http-addr&type=code

**Comment by Ericalvin** [comment]
@romanz 
Hi , yes I'm using https://github.com/Blockstream/electrs , the problem is it's work before, but I don't know why, the "--http-addr 0.0.0.0:3000" in the configuration did not work...

**Comment by romanz** [comment]
https://github.com/romanz/electrs/issues/967
