### ISSUE TITLE
Bug: UnknownSegwitFlag(0)

### ISSUE THREAD

**Issue by Logfro** [romanz/electrs#1024]
**Describe the bug**
Cant get an initial installation to complete first sync. 

Getting this error, before systemd restarts:
``thread 'main' panicked at 'core returned invalid block: UnknownSegwitFlag(0)', src/index.rs:294:49``

**Electrs version**
Newest version (v0.10.4)

**To Reproduce**
1. Starting bitcoind with this following params in bitcoin.conf:
txindex=1
server=1
dbcache=16384
maxmempool=20000

2. After initial bitcoind sync, started electrs with following config:
cookie_file = "/var/lib/bitcoind/.cookie"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"
db_dir = "/home/bitcoin/electrs"
daemon_dir = "/var/lib/bitcoind"
network = "bitcoin"
electrum_rpc_addr = "0.0.0.0:50001"
log_filters = "DEBUG"

4. After a long time, gets stuck at ```indexing 2000 blocks: [834441..836440]``` and error appears after:
``thread 'main' panicked at 'core returned invalid block: UnknownSegwitFlag(0)', src/index.rs:294:49``

**Expected behavior**
Well, that it works

**System running electrs**
 Compiled bitcoind and ``make install`` & built electrs on debian12
Tried the same with a docker approach from community images and got same error

**Electrum client**
Not yet used, as electrs always crashes

**Comment by romanz** [comment]
Is it possible that the block data got corrupted?

**Comment by Logfro** [comment]
Will do a completely new sync and test

**Comment by romanz** [comment]
@Logfro any update?

**Comment by Logfro** [comment]
Still syncing, hdds not the fastest. Electrs runs on NVMe ssds though.

**Comment by Logfro** [comment]
Can confirm, it was corrupted data. Works now.
