### ISSUE TITLE
Feature: support testnet4

### ISSUE THREAD

**Issue by antonilol** [romanz/electrs#1036]
Bitcoin Core PR: https://github.com/bitcoin/bitcoin/pull/29775
Maybe an update from the bitcoin crate is needed, but it could be that simply changing some constants (port, data dir, ...) can get it to work too

**Comment by antonilol** [comment]
That seems way too complicated, I think it would be best to wait for rust-bitcoin to add testnet4 support in some way, I see they are also improving the way networks are handled, see https://github.com/rust-bitcoin/rust-bitcoin/issues/2749

**Comment by nikicat** [comment]
It's indeed complicated, but from my point of view, it's less complicated than refactoring rust-bitcoin and gives the working solution right now. I do not propose it as a PR though, I just wanted to leave the link here if someone needs it.

**Comment by romanz** [comment]
Thanks for opening this issue!
I prefer to wait for proper Testnet4 support from https://github.com/rust-bitcoin/rust-bitcoin/issues/2749.

**Comment by twofaktor** [comment]
https://github.com/bitcoin/bitcoin/releases/tag/v28.0

**Comment by romanz** [comment]
https://github.com/rust-bitcoin/rust-bitcoin/issues/2749 is being backported to 0.32.x by https://github.com/rust-bitcoin/rust-bitcoin/pull/3453.

**Comment by antonilol** [comment]
Note that because the backport may not be a breaking change, it will be slightly different (adds a `Testnet4` enum variant to `Network` instead of a new `TestnetVersion` field in `Network::Testnet`), see https://github.com/rust-bitcoin/rust-bitcoin/pull/3453#discussion_r1797094776

**Comment by junderw** [comment]
The backport got ACKed, so expect 0.32.4 soon-ish.

It will be backwards compatible unlike the new network API on master.

**Comment by romanz** [comment]
Merged in #1104 - thanks @junderw!
