### ISSUE TITLE
Config:Indexing is not started

### ISSUE THREAD

**Issue by Fatsi321** [romanz/electrs#1050]
**Have you read the documentation?**
Yes. (Please, read usage.md first if you did not.)

**How did you configure electrs?**

<details>
<summary>electrs.toml</summary>
auth="XXXXXXXX:XXXXXXXX"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"
db_dir = "/bitcoin"
network = "bitcoin"
electrum_rpc_addr = "127.0.0.1:50001"

log_filters = "DEBUG"
```
type error message here
```
[2024-06-04T13:50:06.694Z DEBUG bitcoincore_rpc] JSON-RPC request: getblockchaininfo []
[2024-06-04T13:50:06.694Z DEBUG bitcoincore_rpc] JSON-RPC request: getnetworkinfo []
[2024-06-04T13:50:06.694Z INFO  electrs::daemon] waiting for 0 blocks to download (IBD)

These messages repeat and repeat, and no index were built, I am sure the bitcoin core RPC service is working.
</details>

Environment variables: `ELECTRS_X=Y;...`
Arguments: `--foo`

**Debug output of configuration**
```
Enter the debug output of configuration shown at start of electrs
```

**Expected behavior**
How did you expect `electrs` to be configured

**Actual behavior**
How does `electrs` behave?

**Comment by romanz** [comment]
Could you please add more details to the ticket?

**Comment by Fatsi321** [comment]
I am using electrs v0.10.5, bitcoin core v27.99 on Ubuntu 24.04 LTS, I read the guide and startup electrs but I find that it is not working, seems no index was built

**Comment by romanz** [comment]
Are there any logs being emitted?
How are you running electrs?

**Comment by Fatsi321** [comment]
> Are there any logs being emitted? How are you running electrs?

I started all over and the electrs is able to startup successfully. Thank you.
