### ISSUE TITLE
Config: electrs ignoring Timezone. Defaults to UTC

### ISSUE THREAD

**Issue by thnkman** [romanz/electrs#1077]
electrs runs with UTC time instead of local timezone. I have not found a setting to force timezone. 
Is there such a config setting?

**Comment by romanz** [comment]
I think it's only the logging timestamp format.
If needed, I think that you can pipe the log into [`ts`](https://linux.die.net/man/1/ts) to prepend it with the local time.

**Comment by Kixunil** [comment]
On one hand I'd agree that it'd be nice to print the time in native time zone, on the other it tends to require heavy dependencies that historically had multiple annoying issues. Hard to say if it's worth the trouble.

**Comment by Kixunil** [comment]
This legendary video explains it the best: https://www.youtube.com/watch?v=-5wpm-gesOY

**Comment by Kixunil** [comment]
Launching an entire command for every log record would be crazy large overhead. Also it'd make the project unix-only which is not great given it's now fully portable as far as I know.
