### ISSUE TITLE
Bug: `blockchain.block.header` params don't match the v1.4 specs

### ISSUE THREAD

**Issue by pythcoiner** [romanz/electrs#1080]
[ElectrumX](https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-block-header) specs define that `cp_height` param have been added in v1.4

The [actual implem](https://github.com/romanz/electrs/blob/875fb61951e3b337c9e4e468734e119ff58c0482/src/electrum.rs#L573) did not match, only one param is accepted (`height`).

Same issue w/ [`blockchain.block.headers`](https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain-block-headers), `cp_height` not accepted in the [actual implem](https://github.com/romanz/electrs/blob/875fb61951e3b337c9e4e468734e119ff58c0482/src/electrum.rs#L574)

I just noticed it while implementing a client, looks like noboby call this method if there is no previous report btw.

**Comment by romanz** [comment]
Indeed, Electrum currently is not using this feature: https://github.com/spesmilo/electrum/issues/4900

**Comment by pythcoiner** [comment]
@romanz i guess it's the same about `blockchain.scripthash.get_mempool`?

**Comment by romanz** [comment]
You're right.
