### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by AntoineXBTO** [romanz/electrs#109]
Hi,

It seems like after 24h the electrs server is not able to communicate with the bitcoin server anymore.
I saw a same issue was raised in the past but should have been solved in previous commit.

![image](https://user-images.githubusercontent.com/40615019/50335345-f87e8900-04d8-11e9-9838-57e391e34cc0.png)

The only way to make it work again is to restart bitcoind.

**Comment by romanz** [comment]
Thanks for the detailed response!
I'll try to reproduce using https://github.com/romanz/electrs/blob/master/contrib/xpub.py.

**Comment by AntoineXBTO** [comment]
Hello,

Any feedback on this? Do you need more info?

**Comment by romanz** [comment]
Unfortunately it didn't reproduce on my machine...
Can you run `lsof` when the issue happens, and attach the list of open files? Maybe we can understand the issue better then.

**Comment by romanz** [comment]
No problem.
Could you please post the command-line used to run `electrs`?
Which OS are you running?

It seems that the RPC sockets are not getting closed (if port 3000 is indeed the RPC port).
How do you call the API? could you please post the client code?

**Comment by AntoineXBTO** [comment]
/usr/bin/cargo run --manifest-path=/home/electrs1/electrs/Cargo.toml  -- -vvv --timestamp --db-dir /home/electrs1/db --jsonrpc-import

I'm running  Ubuntu 16.04.5 LTS

I'm calling the API from a C# code
![image_2019-01-14_10-30-48](https://user-images.githubusercontent.com/40615019/51206100-54b8ab00-18d5-11e9-85cf-386bcb7b826d.png)

**Comment by AntoineXBTO** [comment]
I'm actually using the blockstream version.
I believe the backend is the same and IOs on the disk should be equivalent.
I tried increasing the open file limit, I saw it could be an issue not only with electrs, I will come back to you today on this.

**Comment by AntoineXBTO** [comment]
Closing for now. I will come back if I find what the issue is.
Thanks for your time!

**Comment by prinze77** [comment]
Found the issue?

**Comment by prinze77** [comment]
ulimit -n 131072 fixed the issue is somebody have same issue

**Comment by rolznz** [comment]
We had this issue too, and ulimit -n already returned 500000.

We fixed this by adding `LimitNOFILE=131072` to electrs.service to make sure the ulimit is applied to running service daemons (as per https://github.com/Blockstream/esplora/issues/133#issuecomment-564963590)
