### ISSUE TITLE
Bug:cannot connect any wallet or sparrow to electrum server

### ISSUE THREAD

**Issue by Coldslug74** [romanz/electrs#1099]
in sparrow wallet in preferences - server

when trying to connect to the url and socket  i got this message

        Could not connect:

SOCKS: Host unreachable. Check if the proxy server is running.

i upgraded electrum server and sparrow . it was working well last week.

dont work either on blue wallet

thanks for assisting

*

**Comment by romanz** [comment]
Does it work without a SOCKS proxy server?
