### ISSUE TITLE
Hangs after update upon client making request

### ISSUE THREAD

**Issue by Overtorment** [romanz/electrs#110]
It was working fine for some time, then I decided to update, pulled from master and recompiled.
It seems to be starting, except all requests just hang.

```
igor@vmi224865:~/electrs$ ./run-electrum.sh
    Finished release [optimized] target(s) in 3.95s
     Running `target/release/electrs -vvv --timestamp --db-dir ./db '--cookie=111:222' '--electrum-rpc-addr=0.0.0.0:50001' --daemon-dir /home/igor/bitcoin-0.17.0/datadir/`
Config { log: StdErrLog { verbosity: Debug, quiet: false, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin, db_path: "./db/mainnet", daemon_dir: "/home/igor/bitcoin-0.17.0/datadir/", daemon_rpc_addr: V4(127.0.0.1:8332), cookie: Some("111:222"), electrum_rpc_addr: V4(0.0.0.0:50001), monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 4, tx_cache_size: 10000, server_banner: "Welcome to electrs (Electrum Rust Server)!" }
2019-01-05T13:37:21.866+01:00 - DEBUG - Server listening on 127.0.0.1:4224
2019-01-05T13:37:21.867+01:00 - DEBUG - Running accept thread
2019-01-05T13:37:21.938+01:00 - INFO - NetworkInfo { version: 170001, subversion: "/Satoshi:0.17.0.1/" }
2019-01-05T13:37:21.939+01:00 - INFO - BlockchainInfo { chain: "main", blocks: 557152, headers: 557152, bestblockhash: "0000000000000000002e5636f191a9a7c0c977f3fc2425275a96b84a75933ff4", pruned: false, initialblockdownload: false }
2019-01-05T13:37:21.940+01:00 - DEBUG - opening DB at "./db/mainnet"
2019-01-05T13:37:31.819+01:00 - DEBUG - applying 557153 new headers from height 0
2019-01-05T13:37:32.283+01:00 - INFO - enabling auto-compactions
2019-01-05T13:37:32.283+01:00 - DEBUG - opening DB at "./db/mainnet"
2019-01-05T13:37:32.297+01:00 - DEBUG - downloading new block headers (557153 already indexed) from 0000000000000000002e5636f191a9a7c0c977f3fc2425275a96b84a75933ff4
2019-01-05T13:37:33.686+01:00 - INFO - RPC server running on 0.0.0.0:50001




2019-01-05T13:38:17.315+01:00 - INFO - [37.152.240.153:54710] connected peer
```

Here you can see that it started and indexed ok. Then my client connected, but then - nothing. Client hangs waiting for a response: 

```
overtorment@laptop3 ~/Documents/nodejs-electrum-http (master) $ echo '{"id": 1, "method": "blockchain.scripthash.get_balance", "params": ["43f626c7e6c22741e3160900776ba65f2526956c54779d193267fde55624adaf"]}' | nc 1.2.3.4  50001 -i 1
```

**Comment by romanz** [comment]
Thanks for opening this issue!
This scripthash seems to be very popular (has ~381K funding transactions), and since `electrs` is not optimized for this use-case, the query takes a lot of time (on HDDs, the transaction lookups take most of the time).

**Comment by romanz** [comment]
Are there other addresses/scripthashes that cause similar symptoms?

**Comment by Overtorment** [comment]
I thought that its my instance that went bad.
No, I dont have any other. In fact, that one is just a random scripthash I
copypasted somewhere just to check my electrum instances via telnet/nc.
Can it be fixed?

**Comment by romanz** [comment]
It can be solved, but it will make the indexing logic more complicated - so, currently, I'd suggest to check using a different script hash.

**Comment by romanz** [comment]
No, each address has its own script hash.

**Comment by Overtorment** [comment]
Exactly. So electrs cant be used for some occasional addresses with lots of
txs..?

**Comment by romanz** [comment]
It will take too much time (linear in the number of transactions), so you are right...

**Comment by romanz** [comment]
It should work well for addresses with <100 transactions.

**Comment by Overtorment** [comment]
I saw an announcement that blockstream info now supports large addresses.
How did they do that? Is their electrs fork way ahead of this repo..?

**Comment by romanz** [comment]
https://blockstream.info is using a different indexing engine and DB schema as described [here](https://github.com/Blockstream/electrs/blob/new-index/doc/schema.md).
It requires more index storage and uses SSDs for faster indexing and paging.
This project is more optimized for HDDs and smaller index storage overhead, but in the future it may be possible to support both modes of operation using the same codebase (using command line flags).
