### ISSUE TITLE
Feature: make blockchain.scripthash.get_balance call possible with pruned btccore if ran together from the beginning

### ISSUE THREAD

**Issue by errge** [romanz/electrs#1100]
**Is your feature request related to a problem? Please describe.**

I'm trying to figure out the minimal feasible setup for a bitcoin "node" that can answer the question: "What is the current balance of address X?" for any X in the future.

I don't want any solution where the set of Xs have to be pre-configured in any way (e.g. Electrum Personal Server, btccore wallets).

I'm optimizing for CPU+Bandwidth+Disk.

**Describe the solution you'd like**

My idea would be:
  - start from scratch btccore data dir, start full sync, but with `-txindex=0 -blocksonly=1 -blockfilterindex=1 -prune=1000`
  - start electrs AT THE SAME TIME, already at the beginning with `--skip-block-download-wait`
  - wait until everything is synced
  - profit!

The only RPC I want from electrs is `blockchain.scripthash.get_balance`.

Currently this fails, because electrs has an initial check to check for working with pruned node.

Is there a conceptual problem with my request? Is this possible in theory at least? What would be the easiest way to get it working?

**Describe alternatives you've considered**

I tried to consider other solutions, but I didn't find any, that didn't need the set of watched addresses predetermined.

**Comment by romanz** [comment]
electrs index is not storing the balance per address, only the relevant block heights (see [doc/schema.md](https://github.com/romanz/electrs/blob/master/doc/schema.md) for details), so it cannot support the query above when bitcoind is pruned.

If you need the get an address balance, I would suggest using [scantxoutset](https://bitcoincore.org/en/doc/28.0.0/rpc/blockchain/scantxoutset/) CLI command, e.g.:
```
$ time bitcoin-cli scantxoutset start '["addr(bc1qaukl0kf0aec88999tj5xdrtfz56awmqyj9zxeh)"]'
{
  "success": true,
  "txouts": 186046365,
  "height": 866731,
  "bestblock": "00000000000000000001769e5be197242bf0c99b75e2d8b8e534ea7cce2d2d03",
  "unspents": [
    {
      "txid": "a9af3858aff158c128b08526897cf395f442f1f28d5bd9eafe50a6e817a87f54",
      "vout": 3,
      "scriptPubKey": "0014ef2df7d92fee707394a55ca8668d691535d76c04",
      "desc": "addr(bc1qaukl0kf0aec88999tj5xdrtfz56awmqyj9zxeh)#jh4azsdv",
      "amount": 0.00125613,
      "coinbase": false,
      "height": 865867,
      "blockhash": "00000000000000000000a84db1030611ac53cb1ec92604fda1fe563f97358c41",
      "confirmations": 865
    },
    {
      "txid": "1e6329c2c3362238749137ec5fc35e89f903990c242ebcb2d8f3d3686d17d255",
      "vout": 3,
      "scriptPubKey": "0014ef2df7d92fee707394a55ca8668d691535d76c04",
      "desc": "addr(bc1qaukl0kf0aec88999tj5xdrtfz56awmqyj9zxeh)#jh4azsdv",
      "amount": 0.00173205,
      "coinbase": false,
      "height": 863937,
      "blockhash": "00000000000000000001ab35fcb078b958860979f147f9d3f385f9748399a0ee",
      "confirmations": 2795
    },
    {
      "txid": "a0e85a03ad13ddf661270812c010ea45201c31a9de4bf8ef3b337e42baea436c",
      "vout": 3,
      "scriptPubKey": "0014ef2df7d92fee707394a55ca8668d691535d76c04",
      "desc": "addr(bc1qaukl0kf0aec88999tj5xdrtfz56awmqyj9zxeh)#jh4azsdv",
      "amount": 0.00064715,
      "coinbase": false,
      "height": 865560,
      "blockhash": "000000000000000000010c971fc5423bd258afba8a1d97590736da28c240a856",
      "confirmations": 1172
    },
    {
      "txid": "44f4f259bfc6268a4c60a9e64aeb8bc6364b815c80e7dd65d84924cf8996d27d",
      "vout": 3,
      "scriptPubKey": "0014ef2df7d92fee707394a55ca8668d691535d76c04",
      "desc": "addr(bc1qaukl0kf0aec88999tj5xdrtfz56awmqyj9zxeh)#jh4azsdv",
      "amount": 0.05582192,
      "coinbase": false,
      "height": 866483,
      "blockhash": "00000000000000000000d13bdb526ee5db049ef3ddd2f87388752bdd42249340",
      "confirmations": 249
    },
    {
      "txid": "49c79ced651ef9c76c7277c9653fe9e9f1efeba7f46a46026f95b4ea32c167af",
      "vout": 3,
      "scriptPubKey": "0014ef2df7d92fee707394a55ca8668d691535d76c04",
      "desc": "addr(bc1qaukl0kf0aec88999tj5xdrtfz56awmqyj9zxeh)#jh4azsdv",
      "amount": 1.13389434,
      "coinbase": false,
      "height": 866730,
      "blockhash": "000000000000000000010526cc3792cadc027702db956eb80b8fbde623adf749",
      "confirmations": 2
    }
  ],
  "total_amount": 1.19335159
}

real	1m3.245s
user	0m0.002s
sys	0m0.004s
```

**Comment by errge** [comment]
Thanks for the advice, sorry for the noise!
