### ISSUE TITLE
Bug: failed to get block hash 0000000000000000000000b71ed0d9bec536d4fbbfa4da8dece0edb25324d11db0

### ISSUE THREAD

**Issue by redtigervn** [romanz/electrs#1101]
Hi there,

I've installed bitcoin node and electrs server on VPS. I write nodejs script to listen new transaction from specific addrs and I get this error when I use Electrum protocol method **blockchain.scripthash.subscribe** to subscribe scripthash. Then I use electrumClient.subscribe.on event to listen new tx. But I always get this error

`Failed to get block: 0000000000000000000000b71ed0d9bec536d4fbbfa4da8dece0edb25324d11db0`

This block hash has 66 characters instead of 64 characters. Anyone get this error?

I also delete electrs_db folder and sync data again but it doesn't help.

![image](https://github.com/user-attachments/assets/a86b4c7a-96cb-4058-94b9-3c877477b182)

**Comment by romanz** [comment]
Which client library is being used? Would it be possible to share the requests' log?

**Comment by romanz** [comment]
IIUC, by removing the first zero byte, we get the following valid block hash: 
https://blockstream.info/block/00000000000000000000b71ed0d9bec536d4fbbfa4da8dece0edb25324d11db0

**Comment by redtigervn** [comment]
Hi Romanz,
Sorry for late reply, I use **electrum-client** lib (version ^0.0.6)
I also use **bitcoinjs-lib** lib to convert address to electrum hash

`const ecc = require('tiny-secp256k1');
const bitcoin = require('bitcoinjs-lib');
bitcoin.initEccLib(ecc);

const script = bitcoin.address.toOutputScript(address);
const hash = crypto.createHash('sha256').update(script).digest();
const reversedHash = Buffer.from(hash.reverse());
cosnt scripthash = reversedHash.toString('hex');

electrumClient.blockchainScripthash_subscribe(scripthash).then((scripthash) => {              
    console.log(`Subscribed to updates for scripthash: ${scriptHash}`);
});

electrumClient.subscribe.on('blockchain.scripthash.subscribe', async (data) => {
    const [scripthash, status] = data;
    //receive a notification when the status of the script hash changes.
    //do something here....
});
`

**Comment by redtigervn** [comment]
> IIUC, by removing the first zero byte, we get the following valid block hash: https://blockstream.info/block/00000000000000000000b71ed0d9bec536d4fbbfa4da8dece0edb25324d11db0

but I don't know where this block hash come from. I get this error when I'm listening new status of the script hash changes.
This protocol method: **blockchain.scripthash.subscribe**

**Comment by romanz** [comment]
Unfortunately, I am not familiar with this client library.

You can run electrs with higher logging verbosity, to see all the JSON-RPC requests and responses:
```
export RUST_LOG=electrs::server=DEBUG
```

I would suggest also trying to see if your code works on other Electrum servers, and maybe [opening an issue here](https://github.com/you21979/node-electrum-client).

**Comment by redtigervn** [comment]
> Unfortunately, I am not familiar with this client library.
> 
> You can run electrs with higher logging verbosity, to see all the JSON-RPC requests and responses:
> 
> ```
> export RUST_LOG=electrs::server=DEBUG
> ```
> 
> I would suggest also trying to see if your code works on other Electrum servers, and maybe [opening an issue here](https://github.com/you21979/node-electrum-client).

Thanks for your suggestion
