### ISSUE TITLE
Jsonrpc request parsing fails if "id" field isn't an integer

### ISSUE THREAD

**Issue by pm47** [romanz/electrs#111]
I'm trying to connect to an electrs server from eclair, which has so far only been tested against electrumx. The very first message after connecting is rejected, this must be an obvious thing but I have poor rust reading skills and can't figure it out.

```
INFO - [127.0.0.1:57938] connected peer
TRACE - RPC Request("{\"method\":\"server.version\",\"params\":[\"2.1.7\",\"1.2\"],\"id\":\"0\",\"jsonrpc\":\"1.0\"}\r\n")
ERROR - [127.0.0.1:57938] connection handling failed: Error: invalid command: {"id":"0","jsonrpc":"1.0","method":"server.version","params":["2.1.7","1.2"]}
```

**Comment by pm47** [comment]
Ok, it seems that electrs expects the id field of the json rpc request to be a number. This isn't compliant with the json-rpc spec, which states that it can be "of any type" (version 1.0) or either of string/number/null (version 2.0)

**Comment by romanz** [comment]
Thanks for reporting this issue!
Please try the latest master, https://github.com/romanz/electrs/commit/b77cd541d56d9db8c03724a9c30933dd74c81e38 should fix the issue :)

**Comment by pm47** [comment]
Excellent, thanks!
