### ISSUE TITLE
Does electrs need access to the block files after the initial sync?

### ISSUE THREAD

**Issue by d3spwn** [romanz/electrs#112]
I run bitcoind and electrs as different users. Bitcoind creates the files in it's datadir with umask 077, but electrs needs read permissions on the block files during initial sync. I changed the permissions on the block files to g+r so electrs could read index them. New block files created after the initial sync won't have this permission. Does electrs need access to block files after the initial sync?

**Comment by romanz** [comment]
Good question!
You're right - the blk*.dat files are needed only for the initial "bulk" sync.
If you don't want to change their permissions, you can use `--jsonrpc-import` flag, and then the initial sync will use bitcoind's JSONRPC (instead of reading the blk*.dat files).
