### ISSUE TITLE
note: electrs may takes 10+mins to answer a blockchain.scripthash.get_balance request depending on the number of transactions the address has

### ISSUE THREAD

**Issue by filipponeri** [romanz/electrs#1121]
**Describe the bug**

electrs takes 10min to answer a blockchain.scripthash.get_balance request

```
echo '{"jsonrpc": "2.0", "method": "blockchain.scripthash.get_balance", "params": ["8b01df4e368ea28f8dc0423bcf7a4923e3a12d307c875e47a0cfbf90b5c39161"], "id": 0}' | netcat 127.0.0.1 50001
```
**Electrs version**
latest release version

**To Reproduce**
1. electrs fully sync
2. bitcoind running
3. on cmd prompt run 
```
echo '{"jsonrpc": "2.0", "method": "blockchain.scripthash.get_balance", "params": ["8b01df4e368ea28f8dc0423bcf7a4923e3a12d307c875e47a0cfbf90b5c39161"], "id": 0}' | netcat 127.0.0.1 50001
```

4. need to wait 10 min for getting the answer

**Expected behavior**
retrieving the balance in a fraction of a second

Thank you for any input.

**Comment by romanz** [comment]
IIUC, this specific scripthash matches `1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa`, which has >47k transactions - right?

**Comment by antonilol** [comment]
Could it be worth to make a new index that stores balances of addresses (behind a config flag)? Currently electrs looks up all UTXOs and adds up the output values.

**Comment by filipponeri** [comment]
@romanz @antonilol Hi, thank you for your quick replies. You are right. The behavior of electrs that I have reported is simply the effect of having to go through all transactions in the db to calculate the balance for an address. Therefore more time is required to get the balance for an address the more transactions it has.
I have run some experiments on my hardware (dell xps 9370 but electrs db on an external hdd (not ssd). Both bitcoind and electrs runs on the notebook but both have their db on the external hdd. Here is the result from one run.

1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa has 50.27076542 confirmed bitcoins
1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa has 0.0 unconfirmed bitcoins
num transactions as per mempool.space 40812
user wait time in seconds (not process time) 731.1561415195465

3KZDwmJHB6QJ13QPXHaW7SS3yTESFPZoxb has 19.40483118 confirmed bitcoins
3KZDwmJHB6QJ13QPXHaW7SS3yTESFPZoxb has 0.0 unconfirmed bitcoins
num transactions as per mempool.space 1071
user wait time in seconds (not process time) 76.84535527229309

16FuTPaeRSPVxxCnwQmdyx2PQWxX6HWzhQ has 0.0 confirmed bitcoins
16FuTPaeRSPVxxCnwQmdyx2PQWxX6HWzhQ has 0.0 unconfirmed bitcoins
num transactions as per mempool.space 62
user wait time in seconds (not process time 0.5019223690032959

32B5bw2ohLfvgBva2B4X3aao9iDa7Eakp5 has 0.69776391 confirmed bitcoins
32B5bw2ohLfvgBva2B4X3aao9iDa7Eakp5 has 0.0 unconfirmed bitcoins
num transactions as per mempool.space 32288
user wait time in seconds (not process time) 1403.6829478740692
 
Thank you for your attention. I have remove keywork BUG from the title as it is not a bug but how electrs operates.

**Comment by romanz** [comment]
For "popular" addresses, I would suggest using `bitcoin-cli scantxoutset` command:
```bash
$ time ./bitcoin-cli scantxoutset start '["addr(1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa)"]' > utxo.json

real	1m5.988s
user	0m0.345s
sys	0m0.956s
```

You can get all the unspent outputs funding this address, as well as the total balance in the end:
```json
{
  "success": true,
  "txouts": 187316502,
  "height": 873982,
  "bestblock": "0000000000000000000030f391dc79a9a6fa764811e9905a5c53067a45852df0",
  "unspents": [
    {
      "txid": "3f528050c823f11b2b952b221e42e6505bc89dae0ee956388627bf098c9a0100",
      "vout": 0,
      "scriptPubKey": "76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac",
      "desc": "addr(1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa)#632p52jr",
      "amount": 0.00000546,
      "coinbase": false,
      "height": 845952,
      "blockhash": "000000000000000000026f30cee8d5e2a705e8d21abc03d7bdb97059c61c9804",
      "confirmations": 28031
    },
    ...
    {
      "txid": "4c278330dcd08456fd520522b98f5d140795c7d16cbee02592d751d737fafcff",
      "vout": 0,
      "scriptPubKey": "76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac",
      "desc": "addr(1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa)#632p52jr",
      "amount": 0.00001000,
      "coinbase": false,
      "height": 847453,
      "blockhash": "00000000000000000000ee1d47efde39fc4ef6c95cfc00070cc5b049a8d39557",
      "confirmations": 26530
    },
    {
      "txid": "987ef66793bba7f07baee543133ccbf45e2c41b0be9f1f23ef3e73345751feff",
      "vout": 0,
      "scriptPubKey": "76a91462e907b15cbf27d5425399ebf6f0fb50ebb88f1888ac",
      "desc": "addr(1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa)#632p52jr",
      "amount": 0.00000600,
      "coinbase": false,
      "height": 829936,
      "blockhash": "000000000000000000010fe144d857b8d9dedc96ea300c39d87a83b8f3532d15",
      "confirmations": 44047
    }
  ],
  "total_amount": 50.27447162
}    
```

**Comment by filipponeri** [comment]
thank you @romanz for your helpful comments and suggestions about bitcoin-cli scantxoutset. Sorry for the late reply.

**Comment by romanz** [comment]
BTW, I think you can use the approach described in https://github.com/bitcoin/bitcoin/pull/27432#issuecomment-2660949219 to quickly analyze UTXO data using DuckDB.
