### ISSUE TITLE
Bug: Metrics endpoint doesn't return `Content-Type` header

### ISSUE THREAD

**Issue by 0xf0xx0** [romanz/electrs#1127]
**Describe the bug**
The metrics endpoint doesn't return the `Content-Type` header, and prometheus refuses to scrape it. From the [docs](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format) it looks like the header should be set to `text/plain` at minimum.

<details>
<summary>prometheus error log & curl output </summary>

> time=2024-12-18T18:40:39.843Z level=ERROR source=scrape.go:1585 msg="Failed to determine correct type of scrape target." component="scrape manager" scrape_pool=electrs target=hxxp://localhost:4224/metrics content_type="" fallback_media_type="" err="non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target"

```
curl hxxp://localhost:4224/metrics -I
HTTP/1.1 200 OK
Server: tiny-http (Rust)
Date: Wed, 18 Dec 2024 18:52:53 GMT
Transfer-Encoding: chunked
```

</details>

The workaround is to set `fallback_scrape_protocol: "PrometheusText1.0.0"` in the electrs [scrape config block.
](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config)

**Electrs version**
0.10.7

**To Reproduce**
1. Configure and start electrs
2. `curl $electrs_addr -I`
3. behold, thine `Content-Type` is barren

**Expected behavior**
electrs should return the correct `Content-Type` header.

**Configuration**
irrelevant

Environment variables: none
Arguments: none

**System running electrs**
 - Deployment method: manual build
 - OS name and version: EndeavourOS (rolling)

**Electrum client**
none

**Additional context**
https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format

**Comment by romanz** [comment]
Thanks for reporting this issue!
Could you please try https://github.com/romanz/electrs/commit/9eebce9e910a2cf0a8df9df27168ccb0aad4428b?

**Comment by 0xf0xx0** [comment]
works for me :3
