### ISSUE TITLE
Electrs at scale for multi consumers / producers

### ISSUE THREAD

**Issue by gbenattar** [romanz/electrs#114]
Electrs is using tcp sockets for notifying clients (E.g. incoming transaction for an address). We are trying to have both redundancy and reliability for listening to events and we would like to introduce a mechanism which pushes notification to queues (elastic and managed - E.g. AWS SQS) - Then we could have Electrs nodes pushing to a queue and clients consuming from this queue.

In cases where all clients are down, messages will be retained. In cases where Electrum is down, Electrum could backfill the queue with missed operation, for this an "index" need to be kept on what to notify on.

Today our solution with sockets is not bullet proofs even if we subscribe multiple client / electrs to same addresses. We would like to evaluate the effort of this project and if this is something that would be interesting for other users / clients.

What do you think?

**Comment by romanz** [comment]
Many thanks for this suggestion!
I think that it would be possible to replace the current periodic updates (which are sent over JSONRPC) by an abstract "publish" call here:
https://github.com/romanz/electrs/blob/f51c7dc6b4020f8bdcbed104dcac6ff0483a8c2a/src/rpc.rs#L404-L409

Of course, it would default to using the JSONRPC interface (by calling `self.send_values()`), but it can be changed to any other notification mechanism (e.g. AWS SQS).

Please let me know if I understood your issue correctly :)

**Comment by gbenattar** [comment]
Yes - the missing element is the recovery part. In case Electrs is down, when going back up it would need to "re-listen" on subscribed addresses, and backfill the queue with missed events. For instance we could keep an "index" on (ttl cache / low latency db).

Do you see what I mean? Do you have any suggestion on how to do this properly?

**Comment by romanz** [comment]
Just to make sure I understand:
The issue here is the long time it takes to re-subscribe to an address when electrs is restarted?
