### ISSUE TITLE
Release: would be possible to statically compile to a single binary file?

### ISSUE THREAD

**Issue by tiero** [romanz/electrs#115]
https://github.com/rust-lang/rust/pull/24777

I'm not an expert, but do you think would be possible to have as release artifacts also a binary?

**Comment by romanz** [comment]
Thanks for opening this issue!
Currently, there is a Dockerfile which can be used for creating Docker images as part of the release process. See https://github.com/romanz/electrs/blob/master/doc/usage.md#docker for usage example.

**Comment by tiero** [comment]
> Currently, there is a Dockerfile which can be used for creating Docker images as part of the release process. See https://github.com/romanz/electrs/blob/master/doc/usage.md#docker for usage example.

Yes I'm using docker in my CI pipeline, the fact is installing rust and building electrs each time is a bit of no-op. Would love to have the binary already built at least for linux.

I would try myself to do it and see if possible

**Comment by tiero** [comment]
Here, just to demonstrate for Linux.
https://github.com/vulpemventures/electrs/releases/tag/v0.4.1-bin

Of course, signing and other machinery would be needed
