### ISSUE TITLE
Response to server.version should be correct name, version and supported protocol

### ISSUE THREAD

**Issue by freerko** [romanz/electrs#121]
Hi,

running the current electrs 0.5.0 I get this response on a `server.version` request:
` {"id":0,"jsonrpc":"2.0","result":["RustElectrum 0.1.0","1.4"]}`

In the README.md you state 
> Supports Electrum protocol v1.2

The server.version response should include the correct software name (is it RustElectrum or electrs?), the correct version number (0.5.0 instead of 0.1.0) and the correct Electrum protocol version supported (is it 1.2 or 1.4?)

**Comment by romanz** [comment]
Thanks!
Should be resolved by https://github.com/romanz/electrs/commit/878f81cfeb33916c1d09fdf72e2027d62e652f73.
