### ISSUE TITLE
[Enhancement] Rust Equivalent of `Make Install`

### ISSUE THREAD

**Issue by JeffVandrewJr** [romanz/electrs#125]
Does Rust have an equivalent to `make install` that places the relevant binaries in `/usr/local/bin` so that the user can then delete the source directory? If so, using such functionality would make things a little cleaner. Not a huge issue obviously.

**Comment by romanz** [comment]
I think that you could use the `cargo install` command:
```
$ cargo install --path .
$ which electrs
/home/user/.cargo/bin/electrs
```
