### ISSUE TITLE
`failed to parse manifest` on `cargo build --release`

### ISSUE THREAD

**Issue by sangaman** [romanz/electrs#129]
Running `cargo build --release` using the latest from master fails with the error:

```
error: failed to parse manifest at `/home/bitcoin/electrs/Cargo.toml`

Caused by:
  editions are unstable

Caused by:
  feature `edition` is required

this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
```

This is using the following version of rust/cargo, which worked fine several months ago and which are still supposed to be supported according to the docs which indicate 1.28+.

cargo 1.29.0 (524a578d7 2018-08-05)
rustc 1.29.1 (b801ae664 2018-09-20)

https://github.com/rust-lang/cargo/issues/6113 and https://github.com/kbknapp/cargo-outdated/issues/141 suggest that updating to 1.32+ solves this issue. I updated to 1.33 which is the current latest version, and the issue went away for me.

**Comment by romanz** [comment]
Thanks for reporting and fixing the issue!
