### ISSUE TITLE
ERROR - server failed: Error: incorrect magic 2a9315cb at 14742100

### ISSUE THREAD

**Issue by duckartes** [romanz/electrs#13]
2018-07-09T14:46:37.258+00:00 - DEBUG - applying 531189 new headers from height 0
2018-07-09T14:46:38.829+00:00 - INFO - indexing 1310 blk*.dat files
2018-07-09T14:46:38.829+00:00 - DEBUG - 370713 blocks are already indexed
2018-07-09T15:27:34.207+00:00 - ERROR - server failed: Error: incorrect magic 2a9315cb at 14742100

**Comment by romanz** [comment]
This is indeed unfortunate :(
Could you upload the problematic blk*.dat file, so I could analyze it?

**Comment by romanz** [comment]
I am also plan to refactor the bulk indexing code soon, so it'll be easier to debug such issues.

**Comment by duckartes** [comment]
Where would that file be located? 

Not sure where it's failing, don't understand the error code.

**Comment by romanz** [comment]
> I am also plan to refactor the bulk indexing code soon, so it'll be easier to debug such issues.

The refactoring was merged into `master` (#15), please try again with the latest code (https://github.com/romanz/electrs/commit/2852020c58776032711f8e021ea8d10d91efc721).

**Comment by romanz** [comment]
Update: please try again with the code from today (https://github.com/romanz/electrs/commit/d422dc09cb249cc7398c876b587e53645b2fa755).

**Comment by romanz** [comment]
@duckartes Please try again with the latest commit: https://github.com/romanz/electrs/commit/ebdc252a24c8e1128787598a0d732767688796a8 (it should skip invalid and already indexed blocks during initial indexing).
