### ISSUE TITLE
Defaulting to ipv6 addresses

### ISSUE THREAD

**Issue by sangaman** [romanz/electrs#131]
With the latest master and rust 1.33, electrs defaults to ipv6 for all addresses which contrasts with the descriptions in the defaults in the config, where values are specified in ipv4 like `default: '127.0.0.1:50001' for mainnet`. I'm pretty sure I did not observe this behavior with rust 1.28 and master from several months ago. The workaround for me currently is to explicitly specify ipv4 values for `electrum-rpc-addr` and `daemon-rpc-addr` via the command line.

**Comment by romanz** [comment]
Thanks for reporting this issue!
It should be fixed by https://github.com/romanz/electrs/commit/963037607b9c19d6bb6ef1869ff362ac6e0542e6.

**Comment by sangaman** [comment]
Can confirm that the issue is fixed in master now and that I don't need to explicitly specify those command line args anymore. Thanks!
