### ISSUE TITLE
building with rust 1.32

### ISSUE THREAD

**Issue by d3spwn** [romanz/electrs#140]
Is it still possible to build with rust 1.32? Debian has not yet updated their rust package to 1.34.

**Comment by romanz** [comment]
Good point, and thanks for opening this issue!
I think that it should work by reverting https://github.com/romanz/electrs/commit/62592dbabf7fcc2c71830c434d2c8e3df6e2b5d0.
Will try and update this issue.

**Comment by d3spwn** [comment]
Thanks, reverting that commit i was able to build again (v0.6.1).

**Comment by romanz** [comment]
Great :)
I'll release the fix in the following release.

**Comment by romanz** [comment]
I think that Debian buster should support Rust 1.34 now :)
https://packages.debian.org/buster/rustc
