### ISSUE TITLE
How to use ElectRS for private server?

### ISSUE THREAD

**Issue by Engelberg** [romanz/electrs#147]
I can't figure out from the documentation if I run the release version with the default settings listed in Usage.md, how "exposed" the server is to other computers outside my local network.

Specifically, I can't determine from the documentation whether it is possible to configure ElectRS as a private server for use solely from an electrum wallet running on my local machine.  If so, what configuration settings are needed to "lock it down" in this manner?

Even better, my ideal would be to have it running as an TOR hidden service that only I can connect to, remotely.  Can you point me to any directions on how to set that up? Thanks.

**Comment by romanz** [comment]
By default, electrs is listening on `localhost`, so it should not be accessible from other machines.
You can change the default settings by setting the `--electrum-rpc-addr` flag:
https://github.com/romanz/electrs/blob/0858b627e18784f5b870ca27bb8f4de5a26e63c3/src/config.rs#L87-L92

**Comment by romanz** [comment]
Regarding Tor -> https://github.com/romanz/electrs/issues/148 :)

**Comment by romanz** [comment]
Please take a look at #154 and let me know if it works for you.
