### ISSUE TITLE
Allow running as a Tor hidden service

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#148]

**Comment by seth586** [comment]
To run as a tor hidden service, config `torrc` with the following, then restart `tor`:
```
HiddenServiceDir /var/db/tor/remote_connections
HiddenServiceVersion 3
HiddenServicePort 50002 127.0.0.1:50002
```

Then run `electrs` pointing to the local machine for connections:
```
/usr/local/bin/electrs --db-dir=/var/db/electrs --electrum-rpc-addr=127.0.0.1:50002 --daemon-dir=/var/db/bitcoin
```

In the above example, the onion address will be in a file named `/var/db/tor/remote_connections/hostname`

Configure your client machine with a tor connection (start tor browser on windows) then run the following electrum command to only connect to your server (on windows right click the electrum shortcut and change to this): `"C:\Program Files (x86)\Electrum\electrum-3.3.6.exe" -1 -s asdlkjfhpawsiudofhaps4d7fha9s5dfhaps6dfhasfd7hadfsph.onion:50002:t`

The above is for a FreeBSD server environment for remote connections to a windows client, linux should be similar. For more in FreeBSD, check out my guide here: https://github.com/seth586/guides/blob/master/FreeNAS/extras/electrs.md

**Comment by romanz** [comment]
Many thanks for the information!
I've opened #154 - could you please take a look?
