### ISSUE TITLE
What happens when you start electrs and bitcoind isn't fully synced yet?

### ISSUE THREAD

**Issue by Engelberg** [romanz/electrs#150]
It would be great if, after rebooting the computer, I could kick off bitcoind and immediately kick off electrs and trust that it would eventually connect up when bitcoind is ready.  I haven't been brave enough to test it myself -- I don't want to break anything.  What is it's current behavior?  Thanks.

**Comment by romanz** [comment]
Good question - in this case, electrs should wait for bitcoind to finish its initial sync (it will poll bitcoind once every N seconds) - and then start its own sync.
I think that it should be OK, you can start electrs and bitcoind simultaneously :)

**Comment by Engelberg** [comment]
Thanks for your work! I'm really happy to have an electrum server up and running locally.
