### ISSUE TITLE
Use configure_me instead of clap?

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#151]
Electrs now uses `clap` and command line for configuring the server. This has two significant downsides: there's lot of arguments that need to be passed and it's clunky to work with. The other issue is that by passing cookie (password) as argument, it's visible to other processes - including processes of other users.

In order to resolve this, I suggest to swap `clap` for [`configure_me`](https://crates.io/crates/configure_me), as that automatically generates the code for both argument parsing, env vars and loading of config files. The downside is it doesn't have all the features of `clap`. It worked well so far for my projects but there are still some things that need polishing.

As `configure_me` is my crate, I'm offering to implement this, since I know it well. Further, I offer to implement any feature that's missing in `configure_me` that's needed for `electrs`. The nice thing is that the generated code will create config struct exactly as the one used today.

I opened the issue first in order to not waste time if this idea is rejected.

What do you think?

**Comment by romanz** [comment]
Your crate looks great, many thanks for the suggestions!
I'd be happy to switch to `configure_me` - please let me know how may I help :)

**Comment by Kixunil** [comment]
This issue needed a few new features to `configure_me` to be backwards-compatible and work well, which I implemented recently (released few minutes ago). I'm now going to look at it.

From what I see, there's `log` field in the `Config` struct, which needs two parameters to construct. I was thinking about it and I think it's better to create a separate struct in a submodule and copy its' fields instead of trying to cram a special feature into `configure_me` just for this. I'm going to take this way for now, let me know if you prefer some other approach. 

Also, there's `network` field using type from `bitcoin` crate. I'm going to use newtype to implement `ParseArg` and `Deserialize` for now, but I'll consider making a PR against `bitcoin` repo later to implement `ParseArg` directly.

**Comment by romanz** [comment]
Sounds great, thanks!

**Comment by Kixunil** [comment]
I noticed, `bitcoin::network::constants::Network` uses `"bitcoin"` to represent main network, while `electrs` uses `"mainnet"`. It'd be easier to implement parsing using existing functions (with `bitcoin` instead of `mainnet`) but that breaks CLI compatibility. What should I do?

**Comment by romanz** [comment]
I am fine with breaking CLI compatibility, will bump the version accordingly.

**Comment by Kixunil** [comment]
Great, in that case, I'm also removing `cookie` from arguments and env vars in order to prevent users misusing it, thus resolving the security issue mentioned above.
