### ISSUE TITLE
RPC call to gracefully stop electrs

### ISSUE THREAD

**Issue by reynico** [romanz/electrs#155]
Hi, is there any RPC call to gracefully stop electrs instead of killing the process?

**Comment by romanz** [comment]
If you send `SIGINT` or `SIGTERM` to electrs, it should exit gracefully:
```
2019-07-17T12:29:29.795+03:00 - INFO - Electrum RPC server running on 127.0.0.1:50001 (protocol 1.4)
^C2019-07-17T12:29:32.440+03:00 - INFO - stopping server: Interrupted by signal 2
```

**Comment by romanz** [comment]
I can add an additional "shutdown" RPC, but note that it's not part of the Electrum protocol:
https://electrumx.readthedocs.io/en/latest/protocol-methods.html

**Comment by brandoncurtis** [comment]
Note that `electrs` doesn't appear to respond to SIGINT or SIGTERM if it's in the initial sync process.

**Comment by reynico** [comment]
Thanks @romanz ! I'll close this issue.

**Comment by romanz** [comment]
@brandoncurtis @reynico Please take a look at #158
