### ISSUE TITLE
Anomalous long sync

### ISSUE THREAD

**Issue by emanuelelaface** [romanz/electrs#160]
I started electrs as:
```cargo run --release -- -vvvv --index-batch-size=10 --jsonrpc-import --db-dir /Bitcoin/electrs-database --electrum-rpc-addr="192.168.212.200:50001" --daemon-dir=/Bitcoin/bitcoin-database```

and it is 11 hours (and counting) that it is synching. The machine is a quad core atom 1.6GHz with 16 GB of RAM, not particularly fast but still it is more than 5 times of what is written in the documentation.

Moreover the strange part for me is that in the documentation is written that exactly one year ago (August 2018) the DB was 38GB. The blockchain increased of a factor 1.3 in the last year, so I was expecting a total sync of more or less 1.3 times that is 50GB. I am now at 61GB and it does not seems to stop here.

I hope that something is wrong in my sync otherwise it means that the DB of electrs is growing faster than the Blockchain and this, in the long term, can be an issue.

The log in the terminal is:
``` Running `target/release/electrs -vvvv --index-batch-size=10 --jsonrpc-import --db-dir /Bitcoin/electrs-database '--electrum-rpc-addr=192.168.212.200:50001' --daemon-dir=/Bitcoin/bitcoin-database`
Config { log: StdErrLog { verbosity: Trace, quiet: false, timestamp: Off, modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin, db_path: "/Bitcoin/electrs-database/mainnet", daemon_dir: "/Bitcoin/bitcoin-database", daemon_rpc_addr: V4(127.0.0.1:8332), cookie: None, electrum_rpc_addr: V4(192.168.212.200:50001), monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: true, index_batch_size: 10, bulk_index_threads: 4, tx_cache_size: 10000, txid_limit: 100, server_banner: "Welcome to electrs 0.7.1 (Electrum Rust Server)!", blocktxids_cache_size: 100 }
DEBUG - Server listening on 127.0.0.1:4224
DEBUG - Running accept thread
INFO - NetworkInfo { version: 180000, subversion: "/Satoshi:0.18.0/" }
INFO - BlockchainInfo { chain: "main", blocks: 589762, headers: 589762, bestblockhash: "0000000000000000000a48dab7dc2a11d2a1c1c2a9cd4c6e32f4458e2f993706", pruned: false, initialblockdownload: false }
DEBUG - opening DB at "/Bitcoin/electrs-database/mainnet"
TRACE - lastest indexed blockhash: 0000000000000000000000000000000000000000000000000000000000000000
TRACE - downloading 100000 block headers
TRACE - downloading 100000 block headers
TRACE - downloading 100000 block headers
TRACE - downloading 100000 block headers
TRACE - downloading 100000 block headers
TRACE - downloading 89763 block headers
INFO - best=0000000000000000000a48dab7dc2a11d2a1c1c2a9cd4c6e32f4458e2f993706 height=589762 @ 2019-08-12T09:24:53Z (589763 left to index)```

The LOG file is in attachment.
[LOG.gz](https://github.com/romanz/electrs/files/3494298/LOG.gz)

**Comment by emanuelelaface** [comment]
UPDATE: the server synced correctly after ~15 hours. The size of the db  reaches 85GB during the sync and then is reduced to 49GB that is in line with my initial estimation, so it seems that the DB scales as the blockchain (as expected).
The only strange thing was the very slow sync compared to what is in the manual, but I am not sure if it is a real issue, so I am going to close this issue.

**Comment by romanz** [comment]
Many thanks for detailed report!
I'll update the documentation with the relevant information regarding the initial sync duration and storage usage.
