### ISSUE TITLE
v0.7.1 gets stuck after watching many addresses

### ISSUE THREAD

**Issue by hkjn** [romanz/electrs#163]
(Could be related to / improved by #146?)

With electrs v0.7.1 and Electrum v3.3.8, it seems that electrs gets into some unresponsive state fairly often for me. In this state, Electrum's UI shows "synchronizing 0/1.." indefinitely, and meanwhile electrs logs show no requests, apart from periodic `PeriodicUpdate` entries:

```
$ electrs -vvvv
TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.transaction.get\", \"id\": 1, \"params\": [\"[redacted]\"]}\n")
[...]
TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.transaction.get\", \"id\": 1222, \"params\": [\"[redacted]\"]}\n")
TRACE - RPC PeriodicUpdate
TRACE - RPC PeriodicUpdate
^CINFO - stopping server: Interrupted by signal 2
TRACE - stop accepting new RPCs
TRACE - closing 1 RPC connections
TRACE - waiting for 1 RPC handling threads
TRACE - RPC PeriodicUpdate
Killed
```

It seems that this state occurs more often after I tweaked the gap limit settings for some wallets, causing an amplification in the number of addresses watched, which led to 1200+ `blockchain.scripthash.subscribe` calls once a number of Electrum wallets with lots of transactions are open. The issue could be a problem with Electrum instead of electrs, though I think it's more likely to be with electrs since a restart of electrs does address the issue.

There's a separate issue that potentially could be related or provide a clue here, which is that electrs in this state seems to not shut down in response to `SIGINT`, as seen in the logs above it does log a message but never seems to close down (at least not within several minutes of waiting).

I haven't found a way to reproduce the issue reliably yet, but let me know if there's any way I can provide more information to help debug or fix this.

**Comment by romanz** [comment]
Thanks for reporting this issue!
It sounds definitely like some issue with the notification handling code - it should be improved when #146 will be resolved.

By the way, I planned that electrs will be used for watching O(10) addresses and never tried/succeeded running electrs on more than 100 addresses :)

**Comment by hkjn** [comment]
> It sounds definitely like some issue with the notification handling code - it should be improved when #146 will be resolved.

Cool, thanks for confirming.

> By the way, I planned that electrs will be used for watching O(10) addresses and never tried running electrs on more than 100 addresses :)

Ah, hehe. I guess that's the risk of building reliable and useful software; people will start using it in ways never intended. :)

Let me know if there's an easy way to profile what electrs is up to at run time (even in the form of a basic pointer to some Rust profiling 101 or something; I am new to the language), in which case I could start to get familiar with the structure of the code and what needs to be more efficient myself and see if I could contribute more directly in the future.

For this issue, feel free to handle it as you see fit, i.e closing it right now if you think #146 already has all the info needed.

**Comment by romanz** [comment]
Thanks!
I was using Prometheus to monitor the performance of electrs, but you can just use basic timing tools, such as `std::time::Instant`.

**Comment by engenegr** [comment]
1. Lots of addresses should be batched to Electrs with pauses.
2. Although, 10K scripthashes were ok for some time, it looks like server stops subscriptions when significant amount of addresses is achieved.

I'm not a Rust developer, I cant say anything about server code. But I'm working on the client side.
