### ISSUE TITLE
Missing header in DB

### ISSUE THREAD

**Issue by mcsnubbs** [romanz/electrs#165]
Ive attempted to follow these instructions on Mac OSX but am getting the following error - any help appreciated.
```
$ cargo run --release -- -vvvv --index-batch-size=10 --jsonrpc-import --db-dir ./db --electrum-rpc-addr="127.0.0.1:50001" --cookie="default_user:password_here"
    Finished release [optimized] target(s) in 0.10s
     Running `target/release/electrs -vvvv --index-batch-size=10 --jsonrpc-import --db-dir ./db '--electrum-rpc-addr=127.0.0.1:50001' '--cookie=default_user:password_here'`
Config { log: StdErrLog { verbosity: Trace, quiet: false, timestamp: Off, modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin, db_path: "./db/mainnet", daemon_dir: "/Users/XXX/.bitcoin", daemon_rpc_addr: V4(127.0.0.1:8332), cookie: Some("default_user:vpassword_here"), electrum_rpc_addr: V4(127.0.0.1:50001), monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: true, index_batch_size: 10, bulk_index_threads: 8, tx_cache_size: 10000, txid_limit: 100, server_banner: "Welcome to electrs 0.7.1 (Electrum Rust Server)!", blocktxids_cache_size: 100 }
DEBUG - Server listening on 127.0.0.1:4224
DEBUG - Running accept thread
WARN - failed to export process stats: failed to read /proc/self/stat
INFO - NetworkInfo { version: 180100, subversion: "/Satoshi:0.18.1/" }
INFO - BlockchainInfo { chain: "main", blocks: 593222, headers: 593222, bestblockhash: "00000000000000000004bee31c071797942fd9c11f09b14f22f5f2346c1d0185", pruned: false, initialblockdownload: false }
DEBUG - opening DB at "./db/mainnet"
TRACE - lastest indexed blockhash: 00000000000000000014b2241d763cc55c39da5e081fe421067109da934ec6aa
thread 'main' panicked at 'missing 00000000000000000014b2241d763cc55c39da5e081fe421067109da934ec6aa header in DB', src/index.rs:252:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
TRACE - closing DB at "./db/mainnet"
```

**Comment by romanz** [comment]
This is indeed weird - it seems that the index DB may be corrupted :(
Could you retry to reindex the blockchain (by deleting the `./db`)?
Also, could you run `electrs` with higher verbosity (i.e. with `-vvvv` instead `-vv`)?
Please let me know if it doesn't resolve the issue.

**Comment by mcsnubbs** [comment]
Thank you. Trying both now.

**Comment by mcsnubbs** [comment]
$ cargo run --release -- -vvvv --index-batch-size=10 --jsonrpc-import
--db-dir ./db --electrum-rpc-addr="127.0.0.1:50001"
--cookie="default_user:password"

*    Finished* release [optimized] target(s) in 2.52s

*     Running* `target/release/electrs -vvvv --index-batch-size=10
--jsonrpc-import --db-dir ./db '--electrum-rpc-addr=127.0.0.1:50001'
'--cookie=default_user:password'`

Config { log: StdErrLog { verbosity: Trace, quiet: false, timestamp: Off,
modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin,
db_path: "./db/mainnet", daemon_dir: "/Users/XXX/.bitcoin",
daemon_rpc_addr: V4(127.0.0.1:8332), cookie: Some("default_user:password"),
electrum_rpc_addr: V4(127.0.0.1:50001), monitoring_addr: V4(127.0.0.1:4224),
jsonrpc_import: true, index_batch_size: 10, bulk_index_threads: 8,
tx_cache_size: 10000, txid_limit: 100, server_banner: "Welcome to electrs
0.7.1 (Electrum Rust Server)!", blocktxids_cache_size: 100 }

DEBUG - Server listening on 127.0.0.1:4224

DEBUG - Running accept thread

WARN - failed to export process stats: failed to read /proc/self/stat

INFO - NetworkInfo { version: 180100, subversion: "/Satoshi:0.18.1/" }

INFO - BlockchainInfo { chain: "main", blocks: 593499, headers: 593500,
bestblockhash:
"0000000000000000000bf3649a2b3d6dc9edb1ee94862f9fd7a4fc12c9f01d1b", pruned:
false, initialblockdownload: false }

DEBUG - opening DB at "./db/mainnet"

TRACE - lastest indexed blockhash:
0000000000000000000000000000000000000000000000000000000000000000

TRACE - downloading 100000 block headers

TRACE - downloading 100000 block headers

TRACE - downloading 100000 block headers

TRACE - downloading 100000 block headers

TRACE - downloading 100000 block headers

TRACE - downloading 93500 block headers

INFO -
best=0000000000000000000bf3649a2b3d6dc9edb1ee94862f9fd7a4fc12c9f01d1b
height=593499 @ 2019-09-06T08:21:38Z (593500 left to index)

DEBUG - applying 593500 new headers from height 0

INFO - starting full compaction

INFO - finished full compaction

INFO - enabling auto-compactions

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value:
Error { message: "IO error: While open a file for random read:
./db/mainnet/000316.sst: Too many open files" }', src/libcore/result.rs:999
:5

note: run with `RUST_BACKTRACE=1` environment variable to display a
backtrace.

TRACE - closing DB at "./db/mainnet"

**Comment by romanz** [comment]
Could you run `ulimit -n 4096` command before starting `electrs`?
It would allow `electrs` to open a lot of file descriptors :)

**Comment by romanz** [comment]
Please re-open if still relevant.
