### ISSUE TITLE
fails to build

### ISSUE THREAD

**Issue by ebanutsa** [romanz/electrs#173]
error[E0432]: unresolved import `crate`
   --> electrs/target/release/build/electrs-404819c36a2e978e/out/configure_me_config.rs:269:21
    |
269 |     #[serde(crate = "crate::configure_me::serde")]
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ maybe a missing `extern crate configure_me;`?

**Comment by romanz** [comment]
Should be fixed by #175
