### ISSUE TITLE
Custom cookie file path

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#176]
It'd be nice to allow for custom cookie file path if the user uses non-default one. I will make a PR if nobody is faster than myself. :) ( Ihave some other important things to do right now.)

**Comment by k3tan172** [comment]
Definitely interested in this pull request @Kixunil, been looking for a way to allow for a custom cookie file path. At the moment I'm manually copying my .cookie file to ~/.bitcoin/cookie and electrs reading that. Symbolic links from ~/.bitcoin to my datadir don't seem to work either. Would be great to have this feature.

**Comment by Kixunil** [comment]
If you're running bitcoin and electrs under same user and using a different datadir because of mountpoints, you might want to use `rpccookiefile=/home/USER/.bitcoin/.cookie` in your Bitcoin configuration until this gets resolved.

**Comment by Kixunil** [comment]
I'm going to implement this and thinking about it. Suggested configuration name: `cookie_path`. The question is what should happen if the user sets both `cookie` and `cookie_path`. I would suggest to exit with error message complaining about ambiguous configuration so that the user immediately knows what's the problem.

However, it'd be nice if one could override the other with higher-level configuration. This would need a new feature in `configure_me`, which I was planning for a while - making an `enum` of exclusive parameters. The feature would be useful for `btc-rpc-proxy` too. I believe it can be added backwards-compatibly.

I'm going to write the code for what I suggested, @romanz please let me know if you'd like it to be different.

**Comment by romanz** [comment]
Sounds great, thanks a lot!
