### ISSUE TITLE
blockchainScripthash_getHistory by batch of addresses

### ISSUE THREAD

**Issue by gbenattar** [romanz/electrs#178]
Hi,
In our wallet we need to perform blockchainScripthash_getHistory for a batch of addresses and we would like to optimise on the Electrs side.

What do you think of such API? @romanz

**Comment by romanz** [comment]
Sounds good, let's just change the API endpoint name to have a different prefix/suffix, e.g. `blockchain.scripthash.get_history.multiple([hash1, hash2, ... hashN])`.

**Comment by romanz** [comment]
Latest release should support batched JSON-RPC request handling: #230
