### ISSUE TITLE
Update to latest `rust-bitcoin`

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#181]
https://crates.io/crates/bitcoin

**Comment by MichelKansou** [comment]
@romanz is it okay for a rust beginner ?

**Comment by romanz** [comment]
It may be a bit complex, but please try and let me know if you get stuck.

**Comment by MichelKansou** [comment]
@romanz I will do my best to understand it 😁 do I need a full node to test the code or `cargo test` should be fine ?

**Comment by romanz** [comment]
We can start with `cargo test` :)

**Comment by MichelKansou** [comment]
@romanz I updated to the lastest `rust-bitcoin` I got some dependance errors so I updated `bitcoin_hashes` and `cargo test` is fine 😆 do I need to check something else ?

**Comment by romanz** [comment]
Cool, many thanks!
Please open a PR :)

**Comment by romanz** [comment]
Tested locally, and it seems to work well - thanks a lot!
