### ISSUE TITLE
Suitable for a high traffic public server?

### ISSUE THREAD

**Issue by lukechilds** [romanz/electrs#187]
As per the description in the readme:

>The motivation behind this project is to enable a user to run his own Electrum server, with required hardware resources not much beyond those of a full node. The server indexes the entire Bitcoin blockchain, and the resulting index enables fast queries for any given user wallet, allowing the user to keep real-time track of his balances and his transaction history using the Electrum wallet. Since it runs on the user's own machine, there is no need for the wallet to communicate with external Electrum servers, thus preserving the privacy of the user's addresses and balances.

I'm wondering if electrs is suitable for a public high traffic server or if it's more targeted towards low traffic single local user scenarios. Maybe high traffic would put too much pressure on bitcoind for transaction retrieval?

So would you reccomend electrs for high traffic use cases or would ElectrumX be more suitable for that?

**Comment by lukechilds** [comment]
@romanz any update on this? Is this something you have an idea on or something that needs testing first?

**Comment by romanz** [comment]
Thanks for the question and sorry for the delayed response :)

Current design of electrs assume O(1) local low-traffic users - it can be easily DoS-ed, especially if using non-SSD storage for its transactions' index.

I wouldn't recommend using electrs for high-traffic public-serving scenario in its current form.

**Comment by lukechilds** [comment]
No worries at at all, good to know, thanks for the response.

**Comment by sunknudsen** [comment]
Hey @romanz, from a security perspective, how safe is it to allow a few potentially untrusted users to share a node that runs electrs as a Tor hidden service?

**Comment by romanz** [comment]
The main concern will be the lack of DoS-protection.
I would not recommend sharing electrs with untrusted users.
