### ISSUE TITLE
Allow cookie to be set via CLI flag or ENV var

### ISSUE THREAD

**Issue by lukechilds** [romanz/electrs#189]
>In addition, config files support cookie option to specify cookie - this is not available using command line or environment variables for security reasons (other applications could read it otherwise).

This good practise in general, however there are some scenarios where it may be useful to allow setting cookie via CLI flag or ENV var where it's not a security concern.

For example, in an isolated Docker network I just use the credentials `rpcuser:rpcpassword`. It's easy set between different containers and the RPC port isn't even accessible by the host, it's only internal to the Docker network.

To get this working with electrs I need to create a config file purely to set the cookie which is awkward. It would be great if I could just add `ELECTRS_COOKIE=rpcuser:rpcpassword` to my `docker-compose.yml`.

Are you open to allowing this?

**Comment by lukechilds** [comment]
Opened a PR for your convenience if you're open to this: https://github.com/romanz/electrs/pull/190

**Comment by romanz** [comment]
@Kixunil (as the author of `configure_me`)
What do you think?

**Comment by Kixunil** [comment]
The reasoning is good (also possibly useful with [`btc-rpc-proxy`](https://github.com/Kixunil/btc-rpc-proxy)), but I don't think we should just allow it without any kind of warning. I suggest to name it `--cokie-i-understand-security-implications`, but in that case I will need to add renaming feature to `configure_me`.

I'd really like to help you without introducing footguns for other people, so I have some other ideas.

Is this very important to you or you can live with the config file, at least for a while? I wonder, do you set everything else on command line or everything is default except for the cookie?

Would #176 solve your issue better? (`rpcport` and `rpcpassword` are deprecated in Core, BTW)

BTW, I've heard some negative information about Docker security from several independent sources, so you might want to avoid relying on its isolation.

**Comment by lukechilds** [comment]
>Is this very important to you or you can live with the config file, at least for a while? I wonder, do you set everything else on command line or everything is default except for the cookie?

This is the only config file that's required for my whole full node + electrum + tor + explorer setup. Everything else is configured purely inside my `docker-compose.yml` with environment variables.

I feel like that is the preferred Docker approach to configuration, but I understand this could be potentially dangerous to non Docker users so you might not want to accept it.

#176 wouldn't help in this regard as it's still file based.

I like the idea of allowing this behaviour but giving a warning to prevent accidental usage when it may be unsafe.

`--cookie-i-understand-security-implications <cookie>` seems a little verbose. What about just allowing `--cookie <cookie>`, but when used on it's own electrs just exits with a warning that this is potentially unsafe and to run again with `--allow-cookie` if you understand the risks.

Then running again with `--cookie <cookie> --allow-cookie` would run as normal.

Thoughts?

**Comment by Kixunil** [comment]
OK. The way `configure_me` works currently is it doesn't distinguish between file and command line arguments and I don't feel like adding such machinery.

When I was writing `configure_me`, I planned to implement renaming, but decided that it'd be code that allows people making inconsistent (confusing) setups, so decided against it. This is a good case for revisiting it.

One alternative trick would be to require the cookie at the end preceded with a parameter without `--` prefix. This can already be implemented without changes to electrs. If that seems verbose, maybe write it like this:

`electrs ... unsecure <COOKIE HERE>`

But that's quite ugly trick.

OTOH, I think argument renaming might not be too hard. Or maybe I could limit it to env var renaming, which might be even easier.

**Comment by lukechilds** [comment]
Yeah you should definitely do whatever you feel is best in a more general sense for `configure_me`. If argument renaming makes sense then lets go with that.

**Comment by lukechilds** [comment]
Actually now I think about it, #176 could be a nice solution!

I could have a shared volume for the bitcoind data dir between the bitcoind and electrs containers and then point electrs to the cookie file in the shared volume.

**Comment by Kixunil** [comment]
Awesome! I prefer that solution much more, because it solves the issue for other people too. I feel like doing some Open Source stuff now, so I'm going to look at it. :)

**Comment by Kixunil** [comment]
See the referenced PR. :)
