### ISSUE TITLE
The bitcoind cookie is printed in log

### ISSUE THREAD

**Issue by kallerosenbaum** [romanz/electrs#192]
When electrs starts, it prints the cookie used for communication with bitcoind to stdout. It should be excluded from log (except possibly on the highest verbosity level).

Tested with 0.8.0

**Comment by romanz** [comment]
It should be fixed in latest `master` branch: #191

**Comment by romanz** [comment]
Release [0.8.1](https://crates.io/crates/electrs) which should resolve this issue, please let me know if it works for you :)
