### ISSUE TITLE
Point of Clarification

### ISSUE THREAD

**Issue by BTCxZelko** [romanz/electrs#198]
I have a bitcoin core node implementation that maintains all blockheaders for tracking purposes in MySQL. Is it possible to use that same DB for the electrs db?

This would save me the 50GB of data. 

(not sure how to add the correct flag)

**Comment by romanz** [comment]
Currently electrs is using RocksDB (for performance reasons), but in theory, it should be possible to use another database.

**Comment by BTCxZelko** [comment]
Where would I make this modification?

**Comment by romanz** [comment]
https://github.com/romanz/electrs/blob/1498eed6bb07c029eef07bad43a4eb2c37e7d188/src/store.rs#L36

**Comment by BTCxZelko** [comment]
Thank you. Would this modification apply to an existing MySQL db docker? Or just that electrs would use a new MySQL instead of RocksDB?

**Comment by romanz** [comment]
I am not sure that I understand your question.
Could you please rephrase it?

**Comment by BTCxZelko** [comment]
Running Dojo and Electrs.
Dojo uses a dockerized MySQL/MariaDB for storing blockheaders and indexing similar to Electrs does with RocksDB. (At least i believe so)
So i'm curious if I can connect the two. If Electrs can simply be pointed to an existing DB to pull its information from.

**Comment by romanz** [comment]
I am not familiar with the Dojo project, so currently it is not supported.
