### ISSUE TITLE
Cannot connect to bitcoind

### ISSUE THREAD

**Issue by roth-a** [romanz/electrs#199]
I created a ~/.bitcoin/.cookie file with the line
`rpcuser:rpcpassword`

However I get from electrs
`reconnecting to bitcoind: no reply from daemon`
and from bitcoin debug.log
`ThreadRPCServer incorrect password attempt from 127.0.0.1:59596`

What am I doing wrong?

**Comment by roth-a** [comment]
I found out that reading the password from the .cookie file does not work with a custom rpc username and rpspassword.  However I would like to set a custom username and password.

**Comment by romanz** [comment]
You should run `bitcoind` with the `-rpcpassword` and `-rpcuser` parameters (or set them in the `bitcoin.conf` file).
See https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File

**Comment by roth-a** [comment]
> You should run `bitcoind` with the `-rpcpassword` and `-rpcuser` parameters (or set them in the `bitcoin.conf` file).
> See https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File.
> In `electrs`, you can use the config file to set the custom cookie as `USER:PASSWORD`:
> 
> https://github.com/romanz/electrs/blob/1498eed6bb07c029eef07bad43a4eb2c37e7d188/config_spec.toml#L35

I did specify the rpcuser and rpcpassword in the bitcoin.conf (and had in the past other services connect successfully to bitcoind).    I copied the username and password manually to .cookie (username:password), but still electrs was unable to connect to bitcoind.

In the past I was able to connect electrs using the commandline option "cookie" (Specifying the username and password in the commandline when starting electrs). However this was removed.

**Comment by roth-a** [comment]
How do you specify a custom rpcuser and rpcpassword and pass it to electrs?

**Comment by romanz** [comment]
You can also use `--cookie-file` added by #191.

**Comment by roth-a** [comment]
Thanks. But I tried this already too without success. The only option for me is currently to remove the custom user and password.

**Comment by romanz** [comment]
I think it should work with the latest version.

For example, set the following flags in `bitcoin.conf`:
```
rpcuser=user
rpcpassword=8WGfCK981eYio5MnsIqajB4SJnwGFI9oHc
```
Then, set the following cookie file for `electrs`:
```
$ echo "user:8WGfCK981eYio5MnsIqajB4SJnwGFI9o" > auth.cookie
$ electrs --cookie-file=auth.cookie
```

**Comment by roth-a** [comment]
I tried exactly this again (a different alphanumeric password though) and get the same error message
`WARN - reconnecting to bitcoind: no reply from daemon`

**Comment by romanz** [comment]
Please make sure that the cookie file doesn't end with EOL, i.e. (note the **-n**)
```
$ echo -n "user:8WGfCK981eYio5MnsIqajB4SJnwGFI9o" > auth.cookie
```

**Comment by roth-a** [comment]
This works!  Thanks!  I guess every editor I edited created a EOL without me noticing.  
Would it be worth it to improve the cookie reader to handle an EOL?

**Comment by groddeck** [comment]
I'm grateful I found this thread - I doubt I would ever have guessed the trailing EOL was the issue. I would strongly suggest adding at minimum better error message or documentation, but ideally updating the parser code to make it ignore whitespace.

**Comment by Kixunil** [comment]
I believe there was a PR to ignore the lines after the first one? I don't think Core supports multi-line passwords even in principle. (If it does, we shouldn't do it.) I'd be in favor of at least adding a warning if the password ends with a new line even though it leaks a bit of the password into the logs. We could add a config option to suppress the message but the config option also has to suppress itself from config debug output. That seems too much to me.
