### ISSUE TITLE
electrs hangs when querying address with 600K transaction history

### ISSUE THREAD

**Issue by wiz** [romanz/electrs#202]
```
INFO - handle GET /address/3JXRVxhrk2o9f4w3cQchBLwUeegJBj6BEp
TRACE - loop process - 1 events, 0.000s
TRACE -     -> wakeup; idx=0
TRACE - Worker::sleep; worker=WorkerId(0)
TRACE -   sleeping -- push to stack; idx=0
TRACE -     -> starting to sleep; idx=0
TRACE - loop process - 0 events, 0.000s
TRACE - Server::encode status=200, body=Some(Known(1577)), req_method=Some(GET)
DEBUG - flushed 1722 bytes
TRACE - State::close()
TRACE - flushed({role=server}): State { reading: Closed, writing: Closed, keep_alive: Disabled }
TRACE - shut down IO complete
TRACE -     -> task complete
TRACE - deregistering handle with poller
DEBUG - dropping I/O source: 1
TRACE - task complete; state=pool::State { lifecycle: ShutdownOnIdle, num_futures: 3 }
TRACE - try_steal_task -- signal_work; self=1; from=3
TRACE - signal_work -- notify; idx=0
TRACE - loop process - 0 events, 0.000s
TRACE - event Readable Token(4194303)
TRACE - loop process - 1 events, 0.000s
TRACE -     -> wakeup; idx=0
TRACE - Worker::sleep; worker=WorkerId(1)
TRACE -   sleeping -- push to stack; idx=1
TRACE -     -> starting to sleep; idx=1
TRACE - Worker::sleep; worker=WorkerId(0)
TRACE -   sleeping -- push to stack; idx=0
TRACE -     -> starting to sleep; idx=0
TRACE - loop process - 0 events, 0.000s
TRACE - loop process - 0 events, 0.000s
```

**Comment by shesek** [comment]
This seems like the [electrs fork](https://github.com/blockstream/electrs) that's used as part of esplora and not the upstream version maintained by @romanz, best to post it there next time (blockstream/electrs does not accept issues, but [blockstream/esplora](https://github.com/Blockstream/esplora/issues) does).

Requesting a popular address for the first time might take some considerable time. But after that, the data gets cached and receives delta updates for transactions in new blocks, which should be fast.

It definitely shouldn't hang on the first request though, even for [addresses](https://blockstream.info/address/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp) with millions of transactions in their history. What specs are you running this on? How long did it hang for before you gave up?

**Comment by wiz** [comment]
Sorry for the late response - yes I am using the Blockstream fork but you answered my question. I am using a fast server with SSD in raid 0 so I can do 1K iops easily. The query still takes a very long time (30 mins?) and during this time electrs backend is completely unavailable for requests. Forgive my ignorance, but isn't this the type of data that should be pre-indexed?

As a temporary workaround for this DoS attack vector, is there a list of Bitcoin addresses I can query to pre-cache them?

**Comment by wiz** [comment]
For the record the query for your address took 1 hour 7 minutes
```
% time curl -i http://127.0.0.1:3000/address/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp
HTTP/1.1 200 OK
content-type: application/json
cache-control: public, max-age=10
content-length: 309
date: Sun, 29 Dec 2019 07:55:26 GMT

{"address":"1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp","chain_stats":{"funded_txo_count":1601193,"funded_txo_sum":102033362021020,"spent_txo_count":1600304,"spent_txo_sum":102033350511441,"tx_count":3195822},"mempool_stats":{"funded_txo_count":0,"funded_txo_sum":0,"spent_txo_count":0,"spent_txo_sum":0,"tx_count":0}}curl -i http://127.0.0.1:3000/address/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp  0.05s user 0.05s system 0% cpu 1:07:31.63 total
```

**Comment by shesek** [comment]
There's a list of popular addresses (over 4k funding/spending entries) here: https://github.com/Blockstream/electrs/blob/new-index/contrib/popular-scripts.txt

You can get electrs to pre-cache all of them by starting it with `--precache-scripts /path/to/contrib/popular-scripts.txt`. This will probably take quite some time.

**Comment by wiz** [comment]
Thanks, it sounds like that precache feature was exactly what I was looking for. Why don't you enable this by default and pre-cache everything? Isn't that the whole point of having an electrs backend?
