### ISSUE TITLE
"WARN - failed to send PeriodicUpdate to peer 0: sending on a full channel"

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#206]
https://twitter.com/BitcoinSloth/status/1207436829399629824

**Comment by Marfy22** [comment]
I also get this if electrs is running for some time (mine was running for > 30 hours+)
It hasn't appeared again after I restarted the electrs server, since a few minutes ago. It works without any warnings now.

**Comment by romanz** [comment]
Sorry for the delayed response.
It should be safe - will change this log message to DEBUG.
