### ISSUE TITLE
How to gracefully exit electrs?

### ISSUE THREAD

**Issue by nepsilon** [romanz/electrs#208]
Once launched with `cargo run --release --bin electrs -- -vvvv --db-dir=. --daemon-dir ./btc-mainnet --electrum-rpc-addr="127.0.0.1:50001"`, the process doesn't respond to neither `SIGTERM` or `SIGINT`.

A `SIGKILL` results in a corrupted DB:
```
thread 'main' panicked at 'missing 0000000000000000000d7a734d0a608aa587660ae25dc391763cba2a1f7c9343 header in DB', src/libcore/option.rs:1166:5
```

Is there a way to gracefully exit electrs?

**Comment by nepsilon** [comment]
I tried to repair rocksdb with `rocksdb_ldb repair` but while `repair` told me it recovered some files, I still get a panic message when relaunching electrs:

```
thread 'main' panicked at 'missing 0000000000000000000d7a734d0a608aa587660ae25dc391763cba2a1f7c9343 header in DB', src/libcore/option.rs:
```

**Comment by HardCorePawn** [comment]
I've always just used CTRL+C and that seems to exit it OK. 

```
...
2020-01-08T10:45:03.355+13:00 - INFO - best=0000000000000000000c70e9371759a0625a69e8447a9b5eeeb0e500e84c2921 height=611795 @ 2020-01-07T21:44:50Z (1 left to index)
2020-01-08T10:45:03.376+13:00 - DEBUG - applying 1 new headers from height 611795
^C2020-01-08T10:51:10.293+13:00 - INFO - stopping server: Interrupted by signal 2
hardcorepawn@HardCorePC:~/electrs$
```

NOTE: running on Ubuntu under Windows Subsystem Linux (aka WSL)

**Comment by dagurval** [comment]
SIGINT exited cleanly last time I tested, did you try that?

**Comment by romanz** [comment]
Thanks for opening this issue, and sorry for the delayed response.
It should be safe to CTRL+C it after the initial sync is over.

**Comment by smartm0use** [comment]
Since the initial sync may take several hours or days... how to gracefully exit electrs before 100% synced?

I used CTRL+C but I get an error about failing to close db or something similar. Luckily it resumes with no problems when I launched it again.

**Comment by romanz** [comment]
Latest code should support graceful indexing cancellation:
https://github.com/romanz/electrs/blob/172d76bbad378da8d3ca3b88c4f17e2473dec34e/src/index.rs#L206
