### ISSUE TITLE
Can't connect to my electrs - No errors

### ISSUE THREAD

**Issue by danbadjar** [romanz/electrs#211]
Hello,
sorry for the newbie question but I can't connect to my electrs server.

Situation: 
A) PC with Electrum 3.3.8 client
B) Server Bitcoin full node with Electrs fully synced

Electrs is listening on port 50001. If I try to telnet to that port I obtain a response.
Electrum in configured to connect to 192.168.1.10 (Local server address) at port 50001.

I have no errors and Electrum is stuck on "Not connected"

Do you have any idea?
Thanks in advice

**Comment by danbadjar** [comment]
Sorry found the mistake:

I have changed che config file with:

server": "192.168.1.10:50001:t"

And now it works

**Comment by OliverOffing** [comment]
Appending `:t` solved my problem too. Doesn't make a lot of sense to me though. @danbadjar how did you figure it out?
