### ISSUE TITLE
Connect via http

### ISSUE THREAD

**Issue by jlopp** [romanz/electrs#212]
I installed electrs on a home server and want to access it from other machines on my home network. I'm not concerned about network eavesdroppers so I haven't set up nginx as an SSL proxy. However, when I try to connect via the latest Electrum client on another machine, electrs logs an error:

> receiver failed: invalid request - maybe SSL-encrypted data? [CSV of lots of numbers]

It's not clear to me if the problem lies with electrs or with electrum - I can't find a way to tell electrum not to use SSL; does electrs support / signal unencrypted connections?

**Comment by dagurval** [comment]
How are you connecting using electrum? 

If you used the method in the [usage doc](https://github.com/romanz/electrs/blob/master/doc/usage.md), the `:t` postfix should tell the Electrum client to not use SSL

```
electrum --oneserver --server=127.0.0.1:50001:t
```

**Comment by dagurval** [comment]
Btw, the connection is not over HTTP, just regular TCP socket. Electrs does not have SSL support, by itself it only supports unencrypted connections.

**Comment by jlopp** [comment]
I was trying to set the server in the electrum GUI; apparently it assumes SSL.

Weird; I read that usage doc several times and managed to miss the "client" section each time. Got it working now; thanks!
