### ISSUE TITLE
Save state when restarting during initial sync

### ISSUE THREAD

**Issue by benma** [romanz/electrs#213]
I restarted electrs before the initial indexing was finished.

After a restart, it starts indexing at block 0:

```
DEBUG - applying 612254 new headers from height 0
TRACE - indexed ".bitcoin/blocks/blk00001.dat": 0 rows
TRACE - indexed ".bitcoin/blocks/blk00002.dat": 0 rows
TRACE - indexed ".bitcoin/blocks/blk00003.dat": 0 rows
TRACE - indexed ".bitcoin/blocks/blk00000.dat": 0 rows
...
```

The DB is still there, so 0 rows are indexed, but it takes the same amount of time.

I also restarted after the compaction seemed to hang after the initial sync, with the same result.

It would be good to improve this, so restarting picks off where it left off, even during the initial sync.

Additionally, it would help if the compaction step had some sort of log output indicating progress.

**Comment by romanz** [comment]
Thanks for opening this issue, and sorry for the delayed response.
Hope I would have the time to add this support in the next month...

**Comment by cjackie** [comment]
Is there update on this? I have an issue where the USB SSD drive seems to fail, during initial sync for Electrs. Then when I restarted Electrs, it started to load from block 0.

**Comment by Kixunil** [comment]
The version 0.9 can continue indexing **if you retart it nicely** - that means SIGINT. SIGKILL or whole-machine failure will cause reindexing from 0. If you have a faulty storage change that storage as you're asking for trouble not just with electrs but any software you're running there.
