### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by justinmoon** [romanz/electrs#216]
[This section](https://github.com/romanz/electrs/blob/master/doc/usage.md#bitcoind-configuration) of the documentation is a little unclear. This sentence in particular was baffling:

> please use cookie="USER:PASSWORD" option in one of the config files

- In an electrs config file?
- In my bitcoin.conf?

[This comment](https://github.com/romanz/electrs/issues/199#issuecomment-558319816) helped me figure out something that works: create a custom cookie file and manually specify it with `--cookie-file`

But perhaps that's not the optimal thing to do?

**Comment by romanz** [comment]
Good catch, thanks!
Will fix the docs!

**Comment by bensig** [comment]
This is still a bit unclear @romanz - happy to create a PR with some additional info to make this a bit simpler to understand once I get it working.

**Comment by romanz** [comment]
Please do :)

**Comment by bensig** [comment]
Ok and just for clarity - are we no longer supporting a cookie file at `~/.bitcoin/.cookie` as a cookie file containing `rpcuser:rpcpass`?

**Comment by Kixunil** [comment]
It should be supported. If it doesn't work please open an issue.
