### ISSUE TITLE
network option: incorrect help text

### ISSUE THREAD

**Issue by Stadicus** [romanz/electrs#218]
The command `electrs --help` gives the following description of the `--network` option:

```
$ electrs --help
Usage: electrs [ARGUMENTS...]

Arguments:
...
        --network                     Select Bitcoin network type ('mainnet', '
                                      testnet' or 'regtest')
...
```

For the Bitcoin mainnet, the expected value however is not `mainnet`, but `bitcoin`:

```
$ electrs --network mainnet
Error: Failed to parse argument '--network': Unknown network (type mainnet).

Hint: the value must be either 'bitcoin', 'testnet' or 'regtest'.
```

**Comment by romanz** [comment]
I think that the latest electrs should have the correct description:
https://github.com/romanz/electrs/commit/2f4389e1110155dbffd7bd9ab96b6b166be32a2a

**Comment by Stadicus** [comment]
Ok, perfect. I was building the latest release 0.8.2, which I think is about a week older than this commit.

**Comment by romanz** [comment]
Sounds like a good time for a new release :)

**Comment by romanz** [comment]
https://crates.io/crates/electrs/0.8.3 is published.
