### ISSUE TITLE
[Question] How to query electrs for what transaction spends a specific output?

### ISSUE THREAD

**Issue by pedr0-fr** [romanz/electrs#220]
[As mentioned here](https://github.com/romanz/electrs/blob/master/doc/schema.md#transaction-inputs-index), one of the advantages of electrs over electrumx is the ability to query which transactions spends a specific output. However, I didn't find how one is able to conduct such a query. Can someone please give an example of this type of query?

Thank you.

**Comment by romanz** [comment]
Please see #454
