### ISSUE TITLE
[Question] How to use any kind of cache?

### ISSUE THREAD

**Issue by ejose19** [romanz/electrs#221]
I noticed every time I connect from the same wallet, the sync start over. And at only ~150 transactions it takes about 30s to start, is there a way to cache the transactions to speed the process?

With any random server or even electrum-personal-server the "sync" doesn't appear, it just instantly loads the wallet where I left it (as long I don't change the server). Is there a way to replicate this on electrs?

**Comment by romanz** [comment]
Please try the latest version (0.9.0) - it should have better performance :)

**Comment by ejose19** [comment]
I've tried a fresh install with default config, but it's still slow, above 30s for ~400 transactions, for which I cannot reproduce the issue with something like `electrum-personal-server` where it just load instantly. On `electrum` side it's synchronizing every time I open the wallet, so it seems it's doing the "hard work" every time, an option to allow caching transactions would be good (especially if one intends to use `electrs` for personal usage only)

**Comment by romanz** [comment]
Thanks for testing and reporting this issue!
Could you please share the hardware spec of your machine/device running electrs?
If possible, could you please share more verbose log that can help us better understand the performance problem?
```
$ export RUST_LOG=electrs::p2p=debug,electrs::status=debug,electrs=info
$ <run electrs>
```

**Comment by romanz** [comment]
If possible, could you please try [Sparrow Wallet](https://github.com/sparrowwallet/sparrow) (which also works with electrs) to see if it performs better (since it supports [JSON RPC batching](https://github.com/romanz/electrs/issues/230))?

**Comment by romanz** [comment]
IIUC, [EPS](https://github.com/chris-belcher/electrum-personal-server) relies on bitcoind wallet to cache the relevant transactions, so it respond quickly to any wallet-specific query.
Our project allows querying any address, but it requires more processing to actually retrieve the relevant transactions.

**Comment by romanz** [comment]
Opened #530 :)

**Comment by romanz** [comment]
Closing for now, let's continue the discussion in #530.
