### ISSUE TITLE
relayfee should not be hardcoded to 0?

### ISSUE THREAD

**Issue by benma** [romanz/electrs#222]
Hi

I noticed this:

https://github.com/romanz/electrs/blob/cbc2214cd5eca54a0412bcc0d5302e345b613397/src/rpc.rs#L197-L199

Is there a reason this call would not get the relayfee from the `getnetworkinfo` relay call? It is is usually a 1000 sats.

**Comment by romanz** [comment]
Good catch, thanks!
Should be fixed by https://github.com/romanz/electrs/commit/9ecf131e3da4c2765e72f47453afc803a3650641.
