### ISSUE TITLE
gRPC + Protocol Buffers

### ISSUE THREAD

**Issue by tiero** [romanz/electrs#227]
On the line of this https://github.com/kyuupichan/electrumx/issues/993 would you be interested in potential contributions to take full advantage of HTTP2 streaming features and self-generating stubs with grpc/protobuf ? 
Thanks

**Comment by romanz** [comment]
PRs are always welcome :)
If possible, please add a new binary target here:
https://github.com/romanz/electrs/tree/master/src/bin/

**Comment by tiero** [comment]
>  a new binary target here

Do you mean to specify multiple binaries, so it would be compiled to two different executables one with the  JSONRPC and one with gRPC one?

Why not add in the same binary the gRPC interface exposed on a different port, where maybe the user could opt-in via a command?

**Comment by romanz** [comment]
> Why not add in the same binary the gRPC interface exposed on a different port, where maybe the user could opt-in via a command?

Sounds good.

**Comment by Kixunil** [comment]
Would be nice if it could work with both at the same time.
