### ISSUE TITLE
Support batched JSONRPC requests

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#230]
Following #228

**Comment by vlad20012** [comment]
What do you think about using https://github.com/paritytech/jsonrpc/tree/master/tcp ?

**Comment by romanz** [comment]
Thanks for the suggestion, will take a look :)

**Comment by vesparny** [comment]
Hi, is this feature being considered for future implementation?
Batched requests would definitely give a performance boost, especially for wallets containing multiple transactions

**Comment by Kixunil** [comment]
@vesparny if you're asking because you're experiencing performance issues it could be actually caused by inefficiency in some `electrs` code. We were brainstorming about it in #308 

If you have the time, you could check the `next` branch (and accompanied bitcoind fork) to see if your issue is fixed there. The branch still has to be changed but at least we would have more data.

**Comment by craigraw** [comment]
I believe that when Electrs is used over Tor (which is increasingly becoming the default), there is no improvement that will have a bigger impact on perceived performance. To illustrate this I created a custom build of Sparrow, loaded the same wallet twice and configured a connection to an ElectrumX server over Tor. One of the wallets used batched JSONRPC, the other did not. The difference was stark - the batched load completed in 7 secs while the non-batched in 68 seconds. Here are the loading logs - same wallet, same server:

![batching](https://user-images.githubusercontent.com/862166/118971979-55175400-b970-11eb-9071-baddd106d428.gif)

**Comment by Kixunil** [comment]
@craigraw I believe you're performing requests one-by-one, each issued only after previous completes, right? In that case it should be possible to send several requests in parallel to achieve better performance.

Of course I do agree that batching is just better. If parallel requests are easy to implement for you it might be a useful temporary solution.

**Comment by romanz** [comment]
Please take a look at #405 :)

**Comment by craigraw** [comment]
For the purposes of detecting and switching to batched JSON-RPC, can the 0.9.0 version be used (from the `client_name` of the `server.version` request)?

**Comment by romanz** [comment]
It's possible, but I would suggest sending a simple "batched" request to see if the server actually supports that :)
For example (note the `[...]` brackets):
```
$ echo '[{"jsonrpc": "2.0", "method": "server.ping", "id": 0}]' | netcat 127.0.0.1 50001
[{"id":0,"jsonrpc":"2.0","result":null}]
```

**Comment by Overtorment** [comment]
to my experience, you might accidentally crash an electrum server if you send unsupported request 😂

**Comment by romanz** [comment]
It was the case, but it should be resolved by https://github.com/romanz/electrs/pull/398 - i.e. electrs 0.8.10 shouldn't crash when getting an unsupported request :)
```
$ echo '[{"jsonrpc": "2.0", "method": "server.ping", "id": 0}]' | netcat 127.0.0.1 50001 
{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
```

**Comment by romanz** [comment]
Tested on latest https://github.com/sparrowwallet/sparrow version - seems to be working as expected :)

**Comment by craigraw** [comment]
This is embarrassing to say, but adding the `-rc*` to the end of the Electrs version broke the batching detection in Sparrow.  My bad!

I'll fix this going forward of course, but I'd greatly appreciate it if the `0.9.0` final release had no suffix so the current Sparrow release works. I'm sure this will be the case anyway. Thanks!

**Comment by romanz** [comment]
No worries, and thanks for letting me know :)
