### ISSUE TITLE
Question: interacting with the server with cURL 

### ISSUE THREAD

**Issue by gustavonalle** [romanz/electrs#237]
I am trying to send any request to the server via curl, for example:

```
 curl -H "Content-Type: application/json" --data-binary "{"jsonrpc": "2.0", "method": "server.version", "id": 0, "params": ["electrum/3.3.8", "1.4"]}" http://hostname:50001
```

But this fails when reaching the server:
```
Apr 18 16:15:27 endor electrs[2189724]: 2020-04-18T16:15:27.026+01:00 - TRACE - RPC Request("POST / HTTP/1.1\r\n")
Apr 18 16:15:27 endor electrs[2189724]: 2020-04-18T16:15:27.026+01:00 - ERROR - [192.168.1.72:50845] connection handling failed: Error: invalid JSON format
Apr 18 16:15:27 endor electrs[2189724]: Caused by: expected value at line 1 column 1
```

Clearly I must be sending something wrong, what is the correct way of sending those requests?

**Comment by gustavonalle** [comment]
😁
I was assuming the protocol was on top of http, but it's not :)

The correct way would be 

```echo '{"jsonrpc": "2.0", "method": "server.version", "id": 0, "params": ["electrum/3.3.8", "1.4"]}' | nc 127.0.0.1 50001```

Not sure it cURL even supports that

**Comment by moneroexamples** [comment]
Here is fork which provides http api: https://github.com/Blockstream/electrs
