### ISSUE TITLE
No reply from daemon

### ISSUE THREAD

**Issue by Oshirowanen** [romanz/electrs#244]
Followed the guide here:

https://github.com/romanz/electrs/blob/master/doc/usage.md

When I try to execute this command

cargo run --release -- -vvv --timestamp --db-dir ./db --electrum-rpc-addr="127.0.0.1:50001" --daemon-dir /mnt/external_bitcoin_blockchain

I get the following error messages:

![Screenshot from 2020-05-02 14-25-20](https://user-images.githubusercontent.com/7300803/80865367-d8d8a280-8c80-11ea-9f0c-b00a0faefb48.png)

The error changes from "failed to read cookie" to "no reply from daemon" when I created the .cookie file.  I have tried the following variations in the cookie file

user:pass
cookie="user:pass"

Why is this happening and how do I get it to work?

**Comment by Kixunil** [comment]
I'd recommend using cookie file properly:
* Set `rpccookiefile` to some file within existing directory which both `bitcoind` and `electrs` can access
* Set `--cookie-file` on command line or `cookie_file` in the electrs config file to the same file as above

This is the most robust and secure way to do it. If you're concerned about the security of bitcoind, you may consider [btc-rpc-proxy](https://github.com/Kixunil/btc-rpc-proxy).

Anyway, based on the fact that the cookie apparently wasn't created automatically by `bitcoind` and it isn't replying, it seems that you have a problem with `bitcoind` not running. Check its configuration and status.

**Comment by Kixunil** [comment]
FYI, this issue inspired me to make #245. I'd appreciate if you looked at the [new file](https://github.com/romanz/electrs/blob/233d2aa27714a152695464ab380c9727f3324d36/doc/usage.md) and reported if you find it clearer.

**Comment by Oshirowanen** [comment]
> FYI, this issue inspired me to make #245. I'd appreciate if you looked at the [new file](https://github.com/romanz/electrs/blob/233d2aa27714a152695464ab380c9727f3324d36/doc/usage.md) and reported if you find it clearer.

I'll go through this now and will let you know how I get on asap.

**Comment by Oshirowanen** [comment]
Got it working by switching from NTFS to Ext4.

**Comment by Kixunil** [comment]
So this issue can be closed, right?
