### ISSUE TITLE
Configuration error messages may be lost when used with systemd

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#247]
FYI, I found [a bug in `configure_me`](https://github.com/Kixunil/configure_me/issues/39) that probably affects `electrs` as well (didn't test, but the logic is obvious). Opening this issue so that affected people can find it. The workaround so far is to attempt to launch `electrs` manually from console in order to debug the problem. I will try to fix it ASAP.

**Comment by romanz** [comment]
No problem and thanks for the update!

**Comment by Kixunil** [comment]
So I've released a new version of `configure_me_codegen` that should fix it. `cargo update` should suffice. I would've made the PR myself but lately I have trouble compiling `electrs`, will have to take more time to figure it out.

I'm keeping this open until the version is updated in `Cargo.lock` or maybe even `Cargo.toml`.
