### ISSUE TITLE
Still full compact of DB on reboot

### ISSUE THREAD

**Issue by DrFredPhD** [romanz/electrs#249]
Hi, I've completed initial sync and full db compaction, and used the server successfully. Rebooting my server starts full compaction again and I cannot use the ElectRS server in the meantime, I've seen this issue was raised before but it still seems to be happening to me. Any ideas why?

**Comment by romanz** [comment]
Could you verify that the RocksDB index database is persisted between reboots?
Its path is specified by `db_dir` configuration option - and printed to the log on startup:
```
2020-05-14T09:24:47.336+03:00 - DEBUG - opening DB at "/home/user/.electrs/mainnet"
```

**Comment by DrFredPhD** [comment]
The directory seems persistent here is my log from yesterday

> May 13 22:28:05 raspberrypi electrs[7420]: 2020-05-13T22:28:05.398+01:00 - DEBUG - opening DB at "/mnt/hdd/app-storage/electrs/db/mainnet"
> May 13 22:28:09 raspberrypi electrs[7420]: 2020-05-13T22:28:09.660+01:00 - TRACE - lastest indexed blockhash: 000000000000000000087661c988790388aa208e1e028ae0f2b46b7288efb1ea
> May 13 22:28:24 raspberrypi electrs[7420]: 2020-05-13T22:28:24.947+01:00 - DEBUG - applying 630278 new headers from height 0
> May 13 22:29:34 raspberrypi electrs[7420]: 2020-05-13T22:29:34.442+01:00 - DEBUG - downloading new block headers (630278 already indexed) from 00000000000000000004b7c9a9d0aa7d0a7a7e21456ccf61155972daadacd0cc
> May 13 22:29:34 raspberrypi electrs[7420]: 2020-05-13T22:29:34.631+01:00 - TRACE - downloaded 3 block headers
> May 13 22:29:34 raspberrypi electrs[7420]: 2020-05-13T22:29:34.631+01:00 - INFO - best=00000000000000000004b7c9a9d0aa7d0a7a7e21456ccf61155972daadacd0cc height=630280 @ 2020-05-13T21:21:01Z (3 left to index)
> May 13 22:30:40 raspberrypi electrs[7420]: 2020-05-13T22:30:40.094+01:00 - DEBUG - applying 3 new headers from height 630278
> May 13 22:30:40 raspberrypi electrs[7420]: 2020-05-13T22:30:40.292+01:00 - INFO - starting full compaction
> May 14 00:43:26 raspberrypi electrs[7420]: 2020-05-14T00:43:26.819+01:00 - INFO - finished full compaction
> May 14 00:43:26 raspberrypi electrs[7420]: 2020-05-14T00:43:26.846+01:00 - INFO - enabling auto-compactions
> May 14 00:43:27 raspberrypi electrs[7420]: 2020-05-14T00:43:27.153+01:00 - INFO - enabling auto-compactions
> May 14 00:43:27 raspberrypi electrs[7420]: 2020-05-14T00:43:27.612+01:00 - DEBUG - downloading new block headers (630281 already indexed) from 0000000000000000000cfdd013bdcb08540366446bdc1051fd31121d5cc11d12

**Comment by romanz** [comment]
After compaction is over, Electrs writes a "marker" to the DB so it won't do it next time.
Maybe this write was not persisted.
Could you try to restart electrs without rebooting the device?

**Comment by DrFredPhD** [comment]
I restarted the service and it begins full compaction again. I noticed it doesn't shut down gracefully.

```
May 14 07:47:54 raspberrypi systemd[1]: electrs.service: State 'stop-sigterm' timed out. Killing.
May 14 07:47:54 raspberrypi systemd[1]: electrs.service: Killing process 7420 (electrs) with signal SIGKILL.
May 14 07:47:54 raspberrypi systemd[1]: electrs.service: Main process exited, code=killed, status=9/KILL
May 14 07:47:54 raspberrypi systemd[1]: electrs.service: Failed with result 'timeout'.
```

I have timeoutsec set to 300 in the service unit file.

**Comment by Kixunil** [comment]
So it seems the root issue is in stopping `electrs`, not starting. Which version do you use? I suspect [my recent commit](https://github.com/romanz/electrs/commit/bc45dbfe413a59e4b7b3e8e2fedca8e42090c2db) might have some bug. Could you try it two times, one before that commit and one after it?

@romanz this issue seems reappearing, do you think it's possible to write tests for it? I guess we would need to use regtest, let it sync, then send `SIGTERM` and wait for a few minutes. Maybe also connect with nc/socat to simulate a client.

**Comment by DrFredPhD** [comment]
I should checkout from romanz commit (a3bfdda32a1c8cab248d3525786a433d1e415d1e) just before yours? Can do, will take a bit of time to get back as build takes a little while and then when it full compacts will be a few hours each time.

**Comment by DrFredPhD** [comment]
My issue with compacting is now fixed though, as I rebooted the server after full compaction, without connecting a wallet, electrs shutdown gracefully and succesfully closed connection to the db which appears to have left the persistent 'marker' that full compaction was completed.

However, if I do connect electrum wallet to the server, sync wallet, close electrum, then stop electrs server, it will fail to shut down gracefully. Same result before and after mentioned commit.

`May 14 19:26:46 raspberrypi electrs[26619]: 2020-05-14T19:26:46.568+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 692, \"params\": [10]}\n")
May 14 19:26:46 raspberrypi electrs[26619]: 2020-05-14T19:26:46.568+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 693, \"params\": [5]}\n")
May 14 19:26:46 raspberrypi electrs[26619]: 2020-05-14T19:26:46.568+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 694, \"params\": [2]}\n")
May 14 19:26:49 raspberrypi electrs[26619]: 2020-05-14T19:26:49.572+01:00 - TRACE - RPC PeriodicUpdate
May 14 19:27:07 raspberrypi electrs[26619]: 2020-05-14T19:27:07.121+01:00 - DEBUG - downloading new block headers (630364 already indexed) from 000000000000000000036a77a8854de6133db83c0540bf912ed626a741469e4a
May 14 19:27:07 raspberrypi electrs[26619]: 2020-05-14T19:27:07.123+01:00 - TRACE - downloaded 1 block headers
May 14 19:27:07 raspberrypi electrs[26619]: 2020-05-14T19:27:07.123+01:00 - INFO - best=000000000000000000036a77a8854de6133db83c0540bf912ed626a741469e4a height=630364 @ 2020-05-14T18:26:16Z (1 left to index)
May 14 19:27:07 raspberrypi electrs[26619]: 2020-05-14T19:27:07.486+01:00 - DEBUG - applying 1 new headers from height 630364
May 14 19:27:11 raspberrypi systemd[1]: Stopping Electrs...
May 14 19:27:11 raspberrypi electrs[26619]: 2020-05-14T19:27:11.895+01:00 - INFO - stopping server: Interrupted by signal 15
May 14 19:27:11 raspberrypi electrs[26619]: 2020-05-14T19:27:11.895+01:00 - TRACE - stop accepting new RPCs
May 14 19:27:11 raspberrypi electrs[26619]: 2020-05-14T19:27:11.895+01:00 - TRACE - closing 3 RPC connections
May 14 19:27:28 raspberrypi electrs[26619]: 2020-05-14T19:27:28.883+01:00 - TRACE - RPC Done
May 14 19:27:28 raspberrypi electrs[26619]: 2020-05-14T19:27:28.883+01:00 - DEBUG - [127.0.0.1:34438] shutting down connection
May 14 19:27:28 raspberrypi electrs[26619]: 2020-05-14T19:27:28.883+01:00 - INFO - [127.0.0.1:34438] disconnected peer
May 14 19:28:12 raspberrypi systemd[1]: electrs.service: State 'stop-sigterm' timed out. Killing.
May 14 19:28:12 raspberrypi systemd[1]: electrs.service: Killing process 26619 (electrs) with signal SIGKILL.
May 14 19:28:12 raspberrypi systemd[1]: electrs.service: Main process exited, code=killed, status=9/KILL
May 14 19:28:12 raspberrypi systemd[1]: electrs.service: Failed with result 'timeout'.
May 14 19:28:12 raspberrypi systemd[1]: Stopped Electrs.`

**Comment by DrFredPhD** [comment]
v0.8.3 release appears to work fine

```
May 14 19:43:34 raspberrypi electrs[8606]: 2020-05-14T19:43:34.804+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 698, \"params\": [2]}\n")
May 14 19:43:37 raspberrypi electrs[8606]: 2020-05-14T19:43:37.115+01:00 - TRACE - RPC PeriodicUpdate
May 14 19:44:07 raspberrypi electrs[8606]: 2020-05-14T19:44:07.312+01:00 - DEBUG - failed to send PeriodicUpdate to peer 0: sending on a full channel
May 14 19:44:13 raspberrypi electrs[8606]: 2020-05-14T19:44:13.536+01:00 - DEBUG - failed to send PeriodicUpdate to peer 0: sending on a full channel
May 14 19:44:19 raspberrypi electrs[8606]: 2020-05-14T19:44:19.365+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"mempool.get_fee_histogram\", \"id\": 699}\n")
May 14 19:44:19 raspberrypi electrs[8606]: 2020-05-14T19:44:19.369+01:00 - TRACE - RPC Request("{\"jsonrpc\": \"2.0\", \"method\": \"blockchain.estimatefee\", \"id\": 700, \"params\": [25]}\n")
May 14 19:44:19 raspberrypi electrs[8606]: 2020-05-14T19:44:19.369+01:00 - ERROR - [127.0.0.1:38004] connection handling failed: Error: failed to send {"id":700,"jsonrpc":"2.0","result":0.00020929076708853245}
May 14 19:44:19 raspberrypi electrs[8606]: Caused by: Broken pipe (os error 32)
May 14 19:44:19 raspberrypi electrs[8606]: 2020-05-14T19:44:19.369+01:00 - DEBUG - [127.0.0.1:38004] shutting down connection
May 14 19:44:19 raspberrypi electrs[8606]: 2020-05-14T19:44:19.369+01:00 - INFO - [127.0.0.1:38004] disconnected peer #0
May 14 19:44:20 raspberrypi systemd[1]: Stopping Electrs...
May 14 19:44:21 raspberrypi electrs[8606]: 2020-05-14T19:44:21.086+01:00 - INFO - stopping server: Interrupted by signal 15
May 14 19:44:21 raspberrypi electrs[8606]: 2020-05-14T19:44:21.086+01:00 - TRACE - stop accepting new RPCs
May 14 19:44:21 raspberrypi electrs[8606]: 2020-05-14T19:44:21.086+01:00 - TRACE - closing 0 RPC connections
May 14 19:44:21 raspberrypi electrs[8606]: 2020-05-14T19:44:21.086+01:00 - TRACE - waiting for 0 RPC handling threads
May 14 19:44:21 raspberrypi electrs[8606]: 2020-05-14T19:44:21.086+01:00 - TRACE - RPC connections are closed
May 14 19:44:21 raspberrypi electrs[8606]: 2020-05-14T19:44:21.086+01:00 - TRACE - RPC server is stopped
May 14 19:44:22 raspberrypi electrs[8606]: 2020-05-14T19:44:22.248+01:00 - TRACE - closing DB at "/mnt/hdd/app-storage/electrs/db/mainnet"
May 14 19:44:22 raspberrypi systemd[1]: electrs.service: Succeeded.
May 14 19:44:22 raspberrypi systemd[1]: Stopped Electrs.
```

**Comment by Kixunil** [comment]
Thanks a lot for valuable information! I can't look at it in-depth right now, will do it later.

**Comment by romanz** [comment]
It seems that something got stuck during the shutdown process for 1 minute:
```
May 14 19:27:11 raspberrypi systemd[1]: Stopping Electrs...
May 14 19:27:11 raspberrypi electrs[26619]: 2020-05-14T19:27:11.895+01:00 - INFO - stopping server: Interrupted by signal 15
May 14 19:27:11 raspberrypi electrs[26619]: 2020-05-14T19:27:11.895+01:00 - TRACE - stop accepting new RPCs
May 14 19:27:11 raspberrypi electrs[26619]: 2020-05-14T19:27:11.895+01:00 - TRACE - closing 3 RPC connections
May 14 19:27:28 raspberrypi electrs[26619]: 2020-05-14T19:27:28.883+01:00 - TRACE - RPC Done
May 14 19:27:28 raspberrypi electrs[26619]: 2020-05-14T19:27:28.883+01:00 - DEBUG - [127.0.0.1:34438] shutting down connection
May 14 19:27:28 raspberrypi electrs[26619]: 2020-05-14T19:27:28.883+01:00 - INFO - [127.0.0.1:34438] disconnected peer
May 14 19:28:12 raspberrypi systemd[1]: electrs.service: State 'stop-sigterm' timed out. Killing.
```
I tried to reproduce it with regtest, but it seems to WAI.

**Comment by romanz** [comment]
Could you please try to reproduce it when running `electrs` from command-line (i.e. not via systemd)?

**Comment by DrFredPhD** [comment]
> Could you please try to reproduce it when running `electrs` from command-line (i.e. not via systemd)?

It exits fine if I haven't used the server but if I open electrum wallet, then close wallet it hangs at the same place when shutting down server.

```
2020-05-25T16:22:51.237+01:00 - DEBUG - [127.0.0.1:60000] shutting down connection
^C2020-05-25T16:23:21.968+01:00 - INFO - stopping server: Interrupted by signal 2
2020-05-25T16:23:21.968+01:00 - TRACE - stop accepting new RPCs
2020-05-25T16:23:21.968+01:00 - TRACE - closing 1 RPC connections
```

**Comment by pd1983** [comment]
I'm having the same problem, after rebooting my raspi, my server starts full compaction again. I have updated to version 0.8.3 but it's not solving the problem.

**Comment by romanz** [comment]
Could you please try [flush-marker](https://github.com/romanz/electrs/compare/flush-marker) branch?
It should actually write the marker to disk after compaction is over.

**Comment by romanz** [comment]
It seems that https://github.com/romanz/electrs/pull/260 can fix this issue.
Please take a look :)

**Comment by romanz** [comment]
@pd1983 
Could you please test the new electrs WIP version?
It can be built using the instructions here: #308
I hope it should resolve this issue :)
