### ISSUE TITLE
Support blockchain.scripthash.listunspent Electrum API

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#25]
https://github.com/kyuupichan/electrumx/blob/master/docs/protocol-methods.rst

**Comment by greenaddress** [comment]
blockchain.scripthash.listunspent should also be implemented for full 1.2 spec

**Comment by romanz** [comment]
Will be fixed tomorrow.

**Comment by greenaddress** [comment]
I know the title changed a few times but just to clarify: I think both blockchain.address.listunspent and blockchain.scripthash.listunspent  are part of the spec (although blockchain.address.listunspent is deprecated is easy to implement in terms of blockchain.scripthash.listunspent, like electrumx used to do, and technically part of 1.2)

**Comment by romanz** [comment]
Should be fixed by https://github.com/romanz/electrs/commit/321d655d7a2d66b1be5fba83977098ec378f999c.

**Comment by romanz** [comment]
@greenaddress You're right - I'll add support also for `blockchain.address.listunspent`.

**Comment by romanz** [comment]
Done :)
