### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by Oshirowanen** [romanz/electrs#250]
As far as I can tell, I think I have followed the instructions at at the link below correct:

https://github.com/romanz/electrs/blob/master/doc/usage.md

and have the bitcoin-core blockchain indexed in a rocksdb.

![x](https://user-images.githubusercontent.com/7300803/82154265-885a6b00-9864-11ea-9276-f10cd682e046.png)

![y](https://user-images.githubusercontent.com/7300803/82154275-9dcf9500-9864-11ea-9674-9efe9a363ca6.png)

However, I can't seem to find any usage instructions on how to connect to the index using Visual Studio Code C#.  

I know this may not be classed as an "issue" with the code with the code itself, but more of an issue with usage examples missing from the documentation which would be greatly appreciated for new comers.

If this is the wrong place to ask such a request, please suggest a better place.

Kind regards,

Oshirowanen.

**Comment by Kixunil** [comment]
The canonical usage example is Electrum wallet. :)

If you want to access the API from other application/programming language, you need to see [the Electrum protocol specification](https://electrum.readthedocs.io/en/latest/protocol.html)

**Comment by romanz** [comment]
You can start by issuing the RPCs using `netcat`:
```
echo '{"jsonrpc": "2.0", "method": "server.version", "id": 0}' | netcat 127.0.0.1 50001
{"id":0,"jsonrpc":"2.0","result":["electrs 0.8.3","1.4"]}
```

**Comment by Oshirowanen** [comment]
> You can start by issuing the RPCs using `netcat`:
> 
> ```shell
> $ echo '{"jsonrpc": "2.0", "method": "server.version", "id": 0}' | netcat 127.0.0.1 50001
> {"id":0,"jsonrpc":"2.0","result":["electrs 0.8.3","1.4"]}
> ```

This is basically the starting point I was after.  Out of curiosity, is it possible to send a public key/address using something similar and get it to return details about the public key such as how many bitcoin's it has?

**Comment by romanz** [comment]
Currently, electrs doesn't support `blockchain.address.get_history` since it was [removed](https://electrumx.readthedocs.io/en/latest/protocol-removed.html) from Electrum protocol).
I suggest taking a look at [contrib/addr.py](https://github.com/romanz/electrs/blob/master/contrib/addr.py) - it can be used as an example for converting an address into a scripthash and using Electrum `blockchain.scripthash.get_balance` API to get its balance.

**Comment by firepol** [comment]
> Currently, electrs doesn't support `blockchain.address.get_history` since it was [deprecated](https://electrumx.readthedocs.io/en/latest/protocol-removed.html).
> I suggest taking a look at [contrib/addr.py](https://github.com/romanz/electrs/blob/master/contrib/addr.py) - it can be used as an example for converting an address into a scripthash and using Electrum `blockchain.scripthash.get_balance` API to get its balance.

Hi @romanz, after writing my question I've found this one. I tried the `contrib/addr.py` script and that helps already. Just, some command lines examples are always handy for beginners who want to understand if the system is working or not.

Btw you wrote:
> electrs doesn't support blockchain.address.get_history since it was deprecated.

But I've seen in your code, in the rpc.rs file, that there is a `get_history`call, it just needs the scripthash like the `get_balance` one. The methos is called `blockchain.scripthash.get_history`, I tested it and it seems to work, so I guess that @Oshirowanen (or any future googler) would benefit from this little detail too ;)

**Comment by moneroexamples** [comment]
Its not C#, but In python it would be:

```python
import socket


def main():

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect(("127.0.0.1", 50001))
        s.sendall(b'{"jsonrpc": "2.0", "method": "server.version", "params": ["", "1.4"], "id": 0}\n')
        data = s.recv(1028)
        print(data)


if __name__ == '__main__':
    main()
```

**Comment by Kixunil** [comment]
This issue seems to be resolved. Any specific reason to not close it?
