### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by vlddm** [romanz/electrs#257]
Used to use electrumx features like websocket server and requests batching. 
Any changes to get both here?

**Comment by romanz** [comment]
Currently, those features are not supported in electrs - since the original design was serving a local Electrum client, implementing the minimum amount of features required to do so.
PRs are welcome :)

**Comment by Kixunil** [comment]
Do I understand correctly that electrum over websocket works same as normal RPC (same messages), just differing in the framing? If yes, then it should be fairly easy to implement.

**Comment by tiero** [comment]
You can run `websocat` on top, no need to add feature directly in here.

Do I understand correctly that Electrs is not going to support batching?

**Comment by romanz** [comment]
electrs does support batching (https://github.com/romanz/electrs/issues/230):
```
$ echo '[{"jsonrpc": "2.0", "method": "server.ping", "id": 0}, {"jsonrpc": "2.0", "method": "server.ping", "id": 1}]' | netcat 127.0.0.1 50001
[{"id":0,"jsonrpc":"2.0","result":null},{"id":1,"jsonrpc":"2.0","result":null}]

```
