### ISSUE TITLE
cannot install cfg_me

### ISSUE THREAD

**Issue by oitdmser** [romanz/electrs#262]
as recommended in the install guide I ran `cargo install cfg_me` but it errors as follows:

```
Updating crates.io index
error: could not find `cfg_me` in registry `https://github.com/rust-lang/crates.io-index`
```

**Comment by Kixunil** [comment]
Sorry, that was definitely my fault. I forgot to publish it. Thanks for reporting! It's published now, so it should work.

**Comment by oitdmser** [comment]
awesome, thanks for that, downloaded and worked!
