### ISSUE TITLE
Size of txstore

### ISSUE THREAD

**Issue by Naryck** [romanz/electrs#271]
Is there a way of reducing size of Electrs data of BTC blockchain? Or this is normal size for the current blockchain state?
What I see now in electrs:
```
/mnt/bitcoin/electrs/db/mainnet/newindex$ du -sh */
16M     cache/
213G    history/
409G    txstore/
```
All this space is occupied by .sst files:
```
/mnt/bitcoin/electrs/db/mainnet/newindex/txstore$ du -ch *.sst | grep total
409G    total
```

**Comment by shesek** [comment]
This appears to be a database of the [esplora electrs fork](https://github.com/Blockstream/electrs). The electrs db is much smaller, around 50GB.

**Comment by Kixunil** [comment]
62G on my machine.
