### ISSUE TITLE
Mempool position is wrong.

### ISSUE THREAD

**Issue by Transisto** [romanz/electrs#277]
This screencap shows switching between local electrs, electrumx and blockstream esplora server.

The real mempool position for this transaction is about 25mb from tip. 

![bs3](https://user-images.githubusercontent.com/388716/87839413-b9f1b180-c868-11ea-8744-b69dc7b7dfba.gif)

https://github.com/Blockstream/esplora/issues/231

**Comment by Kixunil** [comment]
Can you demonstrate the same using the same Bitcoind node? You're connecting to different nodes, which have different mempools. I believe it has nothing to do with `electrs`.

**Comment by Transisto** [comment]
1. at least 10 random electrum server have the same mb to tip +/- 2%
2. local electrs is consistently about 35% lower.
3. the only other electrs based node I know of, (blockstream) has number that are all over the place (but lower)
4. mempool viewer running on same node confirm that the mb to tip is much lower than it should be (same ~35%)

![bs4](https://user-images.githubusercontent.com/388716/87866290-0105a280-c94e-11ea-928c-5c681cb449c9.gif)

192168.31.29 is local node and consistent but always lower

How do you suggest I test with the same bitcoin node? beside running electrumx using same node. (too involved for me)

**Comment by Kixunil** [comment]
> beside running electrumx using same node

Unfortunately, that's the only way I know of for testing it. :(

**Comment by Transisto** [comment]
Is there a mempool setting that wouldn't include valid transaction with more than 10sat/bytes?

**Comment by Kixunil** [comment]
I don't see a reason to believe high-fee transactions are filtered-out, unless you have two specific transactions with different fees, higher one being included in mempool of one node only, lower one in both.

But it's possible to set a size limit on mempool in bitcoind configuration and it kics out **low-fee** transactions, so that might be the cause and it's the most likely scenario IMO.

**Comment by Transisto** [comment]
I could understand a mempool having more or less low value transactions,
but this is position from tip of a relatively high fee transaction.

**Comment by romanz** [comment]
Could you please reproduce this issue on 0.9.0 release?
