### ISSUE TITLE
"query make take a long time"

### ISSUE THREAD

**Issue by csh2000** [romanz/electrs#278]
Hello, running Electrum wallet 4.0.2 AppImage and connecting through Tor to Electrs 0.8.5 (myNode).

I have a wallet with an address with a lot of transactions, failing to connect to Electrs.

Electrs log:

![Electrs](https://user-images.githubusercontent.com/32745411/87856534-1ebc1300-c920-11ea-8982-45ace6330e3f.JPG)

And keeps connecting and disconnecting until I shut down the wallet.

Electrum wallet message first:

![First](https://user-images.githubusercontent.com/32745411/87856809-ddc4fe00-c921-11ea-838d-45cbeac15a6e.JPG)

then:

![Then](https://user-images.githubusercontent.com/32745411/87856812-e1588500-c921-11ea-98fb-54622c439298.JPG)

And keeps looping like that.

It was working fine previously, problem began some days ago.

Working fine with wallets with few tx...until I open this one.

Thanks!

**Comment by romanz** [comment]
Unfortunately, `electrs` doesn't support addresses with lot of transactions well (performance-wise).
You can increase the limit by setting `--txid-limit=N` to above the default 100 txs per address, but it probably won't work well...

**Comment by csh2000** [comment]
Thanks, good to know.

Close the Issue.

Best.
