### ISSUE TITLE
Too many open files.

### ISSUE THREAD

**Issue by duckartes** [romanz/electrs#28]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "IO error: While opendir: /mnt/DATA/.btc.n0de/electrs/mainnet: Too many open files"', libcore/result.rs:945:5
```

**Comment by duckartes** [comment]
Modifying: /etc/security/limits.conf

Adding: 

*         hard    nofile      500000
*         soft    nofile      500000
root      hard    nofile      500000
root      soft    nofile      500000

Solved it, but I don't know if this is the best, or safest way to go about it? Any downsides to doing it this way?

**Comment by romanz** [comment]
The latest version on [master](https://github.com/romanz/electrs/commits/master) should increase the limit to 2048 (https://github.com/romanz/electrs/commit/4c7413db9d751a0a6b13d35292534f4d35ef22a5), which seems to be enough on my machine.

Could you try to run it to see if it helps?

**Comment by romanz** [comment]
Closing this issue, it's a symptom of https://github.com/romanz/electrs/issues/11
