### ISSUE TITLE
Example to query electrs via curl

### ISSUE THREAD

**Issue by firepol** [romanz/electrs#281]
Hi, I'm new to electrs and I know it's used as backend for electrum wallets, but I was wondering if there is an API reference of the methods that can be called.

Also it would be cool to have a few examples with curl, like the ones of bitcoin RPC reference, e.g. see: https://developer.bitcoin.org/reference/rpc/getbestblockhash.html

In particular, I'd like to know what to call to **get the balance of an address**, via command line (or via python script, e.g. https://kryptomusing.wordpress.com/2017/06/12/bitcoin-rpc-via-python/).

Thanks for letting me know and best regards

**Comment by romanz** [comment]
The RPC protocol is documented here:
https://electrumx-spesmilo.readthedocs.io/en/latest/protocol.html

**Comment by romanz** [comment]
Added: https://github.com/romanz/electrs/blob/master/doc/usage.md#rpc-examples

**Comment by moneroexamples** [comment]
Basic example in python:

```python
import socket


def main():

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect(("127.0.0.1", 50001))
        s.sendall(b'{"jsonrpc": "2.0", "method": "server.version", "params": ["", "1.4"], "id": 0}\n')
        data = s.recv(1028)
        print(data)


if __name__ == '__main__':
    main()
```
