### ISSUE TITLE
Using electrs to emulate txindex

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#287]
I'd like to write some kind of RPC proxy that uses electrs to emulate `txindex=1`. The idea is to forward all calls to `bitcoind` except for `getrawtransaction` without the `blockhash` parameter. That one would first find the height from `electrs` database, then get the blockhash from `bitcoind` and then forward the original request with the block hash parameter added.

This would be useful for people who want to run `electrs` and have `txindex` but don't want to store the index twice. It'd also help people who synchronized `bitcoind` and `electrs` without `txindex` and now they found out they need `txindex` and don't want to experience downtime from reindexing.

`electrs` database contains all information needed for this, however, it's not accessible over RPC.

I propose either of these solutions:

* Expose a new RPC method (e.g. `blockchain.transaction.get_height`) which translates txid to height. This is minimal change and all the logic has to be handled by external program.
* Expose a new (optional) listener that would implement all the logic described above. This would be more performant but with the increased maintenance burden.

What do you think? If you approve any of those solutions, I will definitely write a PR.

**Comment by romanz** [comment]
Good suggestion - I think that adding `blockchain.transaction.get_height` is the easiest way.

**Comment by Kixunil** [comment]
Oh, when attempting to write it I found that there's already a function `lookup_confirmed_blockhash`, which does exactly what I need. So I will write `blockchain.transaction.get_confirmed_blockhash` using that function instead.

Please let me know if there's any reason not to.
