### ISSUE TITLE
Use P2P connection for new blocks' notifications

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#29]
To decrease the latency between getting a new block and notifying the Electrum wallet.
(https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/network/listener.rs)

**Comment by romanz** [comment]
https://github.com/romanz/electrs/commit/fd5db9b2fde34168b3d858289dada295ddc20ecb adds simple P2P listener.

**Comment by xanoni** [comment]
Hmm this has probably been implemented?
