### ISSUE TITLE
Receiving wallet updates ?

### ISSUE THREAD

**Issue by iangregsondev** [romanz/electrs#293]
Hi,

This is a bit of a newbie question, I do apologise.

I want to hook a wallet I am developing in dart to an electrum server and was hoping to use this implementation as its written in RUST.

It currently doesn't support websockets so how does the client (dart) receive updates to the wallet, new transactions etc.

Maybe I am overlooking something, I was hoping to use something like websockets.

If anybody has some info or help - it would be gratefully appreciated

Thanks.

**Comment by Kixunil** [comment]
Websocket is not implemented in `electrs` yet. See #257 

If you have experience in Rust, I think it shouldn't take you too long to add. If not, I might look at it later, but I'm not promising anything. :)

**Comment by iangregsondev** [comment]
Thanks @Kixunil , so if there is no websocket or does a client keep up to date ? Does he poll the electrumx server every xxx minutes ?

**Comment by Kixunil** [comment]
The original Electrum API allows [subscriptions](https://electrum.readthedocs.io/en/latest/protocol.html#blockchain-address-subscribe) over raw TCP socket and this is implemented in `electrs` too. If you can use raw TCP socket, you should be able to use it too. (Pretty much if it's not web browser app.)

**Comment by iangregsondev** [comment]
Ah, that's great then! I can put my own websockets in front - no probs!

Thanks for confirming, I need to a have a bit of a read with electrum :-)
