### ISSUE TITLE
Error when building index on a raspberry pi 4 4GB RAM

### ISSUE THREAD

**Issue by janis-mueller** [romanz/electrs#295]
- Built electrs from source (Electrs v0.8.5)
- Rust: v1.39.0
- Started to let it build the index

Building from source went successful in under 30 minutes on my pi, but when electrs starts to build its index I almost immediately get the following error message in the log: 
"'panicked at 'failed sending blocks to be indexed: "SendError(..)"', src/libcore/result.rs:1165:5"
https://termbin.com/6t7d

My hardware is completly new, less than a month old (raspberry pi 4 4GB, 1tb internal san disk ssd, 32GB industrial grade samsung sd card)

@openoms

**Comment by Kixunil** [comment]
`ERROR - server failed: Error: getblock RPC error: {"code":-1,"message":"Block not found on disk"}`

* Did you disable pruning? (`prune=1` in `bitcoin.conf`)
* Are you sure the database isn't corrupted? (Maybe the power failed at some point in the past?) You could fix this by running `bitcoind` with `reindex=1` (will take some time to process whole chain)

**Comment by janis-mueller** [comment]
Seemed to be a corrupt database indeed, going to do a complete resync and try it again after that, closing the issue for now.
