### ISSUE TITLE
When under load, Electrs connection unexpectedly closes on sending response

### ISSUE THREAD

**Issue by craigraw** [romanz/electrs#298]
When Electrs is under load (PeriodicUpdate running with 100+ script hashes subscribed), client requests can take a long time to complete on a limited resource (e.g. RPi4) device. It's unclear whether Electrs (0.8.5) or the operating system (Raspbian Buster) are responsible, but occasionally under these circumstances both the client and server report that the socket has closed. 

Specifically, Electrs logs:
```
connection handling failed: Error: failed to send .....
Caused by: Broken pipe (os error 32)
shutting down connection
disconnected peer
```

On the Java client side:
```
Caused by: java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.NioSocketImpl.endRead(NioSocketImpl.java:248)
        ....
```

Both errors are reported at the same instant. The Java client does not have any socket timeout and has been tested to be stable in the socket reading state for long periods. For this reason, and the fact that it only happens under load, it appears the connection closure is initiated from the  server-side when it detects it cannot write back to the client. It's unclear why the broken pipe itself occurs though, since the client is receiving other responses right up to the point of disconnection.

**Comment by Kixunil** [comment]
This is super-weird! Does it happen every time it's under load or only occasionally?

**Comment by craigraw** [comment]
Every time. If I load 3-4 smallish wallets in Sparrow Wallet it will happen after a few minutes, and then regularly every 3 minutes or so (Sparrow automatically resubscribes and checks history on reconnection). After reconnection, Electrs increasingly appears slower over this period until the disconnection occurs. The effect of a PeriodicUpdate is noticeable too.

**Comment by Kixunil** [comment]
Could you measure the time until disconnection? Would like to know if it's a magic constant 5 minutes.

**Comment by craigraw** [comment]
Unfortunately not: here are a couple:
```
Sep 20 16:12:32 node electrs[6593]: Caused by: Broken pipe (os error 32)
Sep 20 16:15:35 node electrs[6593]: Caused by: Broken pipe (os error 32)
....
Sep 20 19:27:45 node electrs[6593]: Caused by: Broken pipe (os error 32)
Sep 20 19:30:18 node electrs[6593]: Caused by: Broken pipe (os error 32)
```

Sometimes however it takes longer, but seems directly related to wallet usage (opening of wallets and transactions greatly increases the likelihood of it happening. At the time of it happening, Electrs is effectively unresponsive to new requests, so it would appear that is some kind of timeout occurring.

**Comment by Kixunil** [comment]
That's strange. I'd love to help you more but unfortunately I will be insanely busy this week and maybe the following week as well. Maybe @romanz has more time?

**Comment by romanz** [comment]
I am afraid that the problem here is that electrs is being I/O-bound when running periodic updates over the subscriptions :(

**Comment by romanz** [comment]
There are some optimizations that can be done - e.g. skipping index lookups if there are no new blocks found:
https://github.com/romanz/electrs/blob/d01b3c6f6e8661a87928e45b46be6f63642e4976/src/rpc.rs#L375
Also, #185/#186 may help.

**Comment by romanz** [comment]
Unfortunately, I won't have the time to work on those improvements this week...

**Comment by craigraw** [comment]
> I am afraid that the problem here is that electrs is being I/O-bound when running periodic updates over the subscriptions

Yes I agree this seems to be it. It would be great to get these changes into a new release since Electrs seems to be the default for RPi type hardware node setups now. 

Will try to find some time to try them myself. Also, should have mentioned previously - my setup is running an SSD.

**Comment by craigraw** [comment]
After further work I think that the connection closure was being initiated from the client side, and I've now managed to preserve connections even with Electrs under high load.

I'm going to close this one off. Thanks for the assistance!
