### ISSUE TITLE
Electrs returns incorrect notifications for subscriptions

### ISSUE THREAD

**Issue by craigraw** [romanz/electrs#302]
Electrs often returns incorrect script hash notifications on subscriptions upon broadcasting. Here is an example:

For the following testnet transaction: https://blockstream.info/testnet/tx/796f84c0708bec08e54f8df6398a05950655c0719c63199b8061408b83279101

This transaction consumes two UTXOS from one wallet (derivations m/0/8 and m/1/14), sends one UTXO to a second wallet and one UTXO back to a change address (derivation m/0/15). Both wallets have all relevant script hashes subscribed.

Immediately upon broadcasting this transaction, my logs contain the following:
```
Status updated for script hash ec45088bf312ce8c39769125cd794ebf7aa45fc653dd4c260f7b0e3dca06279d, was c938a1b11d03484e564086c01deef3adb13ee44266641b442d5c2a1a33d1f79f now e48b3f44272a364d4ceb5e0bf46edda5a56658891a1e260627e5b24328b1bda1
Testnet1 history event for node m/1/14
Status updated for script hash 80ad1110afa0dd34ab8b635d4ef54ed3a5e92332fcdc230925272eadeb68004c, was 7e98f47b9b58c3f302978e3048ff7210321d6373cf54c641975ee37ee226fdb3 now d981d4b7352b873b470bab7f1c82f0d3b9ff74d4f1e273f6029ff94dfd7d5405
Testnet1 history event for node m/0/8
Status updated for script hash f089f71780243989f9869af7ec5b0b38183d1ef1092ea75eea8efab30bd0f280, was 3b46c68bb8d274a6949d3d1c8d40236ed75bdc3a6745842ea3449f3ce9058d50 now ca374c93b163e11178ce6a9de0a687848fb1cea2bffbad4afffefd1f59b9a7ef
Testnet1 history event for node m/1/5
```

In this case, Electrs fails to notify that the history for the script hash at m/1/15 has changed, and instead erroneously indicates that m/1/5 has changed. This means that the revised history for m/1/15 is not fetched and the wallet history is incorrect. 

Generally, once the transaction confirms into the blockchain, Electrs will notify the correct script hashes and the wallet history can be repaired. However, mempool transactions are often incorrectly displayed until this happens. While in this case a change output script hash was the cause of the problem, I have seen a failure to notify changes on inputs as well. The problem does not always occur, but seems to be of higher likelihood with more script hashes subscribed and a more complex transaction.

**Comment by craigraw** [comment]
Here is another example. Two wallets open, around 100 script hashes subscribed.

Transaction: https://blockstream.info/testnet/tx/6abdf533d0f5a0a298783b82108ed7aae1a682af2a9a776e9c8230721be66f7b

Node derivations and script hashes:

```
Creating tx 6abdf533d0f5a0a298783b82108ed7aae1a682af2a9a776e9c8230721be66f7b, expecting notifications for 
inputs 
{m/0/9=9461b4ab379ce64c8667a60cb65312db7da2f162fb0c44145255694b02f7ae18, m/1/15=30f7b7c516150629cfd1890a560094f983b17d683a9e4bcd06d87668025b111e} and 
change 
{m/1/16=e134eed5d0df2d5edcf0c46fa5defbc71dd4d866b90e4d28359b233e807c3ec6}
```

Upon broadcast:

```
Status updated for script hash e134eed5d0df2d5edcf0c46fa5defbc71dd4d866b90e4d28359b233e807c3ec6, was null now aa3f363b197c54473d2cfaaed8e9500b0012c22b05af6bdcfa6c72500af50eed
Testnet1 history event for node m/1/16
```
As can be seen above, in this case both inputs to the transaction received no script hash subscriptions, so the wallet balance appears to a net positive rather than a net negative due to registering the change amount only.

Several minutes later when the transaction received it's first confirmation the wallet received the following:
```
Status updated for script hash 30f7b7c516150629cfd1890a560094f983b17d683a9e4bcd06d87668025b111e, was 1eec7a3f84978ceb34e71be5353c9d4552eef583ad43533bb4ae5542c3d954ee now a0f3eec1314022839eef8d618942e77b3dff5e2de04006aa794c42179d683889
Status updated for script hash e134eed5d0df2d5edcf0c46fa5defbc71dd4d866b90e4d28359b233e807c3ec6, was aa3f363b197c54473d2cfaaed8e9500b0012c22b05af6bdcfa6c72500af50eed now 4eebc03927c974bbf7abb973fa0a46e73e57bf30a44c461b0bef6c8df0a4b16d
Status updated for script hash 9461b4ab379ce64c8667a60cb65312db7da2f162fb0c44145255694b02f7ae18, was 3435c4ea1841ecf045430fb364335f9a3b961ef73539502f0b375cb28b78f42f now a373db0145489782e01b71599bf25e223ed023350410b2ecf54836d649ae4887
Testnet1 history event for node m/1/15
Testnet1 history event for node m/1/16
Testnet1 history event for node m/0/9
```

At this point all 3 script hashes have now been notified. Note however that I have omitted a lot of erroneous script hash notifications from the above for script hashes that did not actually change.

**Comment by romanz** [comment]
Should be fixed in `p2p` branch.

**Comment by craigraw** [comment]
Confirmed, I can't see any spurious notifications coming through on the `p2p` branch.
