### ISSUE TITLE
SSL on apache (not NGINX) how?

### ISSUE THREAD

**Issue by curious0101** [romanz/electrs#305]
Hi all,

I have Apache installed (not nginx). How can I achieve SSL with electrs? Can I add SSL transport to electrs via apache?

I'm using SSL connection (to electrumx-server) and it was fine. I'd like to achieve that on electrs.

**Comment by Kixunil** [comment]
I guess this is a question for Apache docs/people, not that relevant here. However, if you do find an answer, writing a PR to add it to docs could be useful.
