### ISSUE TITLE
allow incoming connections during initial indexing

### ISSUE THREAD

**Issue by nioncode** [romanz/electrs#309]
At the moment, connections to electrs seem to not work at all while the initial index is happening.

I don't know if this is supported by the Electrum protocol per se, but it would be great to have some kind of error on the client side if we connect to an electrs server that is still indexing. At least there should be some error printed in the logs if there are connections coming in while Electrs is not ready to handle them. At the moment, it is completely unclear to a user whether the connection did not work at all (e.g. wrong host/ip address, Tor errors) or if the connection would have succeeded, but electrs is not ready to serve connections, yet.

**Comment by primeroz** [comment]
I would like this too, I have been struggling to find a good way to monitor the `liveness` of the electrs process during Initial Indexing or even during IBD on the bitcoind side in which case electrs just wait.

Ideally i would love to be able to at least `server.ping` the server and get a successful response if not actually request a `server.ready` and get a meaningful answer.

Thanks!

**Comment by Kixunil** [comment]
I recommend increasing the verbosity and looking at logs until this is implemented.

**Comment by romanz** [comment]
This should be implemented in `next` branch (#308) - Electrum RPCs are being served during indexing.
See https://github.com/romanz/electrs/commit/c565dc915a87ff5c10ed1abb7f48611b4df43b31
