### ISSUE TITLE
protocol version negotiation (server.version) does not follow spec: server should send error on unsupported protocol

### ISSUE THREAD

**Issue by SomberNight** [romanz/electrs#314]
If in the `server.version` message the client requests a too high protocol version that the server does not support, by the spec, the server must send an error and disconnect. In contrast, electrs proceeds and does version negotiation incorrectly: it sends back the highest protocol version it supports.

See https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#server-version

> The server should use the highest protocol version both support:
> 
> `version = min(client.protocol_max, server.protocol_max)`
> 
> If this is below the value:
> 
> `max(client.protocol_min, server.protocol_min)`
> 
> then there is no protocol version in common and the server must close the connection. Otherwise it should send a response appropriate for that protocol version.

electrs:
```
sending message b'{"jsonrpc": "2.0", "method": "server.version", "id": 0, "params": ["electrum/4.0.4", "1.5"]}'
received data b'{"id":0,"jsonrpc":"2.0","result":["electrs 0.4.1","1.4"]}\n'
```

esplora:
```
sending message b'{"jsonrpc": "2.0", "method": "server.version", "id": 0, "params": ["electrum/4.0.4", "1.5"]}'
received data b'{"id":0,"jsonrpc":"2.0","result":["electrs-esplora 0.4.1","1.4"]}\n'
```

ElectrumX:
```
sending message b'{"jsonrpc": "2.0", "method": "server.version", "id": 0, "params": ["electrum/4.0.4", "1.5"]}'
received data b'{"jsonrpc": "2.0", "error": {"code": 1, "message": "unsupported protocol version: 1.5"}, "id": 0}\n'
// connection closed by server
```

**Comment by romanz** [comment]
Many thanks for opening this issue!

**Comment by romanz** [comment]
BTW, there is an experimental [branch](https://github.com/romanz/electrs/commits/next) of `electrs` described at https://github.com/romanz/electrs/issues/308.
I have fixed the issue in this branch using https://github.com/romanz/electrs/commit/b2b08ceaffcf47734c0db87aee8424d4afef0bdb - will backport it to `master` tomorrow.
