### ISSUE TITLE
Support SSL connections for Electrum RPC

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#32]
Currently, electrs crashes if Electrum wallet tries to connect using SSL [1] (instead of TCP [2])

[1] `electrum -1 --server=127.0.0.1:50001:s`
[2] `electrum -1 --server=127.0.0.1:50001:t`

**Comment by romanz** [comment]
First of all, many thanks for running this tool, testing and reporting this issue!

>  it is blazingly fast, synced in 2hr

Really glad to hear that  :)

> Is anybody working on SSL support?

AFAIK, there is nobody currently working on it.
Please let me know if you can help with this issue.

> But server gave error `receiver failed: invalid UTF8...`, see below:

It seems that there are two clients connecting to this server:
```
2018-08-14T17:40:55.460+03:00 - INFO - [192.168.1.166:59896] connected peer
2018-08-14T17:42:34.990+03:00 - INFO - [192.168.1.201:32910] connected peer
```
It seems that the `192.168.1.166` client succeeds, but the `192.168.1.201` fails (most likely since it tries to connect over SSL - see #34).

**Comment by SimonVrouwe** [comment]
> It seems that the 192.168.1.166 client succeeds, but the 192.168.1.201 client fails

Yes you are right, the `192.168.1.201:32910` is an android electrum wallet which uses SSL

The problem with the other  `192.168.1.166:59896` was that it was `Electrum v3.1.3` which stayed _synchronizing_ forever. Update to `v3.2.2` and works fine, I should have read the instructions more carefully.

I'm not experienced enough and probably lack the skills to help you with SSL. But I will continue to test it by using it as a local server.

**Comment by romanz** [comment]
No problem, many thanks for running and testing this software :)

**Comment by romanz** [comment]
I think that the best solution is to use a TLS-terminating proxy, e.g. [hitch](https://github.com/varnish/hitch):
```bash
$ hitch --backend=[127.0.0.1]:50001 --frontend=[127.0.0.1]:50002 pem_file
```
So the Electrum wallet would connect to the proxy SSL frontend:
```bash
$ electrum -1 --server=127.0.0.1:50002:s
```
