### ISSUE TITLE
Add integration tests with latest Electrum wallet

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#337]
For example, start bitcoind in regtest mode, index it using electrs and run a few transactions using Electrum wallet CLI.

Following https://github.com/spesmilo/electrum/issues/6775.

**Comment by romanz** [comment]
https://github.com/shesek/bwt/blob/master/test/tests.sh can be re-used :)

**Comment by Kixunil** [comment]
I could help setting up lnpbp-testkit, but it'll probably not have time for a few days.

**Comment by romanz** [comment]
Implemented in #342
