### ISSUE TITLE
Query server.version via jsonrpc returns error

### ISSUE THREAD

**Issue by dematerializer** [romanz/electrs#339]
After upgrading electrs to 0.8.6, querying the server.version with
`echo '{"jsonrpc": "2.0", "method": "server.version", "id": 0}' | netcat 127.0.0.1 50001`
fails with
`{"error":"invalid params: []","id":0,"jsonrpc":"2.0"}`

**Comment by Kixunil** [comment]
Interesting, I confirm it also happens to me.

**Comment by Kixunil** [comment]
Oh, this seems to be the intended behavior: https://github.com/romanz/electrs/commit/8f2f53303a62321e3ccd1a8dc42b46c63629a03f#diff-5cdcc3261dd77eadb37bcd60c5f85affcc9306454ae7bb8128e6d096ae51a631R112

[The protocol](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#server-version) doesn't explicitly say the parameters are mandatory, but it also doesn't say they aren't, so I suppose they are meant to be mandatory.

I see that docs weren't updated, is it what got you confused?

**Comment by dematerializer** [comment]
Yes indeed, thanks for pointing the right places out to me, I missed that something changed in 0.8.6 because the docs weren't updated. The call `echo '{"jsonrpc": "2.0", "method": "server.version", "params": ["", "1.4"], "id": 0}' | netcat 127.0.0.1 50001` works! I updated the documentation, see merge request #340.
