### ISSUE TITLE
Build:cargo build --locked --release -vv Segmentation fault

### ISSUE THREAD

**Issue by gabridome** [romanz/electrs#346]
**Have you read the documentation?**
Yes. (Please, read usage.md first if you did not.)

**Did you double-check that you installed all dependencies?**
Yes. (Please, double check the dependencies if you didn't.)

**Which command failed?**

```
cargo build --locked --release -vv
Segmentation fault
```

**System**
OS name and version: (If Linux, the distribution name and version)
rustc version: 
```
rustc --version
Segmentation fault
```
cargo version: (run `cargo --version`; not guaranteed to be same as rustc version!)
```
cargo --version
Segmentation fault
```
**Compilation**
Linking: dynamic
Cross compilation: no
Target architecture: (uname -m on Linux if not cross-compiling)
x86_64
**Aditional context**
Any additional information that seems to be relevant.

**Comment by Kixunil** [comment]
That seems to be a problem with your installation of Rust. Which distribution do you use and how exactly did you install Rust?

**Comment by gabridome** [comment]
> That seems to be a problem with your installation of Rust. Which distribution do you use and how exactly did you install Rust?
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.13 (stretch)
Release:	9.13
Codename:	stretch
```

**Comment by gabridome** [comment]
I removed everything I could in terms of debian packages and I also ran:
```
rustup self uninstall
```
then I only ran:
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
and it worked. Now it is building.
I would thank you and close the ticket.

**Comment by Kixunil** [comment]
Installing via Debian packages is safer and I don't see a reason it shouldn't work. It'd be nice of you to file a bug against Debian if it doesn't work.

Either way, glad you solved it!
