### ISSUE TITLE
Electrs won't shutdown cleanly during re-indexing

### ISSUE THREAD

**Issue by 2pac1** [romanz/electrs#348]
Hey guys,

I started re-indexing by adding reindex=1 to config file and rebooting.
Upon reboot, reindexing started, but also btcrpcexplorer and electrs started on boot.
Reindexing started chugging along, but down the road I noticed it started to hang on single block for like 30min or so, something that caused worry.

When I looked at the processes with command: "top" I saw electrs was spiking up the cpu on Pi.
Then I figured out that it would be best to shutdown btcrpcexplorer and electrs with:
sudo systemctl stop btcrpcexplorer
sudo systemctl stop electrs

Btcrpcexplorer closed immediately.
Electrs shutdown command hangged.
After 1min, I went to see the log of it with: sudo journalctl -f -u electrs
There I saw it was in the process of the shutdown.
<img width="652" alt="Screenshot 2020-12-07 at 07 57 55" src="https://user-images.githubusercontent.com/35058480/101319292-0bbfc600-3862-11eb-89d4-b7fc2aca8bd4.png">
Image attached to this post is how the log looked. I waited for full two minutes, after which it issued kill command which forced closed it.
So as it look, electrs might not be able to shut down cleanly during reindex.
Also, what I want to confirm, that no damage can occur to db or anything else during this incident that I experienced.

If someone can try to replicate or verify or see what is going on, it would be great if this could be fixed.
Have a great day!

**Comment by romanz** [comment]
Should be fixed in `next` branch (see #308).

**Comment by romanz** [comment]
@2pac1 This issue should be resolved by #498 - could you please try the latest `v0.9.0-rc2` release?

**Comment by romanz** [comment]
Please reopen if the issue persists.
