### ISSUE TITLE
Debian 10 server: Electrs systemd service not listening to or opening port 50001

### ISSUE THREAD

**Issue by bitopticon** [romanz/electrs#366]
Hello,

I have been using Electrs on Ubuntu 20.04 server without any issues.

Have recently moved to Debian 10 and experienced the following issue.

When I run Electrs as normal user starting it as follows:

./target/release/electrs -vvv --timestamp --db-dir ./db --electrum-rpc-addr="0.0.0.0:50001"

I can connect to it form Electrum wallet on a remote pc on the same network, no problem there.

When I try to start it as a systemd service using this configuration " electrs.service":

Unit]
Description=Electrs
After=bitcoind.service

[Service]
WorkingDirectory=/home/user/electrs
ExecStart=/home/user/electrs/target/release/electrs --db-dir ./db --electrum-rpc-addr="0.0.0.0:50001"
User=user
Group=user
Type=simple
KillMode=process
TimeoutSec=60
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target

The service starts but apparently it is not listening on port 50001:

ss tulpn
Netid State  Recv-Q  Send-Q   Local Address:Port   Peer Address:Port                                     
udp   UNCONN 0       0              0.0.0.0:68          0.0.0.0:*     users:(("dhclient",pid=368,fd=7))  
tcp   LISTEN 0       128          127.0.0.1:8332        0.0.0.0:*     users:(("bitcoind",pid=394,fd=10)) 
tcp   LISTEN 0       128            0.0.0.0:8333        0.0.0.0:*     users:(("bitcoind",pid=394,fd=29)) 
tcp   LISTEN 0       128          127.0.0.1:8334        0.0.0.0:*     users:(("bitcoind",pid=394,fd=30)) 
tcp   LISTEN 0       128            0.0.0.0:22          0.0.0.0:*     users:(("sshd",pid=392,fd=3))      
tcp   LISTEN 0       128            0.0.0.0:3002        0.0.0.0:*     users:(("node",pid=383,fd=18))     
tcp   LISTEN 0       128          127.0.0.1:4224        0.0.0.0:*     users:(("electrs",pid=1022,fd=5))  
tcp   LISTEN 0       128              [::1]:8332           [::]:*     users:(("bitcoind",pid=394,fd=9))  
tcp   LISTEN 0       128               [::]:8333           [::]:*     users:(("bitcoind",pid=394,fd=28))

I suspect this is the reason why I can not connect with my wallet.

Not sure what could be the issue. 

I do not use any electrs configuration files.

Hope somebody can give me a clue what is wrong with the electrs.service config above. I use the same service config Ubuntu server and experience no problem with it. I simply works.

Cheers,
B

**Comment by Kixunil** [comment]
`electrs` takes some time to start and listen, did you wait a bit?

 I assume you tried the command manually being inside `/home/user/electrs`, right?

**Comment by bitopticon** [comment]
If I run it manually:

 ./target/release/electrs -vvv --timestamp --db-dir ./db --electrum-rpc-addr="0.0.0.0:50001"

I can connect and everything seems to work fine.

When I start it as systemd service I get the issue of not be able to connect to it. I use the service example from your README as listed above.

**Comment by Kixunil** [comment]
What does `journalctl -u electrs` (under root) say?

**Comment by bitopticon** [comment]
Have restarted the service again and it seems to start correctly now. Have checked with  journalctl -u electrs and there are not errors:

systemd[1]: Stopping Electrs...
systemd[1]: electrs.service: Succeeded.
systemd[1]: Stopped Electrs.
systemd[1]: Started Electrs.
electrs[1571]: Config { log: StdErrLog { verbosity: Error, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Never }, network_type: Bitcoin, db_path: "./db/mainnet", daemon_
lines 1-39/39 (END)

Not sure what was the problem but it works now. Will test it and report if I see any issues. Thanks for your comments.

**Comment by Kixunil** [comment]
My guess is that it took more time for it to start previously than later. Glad it works.

BTW have you seen my [Debian repository](https://ln-ask.me)? You might find it interesting since you run Debian 10. It can help you setting things up. You'd have to migrate the data from your current setup, but shouldn't be too hard - let me know and I can help you.

**Comment by bitopticon** [comment]
Thanks again. I do prefer to build it myself. Was considering using a repo but only if I fail to build it myself. Will come back to you if I face any issues. By the way, the link you provide is your personal site not the repo. "co-founded Paralelna Polis Bratislava " interesting :-)

**Comment by Kixunil** [comment]
> Was considering using a repo but only if I fail to build it myself.

Understood. Perhaps building the repo could be also interesting way to decrease trust. I'm helping someone to do it right now (some issues were found). :)

> By the way, the link you provide is your personal site not the repo.

Forgot to type subdomain, sorry, fixed.

**Comment by Kixunil** [comment]
Here's an example: https://github.com/romanz/electrs/blob/master/contrib/electrs.service

And here a copy-paste from CADR:

```systemd
[Unit]
Description=An efficient re-implementation of Electrum Server

[Service]
Type=exec
ExecStart=/usr/bin/electrs --conf-dir /etc/electrs-mainnet/conf.d
User=electrs-mainnet
Group=electrs-mainnet
NoNewPrivileges=true
ProtectSystem=full
ProtectHome=true
PrivateTmp=true
PrivateDevices=true
Restart=always


[Install]
WantedBy=multi-user.target
```
