### ISSUE TITLE
Bug: addr.py usage + failed to get confirmed status

### ISSUE THREAD

**Issue by finmetal** [romanz/electrs#369]
Hello, first of all thanks as ur project is really cool.
what i ask is not a real bug, just i don't find info on docs about a couple of things:

1. if i run the command ./contrib/addr.py 144STc7gcb9XCp6t4hvrcUEKg9KemivsCR
i get the following answer: 144STc7gcb9XCp6t4hvrcUEKg9KemivsCR has {'confirmed': 0, 'unconfirmed': 0} satoshis
Question: is there any chance to get also the "already spent" value ?

2. if i run the same command but on different address like ./contrib/addr.py 322yKaALQo5CqB3kBD4BeZgocyY5p78n2m
i get the following error:

Traceback (most recent call last):
  File "./contrib/addr.py", line 31, in <module>
    main()
  File "./contrib/addr.py", line 26, in main
    result = reply['result']
KeyError: 'result'

On server side i see that "failed to get confirmed status caused by XXXX+ transactions found, query may take a long time"
Question: is there any way to get only the confirmed and already spent without counting transactions?

thanks in advance!

**Comment by Kixunil** [comment]
Hi,

1. the script calls `get_balance` which obviously returns current balance. You'd need to change it to `get_history` and re-calculate the balance yourself (shouldn't be hard)
2. `eletrs` has built-in protection against overloading by processing addresses with too many transactions (in practice address reuse is a bad idea so there shouldn't be more than two transactions per address), you can adjust the threshold by setting `txid_limit` option to a larger value - the default is 100 now.

**Comment by finmetal** [comment]
hi @Kixunil and thanks for ur reply.
I would like to ask if there's any faster/clever way to achieve that: knowing just a wallet (that sadly might have been used for 1000 transactions), is there any command/option for reporting just the latest transaction? get_history will list it all, is there any way to force it to show just the latest or the last X without going mad with overloading? I cannot find it but maybe i'm missing something :) 
Thanks!

**Comment by Kixunil** [comment]
I swear I remember writing a reply, now I see it's not here. Strange.

`electrs` follows Electrum protocol very closely. There's no such method specified in Electrum protocol. There's currently one method that's not in the Electrum protocol, so adding methods is NOT strictly rejected but IDK what @romanz thinks about this one. Feels a bit arbitrary to me but I don't want to block it.

If the wallet is fixed and you always want to know the latest, maybe it's better to have stateful tracking of UTXOs in bitcoind?

**Comment by finmetal** [comment]
No worries, I will have a look at what u suggested
Thank you for your time :)
