### ISSUE TITLE
Initial Sync Batching Inflates Bitcoin Core Memory Usage

### ISSUE THREAD

**Issue by TheBlueMatt** [romanz/electrs#373]
Initial sync batches `getblock` requests, which is great, except that as it gets towards later blocks, this causes significant increases in Bitcoin Core memory usage. On an arm board with 4GB of memory (and the current mempool...), once electrs gets into the 500ks in height Bitcoin Core quickly OOM's (despite having a few 100MB of slack before then). As far as I can guess from skimming the code, Bitcoin Core stores the full responses (doubled into hex strings) for each batch entry before returning, and during each block read Bitcoin Core significantly inflates memory due to malloc overhead deserializing (and then reserializing, and then converting the serialized copy to hex) the block itself.

**Comment by TheBlueMatt** [comment]
Oh, this is with `jsonrpc_import`, obviously (from a remote host).

**Comment by TheBlueMatt** [comment]
It looks like the batches are 100, which would be `100*2*~2MB` for around 400MB in Bitcoin Core memory usage handling a batch request.

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
I can suggest using `--index-batch-size=10` to reduce the default batch size.
The long-term solution should probably be to switch to p2p-based sync - which IIUC should be more efficient.

**Comment by TheBlueMatt** [comment]
The issue is really just the default batch size. Reading via RPC isn't as fast as p2p, but that seems like something Core should fix. Is there a reason for the large batch size? It also seems to cause a bottleneck on my (rather cheap) box instead of streaming as electrs seems to anticipate.

**Comment by romanz** [comment]
Sounds good, will change the default to 10 - which is actually [the recommended configuration for low-memory sync](https://github.com/romanz/electrs/blob/master/doc/usage.md#electrs-usage).

**Comment by TheBlueMatt** [comment]
Is it possible to request them one at a time and then batch on the electrs side? It seems like there's little reason to request in batches at all. Even the overhead of 10 block requests can be nontrivial if only because of memory fragmentation in Core.

**Comment by Kixunil** [comment]
@TheBlueMatt that's pretty surprising, I'd expect that batching avoids overhead of context switching etc. If Core can't serve batches efficiently that seems like a bug to me.

**Comment by TheBlueMatt** [comment]
Bitcoin Core doesn't stream batch responses back, and without that there's not a lot you could do to avoid it - 100 blocks is 400MB of hex data (not counting overhead, which Bitcoin Core tends to have a lot of).

The initial sync doesn't seem to be the only instance of this case, either, even with `--index-batch-size` set to 1 electrs seems to occasionally batch fetch many hundred transactions at once, which hangs Bitcoin Core for some time and ends up balooning memory by around 1GB.

**Comment by TheBlueMatt** [comment]
To put an exact number on it, after a cold restart (and filling the mempool again), Bitcoin Core (with the current ~700MB mempool) was using around 1.8GB with ~200 connections. After running electrs, it syncs some blocks (with batch size set to 1), then fetches the mempool using individual `getmempoolentry` calls, then, once its done that, it appears to call a single batch to get all the transactions in the mempool. That RPC call processing drove the memory usage up from 1.8GB to around 2.8GB before dropping back down to 2.2 (malloc likely wasn't able to free all the way back down so you end up with a lot of unused space).

**Comment by Kixunil** [comment]
Thanks for detailed explanation and analysis! I'm slowly working on some mempool handling improvements which will include moving from NIH RPC code to `bitcoincore-rpc`. It may make sense to remove batching right away by not implementing it in the first place - easier code. What do you think @romanz?

I could implement parallelization but I'm not sure if it helps anything - I'd expect same or worse problems will occur, since each thread still does all that copying?

I was also trying to introduce an abstraction to enable easily mocking RPC impl for test purposes. I will try to make the abstraction even more abstract to enable switching to P2P connection when reasonable. The initial version will not use P2P but it'll be easy to add, I hope.

**Comment by TheBlueMatt** [comment]
> I could implement parallelization but I'm not sure if it helps anything - I'd expect same or worse problems will occur, since each thread still does all that copying?

I'm not exactly sure what you're suggesting here? Parallelizing the RPC calls should be a nice win - the biggest issue here (I think) is the buffer that is maintained between individual RPC calls in a batch and the growth of that buffer. If the calls are sent individually, no such buffering occurs. Bitcoin Core's RPC handling uses (by default) 4 threads (though most of them end up using cs_main, so you won't usually end up being able to use 4 cores) so having 4 (or more, they're queued) requests in flight at once should provide noticeable benefit.

**Comment by TheBlueMatt** [comment]
> enable switching to P2P connection when reasonable

If you're looking to avoid the overhead of hex-encoding everything and JSON-RPC, you might instead try Bitcoin Core's REST interface - it still has the HTTP overhead, but unlike P2P you're not contending for access to the single message handler thread (its served out of the same four RPC handling threads) and you don't have to double-SHA256 everything on the socket.

**Comment by Kixunil** [comment]
> the biggest issue here (I think) is the buffer that is maintained between individual RPC calls

Ah, missed this detail. I will probably put it off to later phase, we'll see.

> you might instead try Bitcoin Core's REST interface

Wow, totally missed it's a thing. Will consider!

**Comment by TheBlueMatt** [comment]
> I will probably put it off to later phase, we'll see.

Just to make sure we're on the same page - the buffer in question there is on the Bitcoin Core side. Just dropping the batches and doing individual requests will solve it entirely at least on the Bitcoin Core end, even if electrs keeps the batches. At least I have the spare memory on the electrs end to handle it, though I presume its best to not require that :).

**Comment by dagurval** [comment]
I switched to fetching one block over RPC at a time and having a block buffer on electrs side: https://github.com/BitcoinUnlimited/ElectrsCash/pull/121

**Comment by Kixunil** [comment]
@TheBlueMatt sure, I meant putting off multiple threads. Dropping it to one will be done first.

@dagurval thanks for heads up!

**Comment by romanz** [comment]
Merged #374
