### ISSUE TITLE
Does "server.peers.subscribe" work now or planned to be implemented?

### ISSUE THREAD

**Issue by chill117** [romanz/electrs#375]
I maintain the [PayNoWay](https://github.com/samotari/pay-no-way) app which communicates with ElectrumX servers via TCP. It uses the "servers.peers.subscribe" RPC command to get a list of known peers to connect to, so that the client app can always find a server to connect to.

I am currently looking at electrs as a potential replacement for ElectrumX, but I notice that this RPC command seems to always return an empty array:
```rust
    fn server_peers_subscribe(&self) -> Result<Value> {
        Ok(json!([]))
    }
```
From https://github.com/romanz/electrs/blob/master/src/rpc.rs#L145-L147

I am not familiar with Rust, so maybe I am misunderstanding something.

So my questions:
* Am I understanding correctly that this feature is not currently implemented in electrs?
  * If yes, is support for this feature planned for the future?
  * If no, is it possible to find a list of publicly available electrs servers?
* Does this project discourage exposing electrs servers publicly?

**Comment by Kixunil** [comment]
Hi, thanks for good question!

> Am I understanding correctly that this feature is not currently implemented in electrs? 

Yes, you understand it correctly.

> Does this project discourage exposing electrs servers publicly?

Yes, it does.

> If yes, is support for this feature planned for the future?

I'm not sure what the implementation should do. It could connect to IRC to get the list of other servers without disclosing its own but since `electrs` is intended for personal use, it makes very little sense to me.

I also find it odd that there's this method in the protocol at all. Connecting to IRC from the client directly seems more secure.

Could you explain why you need multiple Electrum servers in PayNoWay? Is it just to improve reliability or do you broadcast double spend transaction to different Electrum servers? Perhaps your goal could be achieved differently?

> If no, is it possible to find a list of publicly available electrs servers?

I don't think so. Nobody I know runs `electrs` publicly and any list would be list of Electrum servers without filtering the implementation as it is not important for usual uses of Electrum. Also your question feels like XY problem so maybe if you explain the issue in more detail we can help you better.

**Comment by chill117** [comment]
> Nobody I know runs electrs publicly and any list would be list of Electrum servers without filtering the implementation as it is not important for usual uses of Electrum. Also your question feels like XY problem so maybe if you explain the issue in more detail we can help you better.

PayNoWay needs to do all of the following:
* Broadcast raw RBF transactions as well as RBF replacement transactions (the double-spends)
* Fetch the fee rate estimate
* Fetch the minimum relay fee rate - so that the Electrum server will accept and then relay our transactions
* Fetch single transaction
* Fetch UTXO for an address (or script hash)

And yes, the PayNoWay app attempts to maintain socket connections with multiple servers at once to improve reliability.

**Comment by Kixunil** [comment]
Wouldn't it be better to broadcast transactions directly to bitcoind nodes instead of electrum servers? That way you could get more nodes and wouldn't rely on Electrum.

If not, how hard would it be to connect to the Electrum IRC server from the app to get the addresses? AFAIK IRC is very simple.

**Comment by chill117** [comment]
> Wouldn't it be better to broadcast transactions directly to bitcoind nodes instead of electrum servers?

For broadcasting transactions, yes, this is the best method. And it could allow for non-RBF double-spends if the app uses IP-based geo-location of nodes plus some other trickery.

But the app needs other capabilities that aren't possible when communicating only with bitcoin nodes - e.g querying individual transactions by ID/hash, fetching UTXO by scripthash, etc. And the app would require hours to sync and eat a lot of bandwidth/power. This app is for mobile devices, so that would not be a nice experience.

**Comment by Kixunil** [comment]
I don't see any issue with the app connecting to a single `electrs` instance for the remaining operations, do you?

Unless the server is supposed to be public in which case this version of `electrs` is not that great. There's a fork by Blockstream which may be a good choice but it's much more resource-heavy.

**Comment by kyuupichan** [comment]
> I also find it odd that there's this method in the protocol at all. Connecting to IRC from the client directly seems more secure.

Haha, what IRC?  The whole point of this change was to get off IRC.

**Comment by Kixunil** [comment]
Why? This looks dangerous. The server could lie about other servers in order to continue spying on the user by pretending other servers don't exist or only mentioning servers controlled by the same party.

**Comment by kyuupichan** [comment]
You just need one good server, and several are hard-coded into the client.

**Comment by romanz** [comment]
For now, it is preferable to use electrs as a personal Electrum server (i.e. not shared publicly):
https://github.com/romanz/electrs/issues/187
