### ISSUE TITLE
Build fails when compiling serde

### ISSUE THREAD

**Issue by oparex** [romanz/electrs#376]
I followed usage.md for install instructions. I installed required libreries (not for cross compile tho) and finally ran `cargo build --locked --release` as per instructions.

The build fails with error

```
$ cargo build --locked --release
   Compiling serde v1.0.116
error: variable 'access' is still repeating at this depth
   --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/impls.rs:727:47
    |
727 |                     fn visit_seq<A>(self, mut $access: A) -> Result<Self::Value, A::Error>
    |                                               ^^^^^^^

error: variable 'expecting_message' is still repeating at this depth
    --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/impls.rs:1373:13
     |
1373 |             $expecting_message,
     |             ^^^^^^^^^^^^^^^^^^

error: variable 'expecting_message' is still repeating at this depth
    --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/impls.rs:1313:45
     |
1313 |                         formatter.write_str($expecting_message)
     |                                             ^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared type or module `OsStringKind`
    --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/impls.rs:1651:14
     |
1651 |             (OsStringKind::Unix, v) => v.newtype_variant().map(OsString::from_vec),
     |              ^^^^^^^^^^^^ use of undeclared type or module `OsStringKind`

error[E0433]: failed to resolve: use of undeclared type or module `OsStringKind`
    --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/impls.rs:1652:14
     |
1652 |             (OsStringKind::Windows, _) => Err(Error::custom(
     |              ^^^^^^^^^^^^ use of undeclared type or module `OsStringKind`

error[E0425]: cannot find value `OSSTR_VARIANTS` in this scope
    --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.116/src/de/impls.rs:1682:51
     |
1682 |         deserializer.deserialize_enum("OsString", OSSTR_VARIANTS, OsStringVisitor)
     |                                                   ^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 6 previous errors

Some errors have detailed explanations: E0425, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `serde`.
```

**System**
Ubuntu 20.04 LTS
rustc version: rustc 1.47.0
cargo version: cargo 1.46.0

**Compilation**
Linking: both end up producing the same error
Cross compilation: no
Target architecture: x86_64

**Comment by Kixunil** [comment]
Thanks for high-quality report! The error looks very strange, so I don't have enough time to look into it properly right now. Will look at it tomorrow.

**Comment by Kixunil** [comment]
I looked into it and I can't understand how such an error could happen. The only somewhat sensible idea that occurs to me is that your filesystem got corrupted. Removing `~/.cargo/registry` may help.

**Comment by oparex** [comment]
ok now the build fails with this error. I first deleted `~/.cargo/registry` then ran `$ cargo build --locked --release`
```
   Compiling serde v1.0.116
   Compiling librocksdb-sys v5.18.5
   Compiling toml v0.5.6
   Compiling bitcoin_hashes v0.9.4
error: meta-variable `g0` repeats 0 times, but `g1` repeats 16 times
   --> /home/peter/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin_hashes-0.9.4/src/ripemd160.rs:196:10
    |
196 |           $( round!(bb[$g0], bb[$g1], bb[$g2], bb[$g3], bb[$g4],
    |  __________^
197 | |                   $data[$data_index2], $bits2, 0x5a827999,
198 | |                   (bb[$g1] & bb[$g2]) | (!bb[$g1] & bb[$g3])); )*
    | |________________________________________________________________^

   Compiling secp256k1 v0.20.0
   Compiling serde_json v1.0.57
   Compiling bincode v1.3.1
   Compiling cargo_toml v0.8.1
   Compiling configure_me v0.4.0
   Compiling configure_me_codegen v0.4.0
error: aborting due to previous error

error: could not compile `bitcoin_hashes`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I am actually running this on Ubuntu server 20.04 LTS. I am running this with 4GB of RAM, could this be an issue? I have another 4GB of swap allocated tho... I managed to sync my electrumx node some time ago with this hardware...

**Comment by Kixunil** [comment]
Low RAM can cause problems but they behave differently. I'm afraid your storage is failing because you seem to get compile errors based on code that doesn't exist in any official source.

**Comment by oparex** [comment]
What is low in electrs terms? Hmmm I am using the default volume groups that Ubuntu sets at install. I extended the original 200GB to the whole disk of 1TB, maybe that procedure could have done something wrong. Will try to compile on aws. Do you have any particular instance you know is ok hardware wise there that is "guaranteed" to produce a build?

**Comment by Kixunil** [comment]
Regarding RAM, I'm not sure about the exact value (few GB I guess, definitely less than 4) but the result of not having enough is just compilation dying with SIGKILL, not awkward errors like these.

> I extended the original 200GB to the whole disk of 1TB, maybe that procedure could have done something wrong.

Never happened to me but maybe it could.

> Do you have any particular instance you know is ok hardware wise there that is "guaranteed" to produce a build?

Not sure, I compile it on Debian 10 running in Qubes on Purism 13 but that's too specific, I guess. :)
Anyway, if you're going to use a VM pick something with Debian 10 as that should remove some uncertainty.

**Comment by oparex** [comment]
I have tried to build electrs on aws with similar hardware (2 cores, 4GB ram) on Ubuntu server 20 and it worked.
