### ISSUE TITLE
Heavy Electrum wallets wont synchronize.

### ISSUE THREAD

**Issue by ascisco** [romanz/electrs#382]
Is there a way to configure electrs to handle heavy wallets (wallets with a lot of transactions in them)? After my wallet has a 100 or more transactions in it, it starts get stuck and hangs on Synchronizing... 0/1 in my electrum wallet. 

Im running the latest raspiblitz and electrum mobile wallet.

**Comment by Kixunil** [comment]
Sadly this is a known issue that was repeated here multiple times, I'm trying to fix it but it goes slowly since I don't have that lot of time. But based on lot of feedback like this, I will try to prioritize it.

**Comment by craigraw** [comment]
May I suggest that in the meantime there is a new minor release which sets the `wait_duration_secs` configuration setting from 5 to 10 seconds? This quick fix would relieve this issue for many people while the actual fix is coming.

**Comment by Kixunil** [comment]
@craigraw didn't notice bumping it helps, thanks for info! I opened #384.

There are other valuable fixes in the master, so I agree minor release would be useful.

**Comment by romanz** [comment]
0.8.9 is [released](https://crates.io/crates/electrs).

**Comment by romanz** [comment]
Please see https://github.com/romanz/electrs/issues/308#issuecomment-806061229
