### ISSUE TITLE
Bug: failed to read status, stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by d-hoffi** [romanz/electrs#383]
**Describe the bug**
Electrs starts as expected but after some minutes it stops/gets interrupted with the following issue: 
`2021-03-13T21:38:19.113+01:00 - ERROR - server failed: Error: failed to read status
Caused by: stream did not contain valid UTF-8` (see picture)

![Unbenannt](https://user-images.githubusercontent.com/62653718/111043935-d10f9000-8445-11eb-83f0-6adb80ecde9f.JPG)

my system os:
`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`

I am not quite sure, if you need more information. Just let me know if that is the case. Thanks to all of you.

**Comment by Kixunil** [comment]
This looks like maybe you pointed your `electrs` to something that is not Bitcoind RPC interface? Maybe you used 8333 instead of 8332?

Please post your configuration file (`electrs.toml`) with password stripped.

**Comment by d-hoffi** [comment]
here my Electrs configuration file (`/mnt/ext/electrs/electrs.conf`):

#RaspiBolt: electrs configuration
#/mnt/ext/electrs/electrs.conf

#RPC user / password
cookie = "MYNODE:MYPASSWWORD"

#Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/mnt/ext/bitcoin"
daemon_rpc_addr = "127.0.0.1:28332"

#Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/mnt/ext/electrs/db"
txid_limit = 1000

#Logging
verbose = 4
timestamp = true
rust_backtrace = true


if needed, here is my `bitcoin.conf` file:

#RaspiBolt: bitcoind configuration
#/mnt/ext/bitcoin/bitcoin.conf

#Bitcoin daemon
server=1
txindex=1

#Network
listen=1
listenonion=1
proxy=127.0.0.1:9050
bind=127.0.0.1

#Connections
rpcuser=MYNODE
rpcpassword=MYPASSWORD
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

#Raspberry Pi optimizations
maxconnections=40
maxuploadtarget=5000

#Initial block download optimizations
#dbcache=2000
#blocksonly=1

**Comment by Kixunil** [comment]
Yep, I guessed correctly. You entered ZMQ port (28332) instead of RPC port (8332). It should work when you fix it.

**Comment by d-hoffi** [comment]
yeah great, that was the issue. thanks a lot :)
