### ISSUE TITLE
Feature: Make prometheus optional

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#385]
**Is your feature request related to a problem? Please describe.**
Some people have trouble building `electrs` (see e.g. #252) because of `sysconf` dependency, some may not need it and thus avoiding compilation time and potential attack surface may be preferred.

**Describe the solution you'd like**
Make prometheus optional using a Cargo feature (default on, I guess) and document it. Packagers are still encouraged to include it. Put all related code into a single module to cut it out cleanly and create an empty module with empty structs and no-op methods.

**Describe alternatives you've considered**
* Try to fix lib bugs - nice but it's still more moving parts than necessary for many people.
* Rewrite dependencies somehow to bypass C/OS APIs - difficult, I guess?
* Do not support niche platforms

**Comment by RCasatta** [comment]
I am using electrs in regtest env, and I would like to avoid opening an unused `monitoring_addr` port so this would solve.

**Comment by romanz** [comment]
Please try https://github.com/romanz/electrs/commit/b0deaecdc48f652d5ad8b8d768e278e5634362a7 in the `p2p` branch.
Note that it requires reindexing the chain (due to an incompatible index format) - see https://github.com/romanz/electrs/issues/308#issuecomment-806061229.

**Comment by ulzeraj** [comment]
> Please try [b0deaec](https://github.com/romanz/electrs/commit/b0deaecdc48f652d5ad8b8d768e278e5634362a7) in the `p2p` branch.
> Note that it requires reindexing the chain (due to an incompatible index format) - see [#308 (comment)](https://github.com/romanz/electrs/issues/308#issuecomment-806061229).

Hi. Just compiled on FreeBSD 13.0 AMD64 using the OS provided clang and LLVM.

```
FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

cargo 1.52.0
rustc 1.52.1
```

**Comment by romanz** [comment]
It is possible that you are using a deprecated config parameter... sorry about that :(
You can run `electrs --help` to see the supported parameters.

**Comment by ulzeraj** [comment]
Apparently cookie_file and daemon_p2p seems to be a new thing. 

I've copied the binary to electrs2 to not conflict with the working one.

```
$ electrs2 --help
Usage: electrs2 [ARGUMENTS...]

Arguments:
        --conf                  Load configuration from this file.
        --conf-dir              Load configuration from files in this directory.
        --db-dir                Directory to store index database (default: ./db
                                /)
        --daemon-dir            Data directory of Bitcoind (default: ~/.bitcoin/
                                )
        --blocks-dir            Analogous to bitcoind's -blocksdir option, this 
                                specifies the directory containing the raw 
                                blocks files (blk*.dat)
        --cookie-file           JSONRPC authentication cookie file (default: ~/.
                                bitcoin/.cookie)
        --network               Select Bitcoin network type ('bitcoin', 'testnet
                                ', 'regtest' or 'signet')
        --electrum-rpc-addr     Electrum server JSONRPC 'addr:port' to listen on
                                (default: '127.0.0.1:50001' for mainnet, '
                                127.0.0.1:60001' for testnet, '127.0.0.1:60401' 
                                for regtest and '127.0.0.1:60601' for signet)
        --daemon-rpc-addr       Bitcoin daemon JSONRPC 'addr:port' to connect (
                                default: 127.0.0.1:8332 for mainnet, 127.0.0.1:
                                18332 for testnet, 127.0.0.1:18443 for regtest 
                                and 127.0.0.1:18554 for signet)
        --daemon-p2p-addr       Bitcoin daemon p2p 'addr:port' to connect (
                                default: 127.0.0.1:8333 for mainnet, 127.0.0.1:
                                18333 for testnet, 127.0.0.1:18444 for regtest 
                                and 127.0.0.1:38333 for signet)
        --monitoring-addr       Prometheus monitoring 'addr:port' to listen on (
                                default: 127.0.0.1:4224 for mainnet, 127.0.0.1:
                                14224 for testnet, 127.0.0.1:24224 for regtest 
                                and 127.0.0.1:34224 for regtest)
        --wait-duration-secs    Duration to wait between bitcoind polling
        --index-batch-size      Number of blocks to get in one JSONRPC request 
                                from bitcoind
        --txid-limit            Number of transactions to lookup before 
                                returning an error, to prevent 'too popular' 
                                addresses from causing the RPC server to get 
                                stuck (0 - disable the limit)
        --server-banner         The banner to be shown in the Electrum console
        -v, --verbose           Increase logging verbosity
        --timestamp             Prepend log lines with a timestamp
        --jsonrpc-import        Use JSONRPC instead of directly importing blk*.
                                dat files. Useful for remote full node or low 
                                memory system
        --ignore-mempool        Don't sync mempool - queries will show only 
                                confirmed transactions.
```

So I've adjusted accordingly:

```
$ cat /usr/local/etc/electrs2.toml
jsonrpc_import = true
cookie_file = "/var/db/electrs2/.cookie"
daemon_rpc_addr = "10.10.10.37:8332"
daemon_p2p_addr = "10.10.10.37:8333"
db_dir = "/var/db/electrs2"
network = "bitcoin"
electrum_rpc_addr = "127.0.0.1:50001"
verbose = 3
timestamp = true
```

```
$ /usr/local/bin/electrs2 --conf /usr/local/etc/electrs2.toml
Config { network: Bitcoin, db_path: "/var/db/electrs2/bitcoin", daemon_dir: "/var/db/electrs/.bitcoin", daemon_cookie_file: "/var/db/electrs/.bitcoin/.cookie", daemon_rpc_addr: 10.10.10.37:8332, daemon_p2p_addr: 10.10.10.37:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, index_batch_size: 10, ignore_mempool: false, server_banner: "Welcome to electrs 0.9.0 (Electrum Rust Server)!", args: [] }
Error: daemon not available

Caused by:
    JSON-RPC error: JSON decode error: EOF while parsing a value at line 1 column 0
```

On the bitcoind host I get an incorrect password attempt message:

```
ThreadRPCServer incorrect password attempt from 10.10.10.35:64852
```

The Config output still references a ``daemon_cookie_file: "/var/db/electrs/.bitcoin/.cookie``.

Also, is RPC authentication nos supported anymore? The cookie file changes every time the bitcoin core server is restarted and will make it impossible to run the electrs daemon from a separate host.

**Comment by romanz** [comment]
Should be resolved by https://github.com/romanz/electrs/commit/df513cfb18297d3d76097bb62dba93676bbf9a94.

**Comment by ulzeraj** [comment]
Nice. Its working and indexing. Although I had to move the process to the same jail bitcoin core is running.

**Comment by RCasatta** [comment]
ack df513cfb18297d3d76097bb62dba93676bbf9a94 tested in https://github.com/RCasatta/electrsd/pull/5

**Comment by romanz** [comment]
Also, don't compile `hyper` if `metrics` is not needed.

**Comment by RCasatta** [comment]
Is there any plan for the release of the p2p branch?

**Comment by Kixunil** [comment]
@RCasatta from my understanding there's still quite a lot of work and testing to do. I would personally really really want to see at least basic migration code. I'm willing to write it to not block the release but if it can wait I would appreciate it.

**Comment by romanz** [comment]
One remaining feature I'd like to port from `master` is https://github.com/romanz/electrs/pull/398 - returning correct JSONRPC error codes (as defined in https://www.jsonrpc.org/specification#error_object).
