### ISSUE TITLE
4.0.8+ electrum version cannot connect

### ISSUE THREAD

**Issue by pwpwpwpw** [romanz/electrs#386]
Hi, newer versions of electrum cannot connect.
electrum-4.0.4.exe -1 -s 192.168.0.101:50001:t works fine but the same thing with version 4.08 4.09 the program starts but it doesn't want to connect, it the red connection icon just keeps blinking, like it connected and then immediately disconnected.

On the electrs linux machine, this is what I see while monitoring the service with systemctl status

ERROR - 192.168.0.100 receiver failed: channel closed
connection handling failed: Error failed to send {"id":15, "jsonrpc":"2.0","result":null}
Caused by broken pipe (os error 32)

I will continue using 4.0.4 for now, just curious is this normal?

**Comment by Kixunil** [comment]
Which version of electrs are you using?

**Comment by pwpwpwpw** [comment]
I'm not sure, it must have been 0.8.6 or so but I updated it to the latest and now the issue is fixed, the latest electrum connects without a problem.
