### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by tongkirati** [romanz/electrs#389]
**Describe the bug**

**To Reproduce**
1. Configure and start electrs
2. Connect with electrum client XYZ
3. Wait

**Expected behavior**

**Configuration**

<details>
<summary>electrs.toml</summary>

```
type error message here
```

</details>

Environment variables: `ELECTRS_X=Y;...`
Arguments: `--foo`

**System running electrs**
 - Deployment method: manual/native OS package/Docker
 - OS name and version (name of distribution and version in case of Linux)

**Electrum client**
Client name (if not upstream desktop Electrum) and version:

**Additional context**

**Comment by Kixunil** [comment]
Reported as spam.
