### ISSUE TITLE
thread 'fetcher' panicked at 'failed sending blocks to be indexed: "SendError(..)"', libcore/result.rs:945:5

### ISSUE THREAD

**Issue by duckartes** [romanz/electrs#39]
> 2018-07-22T07:46:48.808-04:00 - INFO - best=0000000000000000002951d3e7c55d648db084a352ece44c74e99a675d4cabd0 height=533089 @ 2018-07-22T11:45:58Z (84197 left to index)
> thread 'fetcher' panicked at 'failed sending blocks to be indexed: "SendError(..)"', libcore/result.rs:945:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.
> 2018-07-22T08:07:59.964-04:00 - TRACE - closing DB
> 2018-07-22T08:08:00.694-04:00 - ERROR - server failed: Error: RPC failed: [{"id":84251,"method":"getblock","params":["0000000000000000020eb999832487d18f24cd859ea7db742a92b0567ab91ca1",false]},{"id":84251,"method":"getblock","params":["000000000000000000d6c24c1ace1e7b3da8bc06c29178a597a78e5515ea45ae",false]},{"id":84251,"method":"getblock","params":["000000000000000001eb58dc48854852661ae8e1b771e47c77f9babbd89bd225",false]},{"id":84251,"method":"getblock","params":["00000000000000000115debee56fc1537d19bc9d84b93d166414bf1317884f99",false]},{"id":84251,"method":"getblock","params":["000000000000000001ee5208fc1e2fddf65738bfc8a1f2088d3fa9108a08ff8f",false]},{"id":84251,"method":"getblock","params":["0000000000000000021086e98039c290247c509b80c0c1b3d0dd0f923e506e52",false]},{"id":84251,"method":"getblock","params":["000000000000000000eec3e5eaea812f975dfefed2ba1dd05676b58fe2036676",false]},{"id":84251,"method":"getblock","params":["000000000000000001533c7ffa5e7ad648d60080d8a36da6e83ada7602f85a07",false]},{"id":84251,"method":"getblock","params":["000000000000000001b54ed8a86715f7518b7494824a8d37fcd75cd8016b0355",false]},{"id":84251,"method":"getblock","params":["000000000000000000c1362e6be20bd1d1e2b2c703d4a14f6501f7bbdc74c29c",false]},{"id":84251,"method":"getblock","params":["000000000000000000bb786a53ee0b1c2c6cbed1154e6687ffed0b9098eda346",false]},{"id":84251,"method":"getblock","params":["00000000000000000191dc941e341f7dbc70c3a9b59f6e88aa978a7f63f0581c",false]},{"id":84251,"method":"getblock","params":["000000000000000002001441ed0a1395d68b6c8b74b692e1cba9c21e2d886f49",false]},{"id":84251,"method":"getblock","params":["0000000000000000010c0c045b527ba2e8248a9b1475c69d388599575e171aa7",false]},{"id":84251,"method":"getblock","params":["000000000000000002019ea4d197840ddc30b39777803274b8c4aa4031bcefab",false]},{"id":84251,"method":"getblock","params":["0000000000000000009ea93af4170cd712726ad8f4ddf715c4adeaf3374e3b58",false]},{"id":84251,"method":"getblock","params":["000000000000000000da6ecaeb65eee83244715c3c3e90d1ac6afe770e3a6554",false]},{"id":84251,"method":"getblock","params":["000000000000000001005d250ef9f43056ca34d17f10e556aaac7ac9324b78f5",false]},{"id":84251,"method":"getblock","params":["000000000000000001b29c4386d1b36c25c3408ad49cd85d2dd0163a0f800628",false]},{"id":84251,"method":"getblock","params":["000000000000000002164d6005ef38ea869b995609b83648262b59978b35dae2",false]},{"id":84251,"method":"getblock","params":["0000000000000000016e42152acd207519de23ac4f66ae3d2b2442f8e885573a",false]},{"id":84251,"method":"getblock","params":["0000000000000000020fd12cce1144736f8f49fa85b8cf96ecdd570195f4b8bd",false]},{"id":84251,"method":"getblock","params":["000000000000000001e18c1afd2358da6502724543eda891485707af6b947546",false]},{"id":84251,"method":"getblock","params":["0000000000000000003b7c45567de4c1c3eb361b8466d162f1388b0bb82401b9",false]},{"id":84251,"method":"getblock","params":["0000000000000000005994be75df44df4bdf0e5299322edf76e30f5bbdec05d4",false]},{"id":84251,"method":"getblock","params":["0000000000000000020e3f83a772e71b414c3d76f6664022caec0f17df6247d4",false]},{"id":84251,"method":"getblock","params":["0000000000000000020dceec1a49b119909dcc8651be5db7edf622267878d9a2",false]},{"id":84251,"method":"getblock","params":["0000000000000000014018334494759c9b5e6c0553ded85a469c54cc6889b8e7",false]},{"id":84251,"method":"getblock","params":["000000000000000000de068e372ff71fd9af03ee166c2b8daeb22af78c400afe",false]},{"id":84251,"method":"getblock","params":["00000000000000000153f24946d33ac8d5a1ea912f04148a28a483c4dc83e662",false]},{"id":84251,"method":"getblock","params":["0000000000000000015ce530dc65869e2f1f3a2f4548a1673f564a80ff8299b6",false]},{"id":84251,"method":"getblock","params":["00000000000000000257351c48730e0b4db45cc058960b233bccf0cfb9bbf339",false]},{"id":84251,"method":"getblock","params":["000000000000000000572995c8938b7df198bba4fedb0b8504e442a39d3601e3",false]},{"id":84251,"method":"getblock","params":["00000000000000000186d7c821f27c09464c7997a19036d31d4b022c97ab12ca",false]},{"id":84251,"method":"getblock","params":["0000000000000000017cf6276a890909982f507b7e8e646fa51223438762e210",false]},{"id":84251,"method":"getblock","params":["000000000000000000ae6c8d829f3ecc0e7dd4aceba568a7eb596f68aafebd69",false]},{"id":84251,"method":"getblock","params":["0000000000000000004c87dac4cd541d203e2f221d3c676f11c005ebd416f436",false]},{"id":84251,"method":"getblock","params":["000000000000000000c20f8a3ea20ccc71907994787ea1d5a6e6cd4f8aa65dfc",false]},{"id":84251,"method":"getblock","params":["000000000000000000bd8c9d1cec11cc80792d8a7e25993d711fe29099ec1e70",false]},{"id":84251,"method":"getblock","params":["00000000000000000182d0184efb1e329378a6eecfb93f8a3bebc9df7fc1b846",false]},{"id":84251,"method":"getblock","params":["000000000000000001dc8901d3fd152fbf7aa749588aca78183e47f98bfa0361",false]},{"id":84251,"method":"getblock","params":["000000000000000001ab457d3345447818373518407682ee993cb6a7c468b800",false]},{"id":84251,"method":"getblock","params":["00000000000000000134e0dabb631ce577b1d2bd3fd07529d1d8e92d6edefcc9",false]},{"id":84251,"method":"getblock","params":["000000000000000002721b0c026b24af0290ad12eb90dd055e12e4285e60b61f",false]},{"id":84251,"method":"getblock","params":["0000000000000000019ca83342fa0b318a30e5616b663dd03fb1d38722853767",false]},{"id":84251,"method":"getblock","params":["000000000000000000214f6f37ad06bdfeae69f846511fd84a5fe8e4136d3de3",false]},{"id":84251,"method":"getblock","params":["000000000000000001131227cba56dec47b6a69a043b87ab3acc6535e703fe7b",false]},{"id":84251,"method":"getblock","params":["000000000000000002079d661dc1ec13141d5004985974cd1400fcd2c8a81c54",false]},{"id":84251,"method":"getblock","params":["0000000000000000023c9ed52c4ed27e96cd1e5f53eca2d2c693e35091f87c18",false]},{"id":84251,"method":"getblock","params":["000000000000000002756f93f3e0246a36e0716415c2e38efb751967759ab060",false]},{"id":84251,"method":"getblock","params":["0000000000000000008220d0338f03a512dbab6c3801510ffd1c4e324398af01",false]},{"id":84251,"method":"getblock","params":["0000000000000000016866b1460672d7e862562cc37cfe42eca49822bdec54a4",false]},{"id":84251,"method":"getblock","params":["0000000000000000015d95e11dfce3c2c75261875025e804a98b35419698458e",false]},{"id":84251,"method":"getblock","params":["000000000000000000ecb7a9069f15e892fd8200fc7ed32015b684e1e959f880",false]},{"id":84251,"method":"getblock","params":["000000000000000001056cdcba2cc0eea79abdc694223085c615e0b7672d85c8",false]},{"id":84251,"method":"getblock","params":["000000000000000001e3db3cb5e7b66824e02614b935fcf91fde79e1a9a68039",false]},{"id":84251,"method":"getblock","params":["00000000000000000209cefa216ed76e3d2ffa15483edbc7785c668f10f518e1",false]},{"id":84251,"method":"getblock","params":["000000000000000000a3eda906f3482bca4fdc44c1455172c0f56b0b6489aa81",false]},{"id":84251,"method":"getblock","params":["0000000000000000005511b8312fa987764c05172eb7740aa8e48befc7caf11a",false]},{"id":84251,"method":"getblock","params":["000000000000000000a346ae6a7309e90eb9f079fe0b080ff58414d0d7a3411a",false]},{"id":84251,"method":"getblock","params":["000000000000000001b6a3249c66ce50610d8f14061372725044bb3d162b475d",false]},{"id":84251,"method":"getblock","params":["000000000000000000c162dcd38a0013badf14b5bfaab892faa86294392cb377",false]},{"id":84251,"method":"getblock","params":["000000000000000001bcee4fb91d457177b0c20581e0b63de90dd1b044f0eec2",false]},{"id":84251,"method":"getblock","params":["0000000000000000005e223fa18463ef66e0b8b1f6f7d7c141abecb9c06f6d9a",false]},{"id":84251,"method":"getblock","params":["0000000000000000014fa721a30cec4e7ce72a341f676fc9b22c8e41d6cdc0f9",false]},{"id":84251,"method":"getblock","params":["0000000000000000016d230dc2ffd8eb98ad14c5a5ad04245fa0cb42977d12ca",false]},{"id":84251,"method":"getblock","params":["000000000000000000b0e4d4babcb8f6799c0a7d33dea71f095e44eb4d5a6349",false]},{"id":84251,"method":"getblock","params":["00000000000000000207ad54f117034bb49d8c5128c63fe4289d29a2fb14ced2",false]},{"id":84251,"method":"getblock","params":["0000000000000000017666a32a27624bda261c6b3cb3b60c7924a75c4d6590ef",false]},{"id":84251,"method":"getblock","params":["0000000000000000023a7dfb642c52d65ec1c1bc61511d2771bf9aaf794b5a71",false]},{"id":84251,"method":"getblock","params":["00000000000000000026b72386cbbe789f530ed47f841c52ebafb8d364029475",false]},{"id":84251,"method":"getblock","params":["000000000000000002480d7f8865e433cf54b2439f97aa7a338ca792f55b784f",false]},{"id":84251,"method":"getblock","params":["000000000000000000351fac2df364687b51899896740583f50a70765e5926cd",false]},{"id":84251,"method":"getblock","params":["00000000000000000095237aea75f7c762c9b69ef23b0d0acfb3fc27699b760d",false]},{"id":84251,"method":"getblock","params":["00000000000000000095d70067c6bdcda55024fcf43b2b629ecc3214fbe8a681",false]},{"id":84251,"method":"getblock","params":["000000000000000000620897447da831fe6046bfc062f1f5ce9100c1f7ee851d",false]},{"id":84251,"method":"getblock","params":["0000000000000000027e2ed23fcca3fcbd895567c616a4e9190203be09a73a9d",false]},{"id":84251,"method":"getblock","params":["000000000000000001faa369d755bcbacb971f2807cec957e495ebce8e8b9bb5",false]},{"id":84251,"method":"getblock","params":["0000000000000000014f1e436f5daf530c6e6810713bf1270c64d0237ed2062d",false]},{"id":84251,"method":"getblock","params":["00000000000000000110e09d7f6fb5b4bb06cbed462f32b282f900639c8eaf33",false]},{"id":84251,"method":"getblock","params":["0000000000000000010e5ace3626873b43458d9055d184dca30f081ebd702424",false]},{"id":84251,"method":"getblock","params":["000000000000000002313a8e4eec1d7b597e41d22d5347bcbc3429b7155bd4f5",false]},{"id":84251,"method":"getblock","params":["000000000000000001b25b94dd4d628b9de046e26b53c9786be5b9a52683662f",false]},{"id":84251,"method":"getblock","params":["000000000000000001841b357586393707a0326a61622b43b18069d9b241c81a",false]},{"id":84251,"method":"getblock","params":["000000000000000001d01607ad2c9a5cc647f18dce1f064e2df9a6d1c12352f1",false]},{"id":84251,"method":"getblock","params":["0000000000000000025136ddd4cf47907473478b45482f78d6bca1761df967e0",false]},{"id":84251,"method":"getblock","params":["0000000000000000004c6bc2f9a89c414217421a31cee7fbac6ff1fe8dc38922",false]},{"id":84251,"method":"getblock","params":["000000000000000001bc619185c3bccf2c8894382c59ba4c76867b3215f53a72",false]},{"id":84251,"method":"getblock","params":["0000000000000000009f3c658f72ad7abc0d52e6ab0b13f33881f761009a2afa",false]},{"id":84251,"method":"getblock","params":["0000000000000000025485c6a58ecde13772bb9438b9693908736083c1028992",false]},{"id":84251,"method":"getblock","params":["000000000000000001dcab3c9961dcaff81e21851acf28c79bffc1e5b645e073",false]},{"id":84251,"method":"getblock","params":["0000000000000000017b911c332a70089f1260569905c2fd1dda46fc35272f58",false]},{"id":84251,"method":"getblock","params":["000000000000000001b844111d40c1582c131a1ee4ae105607e67684a0bb8bfd",false]},{"id":84251,"method":"getblock","params":["000000000000000001fe10a77d40a339651162a041445ea3c91197143ee41039",false]},{"id":84251,"method":"getblock","params":["0000000000000000010a2638c69028ea328bde155e3ad29d7b5c72036c8aae8f",false]},{"id":84251,"method":"getblock","params":["000000000000000001208f2bec0de18e983ae506d31ea8597fc6a92c440aa731",false]},{"id":84251,"method":"getblock","params":["0000000000000000015beb647799c06b348f914ce96ccae4066fc25f68314a3c",false]},{"id":84251,"method":"getblock","params":["00000000000000000007d205b68eb98437b8780324eb35d3d4fe479577711ded",false]},{"id":84251,"method":"getblock","params":["000000000000000001a213fb5ca2178a00a44ab2b8cdc8c8b081ea3827c81088",false]},{"id":84251,"method":"getblock","params":["000000000000000001cec9e0bb10cef09d48ce5ce2781e9d5b062f5e30cc79c7",false]}]
> Caused by: disconnected from daemon
>

**Comment by greenaddress** [comment]
This is the same issue as https://github.com/romanz/electrs/issues/18

**Comment by duckartes** [comment]
Gotcha. Guess I'll have to wait for updates.

**Comment by greenaddress** [comment]
@duckartes yep. Can we close as duplicate?

**Comment by duckartes** [comment]
Sounds good. Still learning Github.
