### ISSUE TITLE
Listunspent accepts an xpub?

### ISSUE THREAD

**Issue by iangregsondev** [romanz/electrs#393]
Hi,

is there a way of scanning for unspent utxos given the xpub or xpriv, but I think I need the derivation path.

not sure if this is possible?

I basically want to do a kind of wallet recovery, and I don’t have a list of addresses.

Thanks in advance.

**Comment by shesek** [comment]
Electrs doesn't support xpub lookups directly, but you can create a new watch-only Electrum wallet with your xpub(s) and connect it to your Electrs server.

**Comment by Kixunil** [comment]
I think if the issue is not knowing the derivation path, then Electrum doesn't help as it requires you to specify it.

**Comment by iangregsondev** [comment]
Thanks, everyone. Noted, I will look to figure out an alternative solution.
