### ISSUE TITLE
p2p-based sync fails to receive blocks

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#399]
Here's the output after updating to the latest commit:
```
Config { network: Bitcoin, db_path: "/home/electrs/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_cookie_file: "/home/bitcoin/.bitcoin/.cookie", daemon_rpc_addr: V4(127.0.0.1:8332), daemon_p2p_addr: V4(127.0.0.1:8333), electrum_rpc_addr: V4(0.0.0.0:50001), monitoring_addr: V4(127.0.0.1:4224), wait_duration: 30s, index_batch_size: 12, ignore_mempool: false, server_banner: "Welcome to electrs 0.9.0 (Electrum Rust Server)!", args: [] }
Error: initial sync failed
Caused by:
    0: failed to get block 00000000000006361896db3f164a5df9e83b2aa4f636e3ffac584d5b8c9c6c0c
    1: p2p failed to recv
    2: I/O error: unexpected end of file
```
If I let it run, it appears to keep failing on the same block.

I deleted the db dir (the service had been running, and failing, since I posted my issue), and then the block giving the error changed to this one:
`0: failed to get block 00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048`

It fails on the same block over and over, but every 10m or so it doesn't error right away and advances:
```
+10m: 0000000067217a46c49054bad67cda2da943607d326e89896786de10b07cb7c0
+20m: 0000000055fcaf04cb9a82bb86b46a21b15fcaa75ac8c18679b0234f79c4c615
+30m: 0000000000000591c56b14f82564036a1205b99e2831e2e89ea56eb75f165240
```
Thanks for your help!

_Originally posted by @RR82 in https://github.com/romanz/electrs/issues/308#issuecomment-841339030_

**Comment by romanz** [comment]
Seems like a sporadic failures on various height blocks:
```
$ bitcoin-cli getblockheader 00000000839a8e6886ab5951d76f411475428afc90947ee320161bbf18eb6048 | jq .height
1
$ bitcoin-cli getblockheader 0000000067217a46c49054bad67cda2da943607d326e89896786de10b07cb7c0 | jq .height
2001
$ bitcoin-cli getblockheader 0000000055fcaf04cb9a82bb86b46a21b15fcaa75ac8c18679b0234f79c4c615 | jq .height
6001
$ bitcoin-cli getblockheader 0000000000000591c56b14f82564036a1205b99e2831e2e89ea56eb75f165240 | jq .height
139620
$ bitcoin-cli getblockheader 00000000000006361896db3f164a5df9e83b2aa4f636e3ffac584d5b8c9c6c0c | jq .height
189649
```

**Comment by romanz** [comment]
Could you please run `bitcoind` with the following configuration:
```
$ bitcoind -server=1 -daemon=0 -debug=net -blocksonly -noconnect -listen
```
IIUC, it should log the reason for p2p sync failure.
On my machine, it works with the attached [p2p-sync.log](https://github.com/romanz/electrs/files/6492862/p2p-sync.log).

**Comment by romanz** [comment]
Also, does this issue reproduce on regtest/signet?

**Comment by romanz** [comment]
@RR82 Which version of bitcoind are you running?

**Comment by RR82** [comment]
- I have not tried regtest/signet.
- I was using bitcoin v 0.21.0 and now have upgraded to 0.21.1

After adding:
```
debug=net 
blocksonly=1 
noconnect=1 
listen=1
```
to bitcoin.conf, here is the log when the electrs p2p error occurs:
<pre><code>2021-05-18T23:16:13Z historical block serving limit reached, disconnect peer=0
2021-05-18T23:16:13Z disconnecting peer=0
2021-05-18T23:16:13Z Cleared nodestate for peer=0
<i><b>[electrs restarts here]</b></i>
2021-05-18T23:17:26Z initial getheaders (684123) to peer=2 (startheight:0)
2021-05-18T23:17:26Z sending getheaders (1029 bytes) peer=2
2021-05-18T23:17:26Z received: pong (8 bytes) peer=2
2021-05-18T23:17:26Z received: headers (1 bytes) peer=2
2021-05-18T23:17:26Z received: getheaders (933 bytes) peer=2
2021-05-18T23:17:26Z getheaders 207973 to end from peer=2
2021-05-18T23:17:26Z sending headers (162003 bytes) peer=2
2021-05-18T23:17:26Z received: getdata (433 bytes) peer=2
2021-05-18T23:17:26Z received getdata (12 invsz) peer=2
2021-05-18T23:17:26Z received getdata for: witness-block 00000000000002330cd5a7d555fb54c2c62e781db5a914645019d0b09d1c2b1e peer=2
2021-05-18T23:17:26Z historical block serving limit reached, disconnect peer=2
2021-05-18T23:17:26Z disconnecting peer=2
2021-05-18T23:17:27Z Cleared nodestate for peer=2
</code></pre>

After a quick search on _historical block serving limit reached_ error, I realized I had `maxuploadtarget=1000` in bitcoin.conf, commenting it out seems to have solved this issue. 

I don't think that setting caused an issue with the non-p2p electrs.

It is syncing now.

**Comment by Kixunil** [comment]
It'd be great if electrs at least detected this. Ideally fall back to RPC or some other technique. IDK if whitelist affects this setting but we should probably recommend whitelisting 127.0.0.1 just like NBXplorer does (it even detects lack of whitelisting and logs a message).

**Comment by RR82** [comment]
It has synced successfully and the p2p version solves my other issue that got me started with all of this: https://github.com/spesmilo/electrum/issues/7058

Thanks for all your help!!

**Comment by romanz** [comment]
Cool, happy it worked :)

**Comment by SimonVrouwe** [comment]
Not sure if this is the right place to post, but running p2p-branch 3bf5e5c266ecdbd10aa7709e495113521256e9f1 fixed https://github.com/spesmilo/electrum/issues/7255 for me. However when I run `bitcoind` with `maxconnections=11` or less, then `electrs` returns an error right after starting, see below.

```
simon@gamepc:~/git/electrs$ target/release/electrs --conf ~/.electrs_p2p/config.toml
Config { network: Bitcoin, db_path: "/home/simon/mount/data1TB/electrs_p2p_data/bitcoin", daemon_dir: "/home/simon/.bitcoin", daemon_cookie_file: "/home/simon/.bitcoin/.cookie", daemon_rpc_addr: V4(127.0.0.1:8332), daemon_p2p_addr: V4(127.0.0.1:8333), electrum_rpc_addr: V4(127.0.0.1:50002), monitoring_addr: V4(127.0.0.1:4224), wait_duration: 10s, index_batch_size: 10, ignore_mempool: false, server_banner: "Welcome to electrs 0.9.0 (Electrum Rust Server)!", args: [] }
[2021-07-18T12:23:17.905Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2021-07-18T12:23:18.311Z INFO  electrs::db] "/home/simon/mount/data1TB/electrs_p2p_data/bitcoin": 132 SST files, 30.806031513 GB, 3.833179759 Grows
[2021-07-18T12:23:18.313Z DEBUG electrs::db] DB Config { compacted: true, format: 0 }
[2021-07-18T12:23:18.879Z DEBUG electrs::db] auto-compactions enabled
[2021-07-18T12:23:20.908Z INFO  electrs::chain] loading 691563 headers, tip=000000000000000000107e982d2934c55242a7041669571f75d7208eb3212d48
[2021-07-18T12:23:23.149Z INFO  electrs::chain] chain updated: tip=000000000000000000107e982d2934c55242a7041669571f75d7208eb3212d48, height=691563
[2021-07-18T12:23:23.550Z INFO  electrs::db] closing DB at "/home/simon/mount/data1TB/electrs_p2p_data/bitcoin"
[2021-07-18T12:23:23.556Z DEBUG electrs::metrics::metrics_impl] closing Prometheus server
Error: failed to get headers

Caused by:
    0: p2p failed to recv
    1: I/O error: unexpected end of file
```

Setting `maxconnections=12` resolves this consistently, at least on a fully synced `electrs`. Adding the options `whitelist=127.0.0.1` and `whitebind=127.0.0.1:8333` to `bitcoin.conf` does not make any difference. The number of peers connected to `bitcoind` is far below `maxconnections` when `electrs` crashes, checked using `bitcoin-cli getpeerinfo | jq '. | length'`.

Build details:
```
git pull && checkout p2p
cargo build --all --release 
export RUST_LOG=electrs=debug
```
System:
Bitcoin Core version v0.21.1
Linux gamepc 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux
8-core, 16GB ram

**Comment by romanz** [comment]
Thanks for reporting this issue!
I have opened #429 - let's discuss it there.
