### ISSUE TITLE
`librocksdb` fails to build on a Raspberry Pi 4

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#403]
I've had another try at compiling `librocksdb` on a Raspberry Pi 4, which is failing with the following error:

```
error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DZSTD=1" "-DNDEBUG=1" "-DOS_LINUX" "-DROCKSDB_PLATFORM_POSIX" "-DROCKSDB_LIB_IO_POSIX" "-o" "/home/xxx/git/electrs/target/release/build/librocksdb-sys-320abe6ed7d88d37/out/rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.o" "-c" "rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.cc" with args "c++" did not execute successfully (status code exit code: 1).
```

I've now run the `c++` compilation command outside the script, and it seems the architecture is either not supported or not properly detected:

```
~/.cargo/git/checkouts/rust-rocksdb-949349bba4a70d36/379c2d7/librocksdb-sys $ "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "zstd/lib/" "-I" "zstd/lib/dictBuilder/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DZSTD=1" "-DNDEBUG=1" "-DOS_LINUX" "-DROCKSDB_PLATFORM_POSIX" "-DROCKSDB_LIB_IO_POSIX" "-o" "/home/xxx/git/electrs/target/release/build/librocksdb-sys-320abe6ed7d88d37/out/rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.o" "-c" "rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.cc"
In file included from rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/locktree.h:62,
                 from rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.h:59,
                 from rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/lock_request.cc:56:
rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/../portability/toku_time.h:137:2: error: #error No timer implementation for this platform
 #error No timer implementation for this platform
  ^~~~~
rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/../portability/toku_time.h: In function ‘tokutime_t toku_time_now()’:
rocksdb/utilities/transactions/lock/range/range_tree/lib/locktree/../portability/toku_time.h:139:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
```

_Originally posted by @craigraw in https://github.com/romanz/electrs/issues/308#issuecomment-845122206_

**Comment by romanz** [comment]
@craigraw Could you please try to build https://github.com/rust-rocksdb/rust-rocksdb to find when it started to fail building on RPi4?
I think that `0.12.2` should be OK - since it's used in `master` branch.

**Comment by romanz** [comment]
It seems that it indeed doesn't support ARM 32-bit targets:
```c
// Get the value of tokutime for right now.  We want this to be fast, so we
// expose the implementation as RDTSC.
static inline tokutime_t toku_time_now(void) {
#if defined(__x86_64__) || defined(__i386__)
  uint32_t lo, hi;
  __asm__ __volatile__("rdtsc" : "=a"(lo), "=d"(hi));
  return (uint64_t)hi << 32 | lo;
#elif defined(__aarch64__)
  uint64_t result;
  __asm __volatile__("mrs %[rt], cntvct_el0" : [ rt ] "=r"(result));
  return result;
#elif defined(__powerpc__)
  return __ppc_get_timebase();
#else
#error No timer implementation for this platform
#endif
}
```

**Comment by romanz** [comment]
It was added to rocksdb at https://github.com/facebook/rocksdb/commit/98236fb10ecdbe6e7e8ef5cfb11e1f11dcb72f84.

**Comment by romanz** [comment]
@craigraw IIUC, https://github.com/romanz/electrs/commit/ce0018be5787e03b8f2c9c37a01178b29be68fe3 on `p2p` branch should use rocksdb 6.15.4 which should compile on ARM 32-bit. Could you please try building it on RPi4?

**Comment by craigraw** [comment]
It's working! Compiled and now indexing on testnet. I'll close this off.

**Comment by romanz** [comment]
Cool, thanks for reporting and testing!

**Comment by fooedge2** [comment]
Doesn't compile for me. I original problem is gone, but now I get linker errors after compilation

```
pi@raspberrypi:~/electrs $ cargo build --locked --release
   Compiling electrs v0.9.0 (/home/pi/electrs)
error: linking with `cc` failed: exit code: 1
```
mainly reference to __atomic_load_8, __atomic_store_8, __atomic_compare_exchange_8, __atomic_fetch_or_8, ... are missing. 

`/usr/bin/ld: memtable.cc:(.text._ZN7rocksdb8MemTable3AddEyNS_9ValueTypeERKNS_5SliceES4_bPNS_23MemTablePostProcessInfoEPPv+0x250): undefined reference to `__atomic_load_8'`

**Comment by romanz** [comment]
Which RPi are you using?
How much RAM does it have available?

**Comment by fooedge2** [comment]
It's a raspberry pi 4 with 8 GB RAM. RAM is not the issue here, it was only using 1,3 GByte when it failed. I think it's more related to a linker option, I was just looking at this problem and found this post:

https://github.com/redis/redis/issues/6275

I know this is not related to electrs but maybe the linker option should be adapted in a similar way. I'm still surprised why it works for craigraw.

**Comment by fooedge2** [comment]
Yay! No errors! 

Finished release [optimized] target(s) in 32m 23s

Ok, that worked. I will now try to index the database again, this did take around 1-2 days in the past.

**Comment by Kixunil** [comment]
Ideally this should be fixed in `rocksdb-sys`

**Comment by fooedge2** [comment]
Do I need to start the p2p version differently? It starts without errors and creates initially a few index files in the database directory but then it does nothing anymore (no cpu usage, no writes to the SSD, ...)

`May 20 21:55:55 raspberrypi electrs[23635]: Config { network: Bitcoin, db_path: "/mnt/bitcoin/electrs/db/bitcoin", daemon_dir: "/mnt/bitcoin", daemon_cookie_file: "/mnt/bitcoin/.cookie", daemon_rpc_addr: V4(127.0.0.1:8332), daemon_p2p_addr: V4(127.0.0.1:8333), electrum_rpc_addr: V4(127.0.0.1:50001), monitoring_addr: V4(127.0.0.1:4224), wait_duration: 10s, index_batch_size: 10, ignore_mempool: false, server_banner: "Welcome to electrs 0.9.0 (Electrum Rust Server)!", args: [] }`

**Comment by romanz** [comment]
Could you please increase the log verbosity to DEBUG and attach the full log?
I also suggest testing on `signet`, since it should finish the indexing in <1 minute.
```
$ RUST_LOG=electrs=debug ./server.sh signet
```

**Comment by AaronDewes** [comment]
Why is arm32 still needed? AFAIK electrs & bitcoin core are often using more than 1GB of RAM, and the Pi supports arm64 on these models

- Raspberry Pi 2B Rev 1.2
- Raspberry Pi 3A+
- Raspberry Pi 3B
- Raspberry Pi 3B+
- Raspberry Zero 2 W
- Raspberry Pi 4B
- Raspberry Pi Compute Module 3 (& 3+, all variants)
- Raspberry Pi Compute Module 4

So most recent Rasoberry Pi boards support it, and all board with at least 1GB of RAM (except some early Pi 2 models) support arm64.

**Comment by Kixunil** [comment]
AFAIK Raspbian is still 32-bit and quite popular. Looking forward to this changing.

**Comment by romanz** [comment]
IIUC, there are 64-bit builds of Raspberry Pi OS (https://downloads.raspberrypi.org/raspios_arm64/images/) but I never tried them.

**Comment by romanz** [comment]
OTOH, [it seems that Raspiblitz 1.7 is based on a 64-bit base image](https://github.com/rootzoll/raspiblitz/blob/306c7d9f914170e513c76aab0fd5f2e326c838a8/CHANGES.md#whats-new-in-version-170-of-raspiblitz) :)
