### ISSUE TITLE
Bug: mempool.get_fee_histogram returns bogus values

### ISSUE THREAD

**Issue by craigraw** [romanz/electrs#404]
**Describe the bug**
When using the p2p branch on testnet, calling `mempool.get_fee_histogram` returns values that are not useful, and can actually break client applications. Here is the result of the call on my machine:
```
{"id":10,"jsonrpc":"2.0","result":[[18446744073709551615,0],[9223372036854775807,0],[4611686018427387903,0],[2305843009213693951,0],[1152921504606846975,0],[576460752303423487,0],[288230376151711743,0],[144115188075855871,0],[72057594037927935,0],[36028797018963967,0],[18014398509481983,0],[9007199254740991,0],[4503599627370495,0],[2251799813685247,0],[1125899906842623,0],[562949953421311,0],[281474976710655,0],[140737488355327,0],[70368744177663,0],[35184372088831,0],[17592186044415,0],[8796093022207,0],[4398046511103,0],[2199023255551,0],[1099511627775,0],[549755813887,0],[274877906943,0],[137438953471,0],[68719476735,0],[34359738367,0],[17179869183,0],[8589934591,0],[4294967295,0],[2147483647,0],[1073741823,0],[536870911,0],[268435455,0],[134217727,0],[67108863,0],[33554431,0],[16777215,0],[8388607,0],[4194303,0],[2097151,0],[1048575,0],[524287,0],[262143,0],[131071,0],[65535,0],[32767,0],[16383,0],[8191,0],[4095,141],[2047,0],[1023,0],[511,202],[255,0],[127,4188],[63,803],[31,0],[15,435],[7,332],[3,1567],[1,6210]]}
```

The first few values here indicate a fee rate that is higher than the total amount of BTC ever possible.  In fact, the first value is so high (>2^64) that it breaks Sparrow's parsing into a Java signed `long` value. 

**To Reproduce**
1. Configure electrs-p2p on testnet and start
2. Connect with any client that calls `mempool.get_fee_histogram`

**Expected behavior**
Although the choice of fee intervals is left to the implementation, it seems reasonable to truncate the list where the cumulative virtual size at that fee rate, and all the ones above it, are zero.

**Configuration**
Arguments: `--testnet`

**System running electrs**
 - Deployment method: manual from source
 - Raspberry Pi 4 
 
**Electrum client**
Sparrow 1.4.1

**Comment by romanz** [comment]
Thanks for reporting this issue!
It should be fixed by https://github.com/romanz/electrs/commit/f6fac2478c599e3cfb9627f25d11f4151fd4fabb.

**Comment by craigraw** [comment]
Looks good! Confirmed it's working. Thanks for the quick fixing.
