### ISSUE TITLE
Notification failure should not result in closing the server

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#406]
During my testing the electrs server process occasionally terminated with the following error:
```
Error: server failed

Caused by:
    0: failed to send response: {"jsonrpc":"2.0","method":"blockchain.headers.subscribe","params":[{"height":1976465,"hex":"000000203f3..."}]}
    1: Broken pipe (os error 32)
```

_Originally posted by @craigraw in https://github.com/romanz/electrs/issues/405#issuecomment-846957921_

**Comment by romanz** [comment]
Thanks for reporting the issue!
It should be fixed by https://github.com/romanz/electrs/commit/f4102dca8670de8460836e39e3f578722cee58e9

**Comment by craigraw** [comment]
Thanks! Running these changes, will report if there are any issues.
