### ISSUE TITLE
Broadcast request causes server to disconnect

### ISSUE THREAD

**Issue by craigraw** [romanz/electrs#408]
On the P2P branch:

Broadcasting any transaction is failing with the following error presented in the electrs logging output:
```
[2021-06-02T07:58:36.597Z ERROR electrs::server] 23: disconnecting due to failed to handle request: {"jsonrpc":"2.0","method":"blockchain.transaction.broadcast","params":{"raw_tx":"0200000000010100..."},"id":9}
```

There is nothing related in bitcoind `debug.log`. This is on testnet.

I've successfully broadcast the transaction through blockstream.info, so the transaction is valid. I believe this used to work fine - I'm running the latest p2p HEAD so might have been a recent change.

**Comment by romanz** [comment]
I think that the current JSON RPC server doesn't support "keyword parameters":
```
"params":{"raw_tx":"0200000000010100..."}
```
It expected it to be an array of JSON values, e.g.:
```
"params":["0200000000010100..."]
```

**Comment by craigraw** [comment]
Confirmed, I've changed that on my side and it works.
