### ISSUE TITLE
Bug: Blue Wallet fails with 'RPC failed: no subscription for scripthash' while connecting to p2p branch. 

### ISSUE THREAD

**Issue by ulzeraj** [romanz/electrs#416]
Hi. I'm getting the mentioned error when I try to connect blue wallet to an electrs instance from the p2p branch.

From tcpdump the payload seems to be like this:

```
{"jsonrpc":"2.0","method":"blockchain.scripthash.get_history","params": ["omitted_hash"],"id":ommited_numerical_id}
```

So I've tried:

```
echo '{"jsonrpc":"2.0","method":"blockchain.scripthash.get_history","params": ["omitted_hash"],"id": ommited_numerical_id}' | nc localhost 50001 | jq .
```

And the response is:

```
{
  "error": {
    "code": 1,
    "message": "RPC failed: no subscription for scripthash"
  },
  "id": ommited_numerical_id,
  "jsonrpc": "2.0"
}
```

I've switched to p2p because its easier to build on FreeBSD. I think this error was not present while using the main branch.

Thank you.

**Comment by Pantamis** [comment]
Same for me with RPC-Explorer and `blockchain.scripthash.get_balance` method !

It seems to be related to #310 

Sparrow works great for me.

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
Opened two new issues - I didn't implement them yet on `p2p` branch :)

**Comment by romanz** [comment]
Should be fixed now in `p2p` branch.
