### ISSUE TITLE
MSRV plans regarding bullseye?

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#423]
I wonder what the plans regarding bullseye are. Will MSRV be bumped? AFAIK we could do some nice dependency cleanup if it was.

**Comment by romanz** [comment]
> Will MSRV be bumped? AFAIK we could do some nice dependency cleanup if it was.

Yes, I think it will be great to bump to 1.48.0 (https://packages.debian.org/bullseye/rustc) when bullseye is released.

**Comment by romanz** [comment]
Hopefully, it will happen soon™ :)
https://lists.debian.org/debian-release/2021/06/msg00200.html

**Comment by romanz** [comment]
The planned release date is Aug 14:
https://lists.debian.org/debian-devel-announce/2021/07/msg00003.html

**Comment by Kixunil** [comment]
FTR I just successfully compiled `electrs` 0.8.8 (IDK why I still have that one in the project) on bullseye with dynamic linking without issues. Will test later.

**Comment by Kixunil** [comment]
Maybe we should wait a bit longer with MSRV bumping - at least until newer version is in Raspbian, which is quite popular. Or at least do it some time after 0.9.0 release, which will bring important performance improvements and it'd be nice to enable them for RPi users.

My thinking is to release 0.9.0, wait a while to see if there are any issues that should be fixed too, then bump MSRV or bump MSRV when newer version is available in both Debian and Raspbian.

See also https://github.com/Stadicus/RaspiBolt/issues/747#issuecomment-894627169

**Comment by romanz** [comment]
https://bits.debian.org/2021/08/bullseye-released.html :)

**Comment by romanz** [comment]
Latest release bumped MSRV to 1.48.0 (#455).
