### ISSUE TITLE
Fix GitHub actions to use correct Rust version for testing

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#436]
GA seems to use something else than what's in `rust-toolchain` file.

**Comment by Kixunil** [comment]
Partially fixed by #438 but it's imperfect solution as it may get out-of-sync with `rust-toolchain`.

**Comment by romanz** [comment]
I think that https://github.com/romanz/electrs/pull/441 should work:
https://github.com/romanz/electrs/runs/3133681404?check_suite_focus=true#step:3:11

**Comment by Kixunil** [comment]
That's even nicer than I anticipated. I guess it's thanks to **not** using toml format of `rust-toolchain`
