### ISSUE TITLE
server.features protocol method not implemented

### ISSUE THREAD

**Issue by Overtorment** [romanz/electrs#439]
Jul 22 11:02:06 aaa electrs[25439]: 2021-07-22T11:02:06.326+01:00 - TRACE - RPC Request("{\"jsonrpc\":\"2.0\",\"method\":\"server.features\",\"params\":[],\"id\":6}\n")
Jul 22 11:02:06 aaa electrs[25439]: 2021-07-22T11:02:06.326+01:00 - ERROR - [127.0.0.1:41596] connection handling failed: Error: unknown method server.features []

ver 0.8.9

**Comment by Kixunil** [comment]
This seems more like a feature request to support that method? Unless Electrum relies on it.

**Comment by Overtorment** [comment]
Yeah you could call it a feature request.
Bluewallet relies on in, but only on electrum settings debug screen.

**Comment by Overtorment** [comment]
Method is documented here: https://electrumx.readthedocs.io/en/latest/protocol-methods.html#server-features

**Comment by romanz** [comment]
Thanks for reporting the issue!
Will add it to `p2p` branch - to be part of the `0.9` release.

**Comment by Kixunil** [comment]
That other doc says "The following features MUST be reported by the server." which suggests it's mandatory and therefore this is indeed bug. But IDK whether I'm correct and which docs should be considered "official".

**Comment by Overtorment** [comment]
> But IDK whether I'm correct and which docs should be considered "official".

definitely not https://electrum.readthedocs.io/en/latest/protocol.html

![image](https://user-images.githubusercontent.com/1913337/126675295-154d5db3-7089-4077-8c6d-bd75bceeaa0c.png)

**Comment by romanz** [comment]
Should be fixed by #445.
