### ISSUE TITLE
Bug: p2p configuration seems to be messed up

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#440]
**Describe the bug**
`auth` doesn't seem to be used in `p2p` branch, only `cookie_file`.
Moreover the original plan was to turn use of `cookie` into hard error *with a nice message* before removing it entirely.
Do we still want to do that? I think it'd be nicer for at least one release.

**To Reproduce**
1. `git checkout p2p`
2. `vim src/config.rs`
3. `/auth`
4. "Pattern not found: auth"

**Expected behavior**
`auth` is used instead of cookie if specified (error if both are specified).

**Additional context**
Was just thinking about turning it into hard error in 0.9 - looks like we're thinking the same here.

**Comment by romanz** [comment]
Oops, good catch - thanks!
Will fix.

**Comment by romanz** [comment]
Should be fixed in #442, please take a look :)

**Comment by romanz** [comment]
Log verbosity is not propagated correctly: https://github.com/romanz/electrs/pull/446#issue-696338090
