### ISSUE TITLE
Config: no txid_limit in p2p branch

### ISSUE THREAD

**Issue by Pantamis** [romanz/electrs#447]
ElectRS can hang a long time without responding if it is asked to provide the history of a scripthash with a lot of transactions. txid_limit is used in master branch to stop the query prevently in that case. It doesn't seems to be implemented in p2p branch.

It would be useful to implement Electrum 1.5 compatibility too since get_history will add feature to support pagination of long history (txid_limit could be used to set the length of returned part of history)

**Comment by Kixunil** [comment]
> get_history will add feature to support pagination of long history

Thank God, I was just going to suggest something like that. Great that others thought about it as well.
