### ISSUE TITLE
Bug: Killed during "starting full compaction"

### ISSUE THREAD

**Issue by kentschubert** [romanz/electrs#453]
electrs Killed during "starting full compaction"

Followed Raspibolt pi set for bitcoin core, lnd, and electrs
$ electrs --conf /mnt/ext/electrs/electrs.conf
Seems to complete indexing...
2021-08-09T02:50:18.499+01:00 - DEBUG - no more blocks to index
2021-08-09T02:50:21.087+01:00 - DEBUG - last indexed block: best=00000000000000000001c35ba10dabccdb8d36789429e0d69d214f068c7ec93a height=694876 @ 2021-08-09T00:24:17Z
2021-08-09T02:50:21.211+01:00 - INFO - starting full compaction
Killed

**Configuration**
AUTH="{myrpcuser}:{myrpcpasswd}"
# Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/mnt/ext/bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"

# Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/mnt/ext/electrs/db"
txid_limit = 1000

# Logging
verbose = 4
timestamp = true
rust_backtrace = true

**System running electrs**
raspi 4 8GB + 1.9TB SSD, 4GB swapfile
deployed as per https://stadicus.github.io/RaspiBolt/raspibolt_50_electrs.html#install-dependencies

**Additional context**
Deep into "starting full compaction" system appears to become over-taxed (laggy).
Excerpt from last entries in /mnt/ext/electrs/db/mainnet/LOG :

**Compaction Stats [default]**
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0    564/564 90.04 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0      4.3         2         1    2.482       0      0
 Sum    564/564 90.04 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0      4.3         2         1    2.482       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
Uptime(secs): 6001.0 total, 0.0 interval
Flush(GB): cumulative 0.010, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.01 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 2.5 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memt$

** File Read Latency Histogram By Level [default] **
2021/08/09-11:58:53.450956 b50ff3a0 [db/compaction_job.cc:1374] [default] [JOB 7] Generated table #746: 18011411 keys, 270266717 bytes
2021/08/09-11:58:53.451892 b50ff3a0 EVENT_LOG_v1 {"time_micros": 1628506733451842, "cf_name": "default", "job": 7, "event": "table_file_creation", "file_number": 746, "file_size": 270266717, "table_properties": {"data_size": 26843$
2021/08/09-12:01:22.011088 b50ff3a0 [db/compaction_job.cc:1374] [default] [JOB 7] Generated table #747: 17990656 keys, 270264371 bytes
2021/08/09-12:01:22.013783 b50ff3a0 EVENT_LOG_v1 {"time_micros": 1628506882013733, "cf_name": "default", "job": 7, "event": "table_file_creation", "file_number": 747, "file_size": 270264371, "table_properties": {"data_size": 26843$
2021/08/09-12:07:03.536245 b38fc3a0 [WARN] [db/db_impl.cc:669] ------- DUMPING STATS -------

Any suggestions would be greatly appreciated.

**Comment by Kixunil** [comment]
This looks exactly like having low memory but it's surprising because I'd expect 8GB to be enough. It'd be really nice if you tried again while monitoring RAM usage to determine if it's actually `electrs` eating too much RAM or other app eat a lot too. If you don't want to help with diagnostics and only wan to get it working ASAP try using json RPC import.

**Comment by kentschubert** [comment]
>  It'd be really nice if you tried again while monitoring RAM usage to determine if it's actually `electrs` eating too much RAM or other app eat a lot too.

Thanks so much for the suggestion.  As per your suggestion, I've tried again, several times, and monitored closely using top and htop.  Both of those monitoring apps revealed no memory issues: e.g. electrs purrs along at a steady <25% memory usage right through the point that that it is Killed, deep into "starting full compaction".  No other apps are consuming any significant amount of memory.  Is it possible that there could be a sudden surge/spike in memory usage that htop and top are not revealing (i.e. so sudden, electrs kills before the spike registers on htop or top?)?   If you think this makes sense, I will  take your suggestion a little further, and install Prometheus to see if it can pinpoint any such potential spike in mem usage.  I'd be grateful for your opinion on this.

**Comment by Kixunil** [comment]
I'm not really sure. I think it'd be best to first check if it was indeed OOM killed by running `dmesg -T | grep -i 'killed process'` or `grep -i 'killed process' /var/log/messages`.

If it was then, given your findings, I'd guess you have OOM killer set to too aggressive settings and maybe you should relax it. If it wasn't killed by OOM killer than I have no clue what it could be.

If it is a spike it'd likely happen somewhere inside rocksdb and Prometheus will not help you. Maybe you could [disable overcommit](https://serverfault.com/questions/141988/avoid-linux-out-of-memory-application-teardown) and maybe we could get an exact line where a big chunk of memory is allocated, then figure out if it can be decreased.

**Comment by kentschubert** [comment]
> I think it'd be best to first check if it was indeed OOM killed by running `dmesg -T | grep -i 'killed process'` or `grep -i 'killed process' /var/log/messages`.

Thanks, again, for your suggestion.  Appears it is an OOM-Kill.  I'll follow through on your suggestion to potentially relax the oom-kill settings.  If you have any other thoughts or suggestions, I'd be grateful.

[dmesg output.txt](https://github.com/romanz/electrs/files/6988071/dmesg.output.txt)

$ dmesg -e | grep -i kill
[ +34.317133] kthreadd invoked oom-killer: gfp_mask=0x400dc0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), order=1, oom_score_adj=0
[  +0.000017] [<c0b85080>] (dump_header) from [<c03b8800>] (oom_kill_process+0x1b4/0x1c0)
[  +0.000009] [<c03b864c>] (oom_kill_process) from [<c03b9378>] (out_of_memory+0x2b8/0x390)
[  +0.000024] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/,task=electrs,pid=18258,uid=1002
[  +0.000153] Out of memory: Killed process 18258 (electrs) total-vm:2261012kB, anon-rss:1222084kB, file-rss:1204kB, shmem-rss:0kB, UID:1002 pgtables:4392kB oom_score_adj:0

**Comment by kentschubert** [comment]
Resolved.  After doing a lot of reading on the subject I decided against changing the memory management settings of my machine (no change to vm.oom-kill, no change to vm.overcommit_memory), and instead, disabled rust_traceback by commenting-out  rust_traceback = true  in my electrs.conf file.  Success.  Thanks for the suggestions and ideas - they assisted the thought process.

**Comment by Kixunil** [comment]
I believe you mean `RUST_BACKTRACE`?

If you have the time could you check the change in #459 to see if it also crashes with `RUST_BACKTRACE=1`?
It may be *the proper* fix but I'm not sure.

**Comment by kentschubert** [comment]
> If you have the time could you check the change in #460 to see if it also crashes with `RUST_BACKTRACE=1`?

Replacing my electrs.conf line `rust_backtrace=true` with `RUST_BACKTRACE=1` solves crash problem.  I ran multiple replications over the weekend to confirm.

Thanks again for your help and your contributions.

**Comment by Kixunil** [comment]
Now I'm incredibly confused. The `rust_backtrace` option should do nothing. It's not processed by `electrs` at all. How come it has any effect on you? Do you happen to use some other fork of `electrs`? Maybe I'm missing something - @romanz do you have any idea?

**Comment by romanz** [comment]
Nope... looks strange indeed :(

**Comment by kentschubert** [comment]
> Do you happen to use some other fork of `electrs`?
I followed RaspiBolt electrs documentation, including the suggested electrs.conf settings (https://stadicus.github.io/RaspiBolt/).  Current electrs version = v0.8.10.  Other than the issue reported here (resolved by removing `rust_backtrace=true`), that documentation worked splendidly for me.

**Comment by kentschubert** [comment]
> Do you happen to use some other fork of `electrs`?

I followed RaspiBolt electrs documentation, including the suggested electrs.conf settings (https://stadicus.github.io/RaspiBolt/). Current electrs version = v0.8.10. Other than the issue reported here (resolved by removing rust_backtrace=true), that documentation worked splendidly for me.

**Comment by romanz** [comment]
@kentschubert Could you please re-test with the latest `0.9.0-rc1` release?

**Comment by kentschubert** [comment]
> @kentschubert Could you please re-test with the latest `0.9.0-rc1` release?

My sincere apologies for the tardy response.   I just upgraded Electrs v0.8.10 to v0.9.0 (on my Raspi 4, 8GB Raspibolt config).  I  followed your updated documentation.  Well done.  My update went flawlessly.  Electrs 0.9.0 working beautifully.  Thanks so much.

**Comment by romanz** [comment]
Cool, happy it worked for you :)
