### ISSUE TITLE
Unable to use "sweep" function in Electrum

### ISSUE THREAD

**Issue by HardCorePawn** [romanz/electrs#47]
When trying to use "Wallet -> Private Keys -> Sweep"

The client "hangs" for an extended period of time, the following error is logged multiple times by the server and then the client returns a "Server did not answer" message.

> 2018-08-07T08:43:13.273+12:00 - ERROR - [127.0.0.1:63592] connection handling failed: Error: unknown method blockchain.scripthash.listunspent [String("033b.....07fb")]

The client then shows as offline (red dot) and the errors continue to be logged by the server until the client is shutdown.

**Comment by greenaddress** [comment]
@HardCorePawn what version are you using of electrs? Can you reproduce with the current master version of electrs?

Electrs didn't used to support sweeping a few weeks back but it has been added since (unless it broke recently)

**Comment by romanz** [comment]
Indeed, it should be fixed by #25.

**Comment by HardCorePawn** [comment]
I had looked through other issues, but failed to see #25 

Can confirm that after updating via git and recompiling that "sweeping" works.
