### ISSUE TITLE
Possible index optimization for P2P

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#474]
When looking into index schema to understand it better I found a possible optimization: Instead of having separate txid -> height, txid, vout -> height records, consider having common record txid, vout -> height, Option\<height\>.

* When a transaction with unspent output(s) is added a record with vout = 2^32-1 is added that has height equal to confirmed height.
* When an output is spent, and there exists 2^32-1 vout add a record txid, vout -> spent_height, confirm_height, then remove 2^31-1 record.
* When an output is pent and there's no 2^32 vout just add txid, vout -> spent_height
* To read confirm height find txid and iterate over records, if there's a record with two heights or one with vout = 2^31-1 return the last height
* To read spent height just find txid, vout and read the former height

Possibly to avoid search when fetching confirm height always put confirm height into the recorrd with smallest vout (thus when a new output is spent this may need to change records). This makes writes slower but reads faster. Not sure which is better.

(2^31-1 vout is OK because block size prevents that many outputs to exist.)

Forgot to explain why this should be more optimal: it introduces overhead of 4B per UTXO but reduces overhead by 8B for each transaction with at least one **spent** output. There's more transactions with at least one spent output than UTXOs, so it should be net-benefit. ~~This will be true as long as there's more non-coinbase transactions than coinbase transactions.~~ Not exactly because a transaction with many outputs can lead to many transactions with unspent outputs.

**Comment by romanz** [comment]
Good suggestion - but unfortunately it would require DB reads during the indexing process (which is currently is write-only).
Since we disable compaction during initial sync, such reads will be significantly slower - and will cause the indexing to take more time.

**Comment by Kixunil** [comment]
Ah, I see, so probably not worth it. Closing this, if anyone can prove it's worth it we may reopen.
