### ISSUE TITLE
Feature: blockchain.scripthash.listunspent

### ISSUE THREAD

**Issue by gr0kchain** [romanz/electrs#475]
Electrum v1.3 deprecates `blockchain.address.listunspent` in favour of `blockchain.scripthash.listunspent`.

Noted that this is currently available in the master branch, but not the p2p branch which includes batching support. 

https://electrumx.readthedocs.io/en/latest/protocol-methods.html#blockchain.scripthash.listunspent

**Comment by romanz** [comment]
Please take a look at #485 :)

**Comment by romanz** [comment]
Should be now resolved in `p2p` branch.

**Comment by gr0kchain** [comment]
Tested and this seems to work as expected! Thanks for taking the time to assist in getting this implemented
