### ISSUE TITLE
Re-use `rust-bitcoin` Network enum

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#48]
https://github.com/rust-bitcoin/rust-bitcoin/blob/bf9c749b0c3c63dc2154bacf4d8c1c61dfe1d734/src/network/constants.rs#L53

**Comment by romanz** [comment]
Latest `bitcoin` crate doesn't support Regtest :(
https://docs.rs/bitcoin/0.13.2/bitcoin/network/constants/enum.Network.html

**Comment by greenaddress** [comment]
@romanz 0.14.0 has been released https://github.com/rust-bitcoin/rust-bitcoin/releases/tag/0.14
