### ISSUE TITLE
Logo for electrs

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#481]
**Is your feature request related to a problem? Please describe.**
It's sometimes desirable to communicate a list of projects by using their logos instead of names. Such lists can be understood by humans without reading everything making it more appealing. Electrs currently doesn't have a logo.

**Describe the solution you'd like**
Create a logo for Electrs. I may be able to get someone to design it, we need to just think what should there be.
I'm thinking that the logo should have the Rusts gear around or at least part of it (e.g. a quater).
Apart from reference to Rust it communicates being technical component which it is.
I'm not sure about the rest. Two things that come to mind is `E` letter in some reasonable font or modified Electrum logo (inside the gear). Would like to hear other ideas. Of course @romanz you should be the final decider what it will be.

**Describe alternatives you've considered**
List electrs by name or skip it :cry: 

**Additional context**
I'd like to add an icon to my repository and to my donation site I'm creating.
A logo may also be a nice marketing move for 0.9, hopefully also attracting contributors, not just users. :)

**Comment by romanz** [comment]
Sounds great, many thanks for the suggestion - much appreciated!

Maybe we can use the "atom diagram" from [the Electrum logo](https://electrum.org/logo/electrum_logo.png) - and put the ["Rust gear"](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/330px-Rust_programming_language_black_logo.svg.png) inside/around it?
Something like https://i.etsystatic.com/8544920/r/il/197e80/1529979094/il_fullxfull.1529979094_7m2q.jpg :)

**Comment by Kixunil** [comment]
A friend made some nice suggestion, sent to your e-mail (the one I got heads up about electrs improvement proposal).

**Comment by Kixunil** [comment]
Closed by #510
