### ISSUE TITLE
Cannot publish `0.9.0-rc1` on crates.io :disappointed: 

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#489]
```
$ cargo publish 
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `bitcoincore-rpc` does not specify a version
Note: The published dependency will use the version from crates.io,
the `git` specification will be removed from the dependency declaration.
```

Currently, we are using unpublished `bitcoincore-rpc` and `rocksdb` dependencies:
https://github.com/romanz/electrs/blob/62e404848b47faa0c332ddfc55672acc8e1190e0/Cargo.toml#L39-L51

**Comment by AaronDewes** [comment]
It's not directly related to this issue, but the migration guide and config example are a bit confusing. The upgrade guide mentions to change the electrs config for p2p. However, the config example only contains `daemon_rpc_addr`. What is needed in practice now? `daemon_p2p_addr`, `daemon_rpc_addr` or both?

**Comment by Kixunil** [comment]
> It's not directly related to this issue

Then why you didn't open a new issue?

> the config example only contains `daemon_rpc_addr`

Good point! Will look into updating later meanwhile you can just run `electrs --help` to learn new arguments or use `cfg_me man` (see docs) to see man page which includes detailed information on configuration files. These two are auto-generated, so they are definitely up to date.

> What is needed in practice now? `daemon_p2p_addr`, `daemon_rpc_addr` or both?

Both are needed, note that they are different things: p2p addr refers to P2P protocol (port), usually localhost:8333, rpc addr refers to JSON RPC, usually localhost:8332.

**Comment by romanz** [comment]
32b6340cc1ec2cd35e624a5fbe281c327a0bcdcf uses [`core-rpc`](https://github.com/RCasatta/rust-bitcoincore-rpc) instead of [`bitcoincore-rpc`](https://github.com/rust-bitcoin/rust-bitcoincore-rpc).

**Comment by romanz** [comment]
I'll probably do similar trick to `rocksdb` as done in https://github.com/RCasatta/rust-bitcoincore-rpc/commit/af7ac9fb9e36f9b0810f67901e43753187a31885 for `bitcoincore-rpc`.

**Comment by romanz** [comment]
Done in https://github.com/romanz/electrs/commit/357bfe896db5296c854c25952151ef89feaf4333, using the following forked crates:
- https://crates.io/crates/electrs-librocksdb-sys/6.11.4-e1
- https://crates.io/crates/electrs-rocksdb/0.15.0-e1

**Comment by romanz** [comment]
`0.9.0-rc1` is released :)

**Comment by Kixunil** [comment]
Cool! I hope to find some time to check if those changes can be upstreamed as maintaining a fork is not great.
