### ISSUE TITLE
Bug: 0.9.0-rc1 causes `rust-bitcoin` to panic when logging a non-standard script on 32-bit platforms

### ISSUE THREAD

**Issue by dematerializer** [romanz/electrs#490]
**Describe the bug**
After upgrading to 0.9.0-rc1, reindexing is giving the following error message:
```
Sep 18 22:41:15 raspberrypi electrs[12714]: thread '<unnamed>' panicked at 'slice index starts at 5 but ends at 4', /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin-0.27.0/src/blockdata/script.rs:531:32
Sep 18 22:41:15 raspberrypi electrs[12714]: [2021-09-18T20:41:15.780Z INFO  electrs::db] closing DB at /mnt/ext/electrs/db/bitcoin
Sep 18 22:41:15 raspberrypi systemd[1]: electrs.service: Main process exited, code=exited, status=101/n/a
Sep 18 22:41:15 raspberrypi systemd[1]: electrs.service: Failed with result 'exit-code'.
```

**Electrs version**
0.9.0-rc1

**To Reproduce**
1. Manually upgrade electrs to latest version (using latest git tag, manually build with `cargo build --locked --release` and cp binary to destination
2. `sudo systemctl restart electrs` 
2. Wait
3. See error with `sudo journalctl -f -u electrs`

**Expected behavior**
Reindexing is supposed to run through.

**Configuration**
electrs.conf
```
# Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/mnt/ext/bitcoin"
cookie_file = "/mnt/ext/bitcoin/.cookie"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"

# Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/mnt/ext/electrs/db"
txid_limit = 1000

# Logging
verbose = 4
timestamp = true
rust_backtrace = 1
```
bitcoin.conf
```
# Bitcoin daemon
server=1
txindex=1
disablewallet=1
sysperms=1

# Network
listen=1
listenonion=1
proxy=127.0.0.1:9050
bind=127.0.0.1
whitelist=download@127.0.0.1

# Connections
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333

# Raspberry Pi optimizations
maxconnections=40
maxuploadtarget=5000
```

**System running electrs**
 - Deployment method: manual (based on https://stadicus.github.io/RaspiBolt/, modified following https://github.com/romanz/electrs/blob/master/doc/usage.md#upgrading)
 - Raspberry Pi OS Lite (32-bit)
 - Raspbian GNU/Linux 10 (buster)

**Electrum client**
not applicable

**Comment by romanz** [comment]
Many thanks for reporting this issue!
Could you please attach the electrs log?
If it's not shown, you can run electrs with higher verbosity using `RUST_LOG` environment variable:
```
export RUST_LOG=electrs=INFO
```

**Comment by romanz** [comment]
Also, does it reproduce on regtest/signet (which are much smaller than mainnet)?

**Comment by romanz** [comment]
@AaronDewes Have you by chance encountered this issue?

**Comment by AaronDewes** [comment]
No, I haven't seen it, but I only use 64bit builds (arm64) in Docker.

**Comment by romanz** [comment]
Pinging more 32-bit RPi users: @sangaman @xanoni @unruhschuh

**Comment by romanz** [comment]
Seems that the panic (`slice index starts at 5 but ends at 4`) happens in the `Script::bytes_to_asm_fmt` method:
https://github.com/rust-bitcoin/rust-bitcoin/blob/5098011416d3b1895ab84109fbc50b0eda3ab7c0/src/blockdata/script.rs#L531
```rust
for ch in &script[index..index + data_len] {
    write!(f, "{:02x}", ch)?;
}
```
IIUC, `data_len` has to be "-1" for this to happen :confused:

**Comment by romanz** [comment]
@dematerializer It seems that you are running with the most verbose log setting (`TRACE`):
```
verbose = 4
```
Could you try run with a lower one, e.g. `verbose = 2` (`INFO`)?

**Comment by dematerializer** [comment]
Thanks for the suggestion to lower the verbosity, I think this helped!

With `verbose = 4` in `electrs.conf`:
```
bitcoin@raspberrypi:~ $ RUST_BACKTRACE=1 electrs --conf /mnt/ext/electrs/electrs.conf >electrs-panic.log 2>&1
```
yields many lines of blocks printed out, e.g.
```
[2021-09-19T09:59:15.934Z TRACE electrs::p2p] recv: Block(Block { header: BlockHeader { version: 2, .........
```
ending with:
```
thread '<unnamed>' panicked at 'slice index starts at 5 but ends at 4', /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/bitcoin-0.27.0/src/blockdata/script.rs:531:32
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2758
  14: bitcoin::blockdata::script::Script::bytes_to_asm_fmt
  15: <&T as core::fmt::Debug>::fmt
  16: core::fmt::builders::DebugStruct::field::{{closure}}
             at src/libcore/fmt/builders.rs:154
  17: core::result::Result<T,E>::and_then
             at src/libcore/result.rs:729
  18: core::fmt::builders::DebugStruct::field
             at src/libcore/fmt/builders.rs:137
  19: <&T as core::fmt::Debug>::fmt
  20: core::fmt::builders::DebugInner::entry::{{closure}}
             at src/libcore/fmt/builders.rs:419
  21: core::result::Result<T,E>::and_then
             at src/libcore/result.rs:729
  22: core::fmt::builders::DebugInner::entry
             at src/libcore/fmt/builders.rs:405
  23: core::fmt::builders::DebugSet::entry
             at src/libcore/fmt/builders.rs:496
  24: <&T as core::fmt::Debug>::fmt
  25: core::fmt::builders::DebugStruct::field::{{closure}}
             at src/libcore/fmt/builders.rs:154
  26: core::result::Result<T,E>::and_then
             at src/libcore/result.rs:729
  27: core::fmt::builders::DebugStruct::field
             at src/libcore/fmt/builders.rs:137
  28: <&T as core::fmt::Debug>::fmt
  29: core::fmt::builders::DebugInner::entry::{{closure}}
             at src/libcore/fmt/builders.rs:419
  30: core::result::Result<T,E>::and_then
             at src/libcore/result.rs:729
  31: core::fmt::builders::DebugInner::entry
             at src/libcore/fmt/builders.rs:405
  32: core::fmt::builders::DebugSet::entry
             at src/libcore/fmt/builders.rs:496
  33: <&T as core::fmt::Debug>::fmt
  34: core::fmt::builders::DebugStruct::field::{{closure}}
             at src/libcore/fmt/builders.rs:154
  35: core::result::Result<T,E>::and_then
             at src/libcore/result.rs:729
  36: core::fmt::builders::DebugStruct::field
             at src/libcore/fmt/builders.rs:137
  37: <&T as core::fmt::Debug>::fmt
  38: core::fmt::builders::DebugTuple::field::{{closure}}
             at src/libcore/fmt/builders.rs:347
  39: core::result::Result<T,E>::and_then
             at src/libcore/result.rs:729
  40: core::fmt::builders::DebugTuple::field
             at src/libcore/fmt/builders.rs:334
  41: <bitcoin::network::message::NetworkMessage as core::fmt::Debug>::fmt
  42: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
  43: <core::fmt::Arguments as core::fmt::Display>::fmt
             at src/libcore/fmt/mod.rs:422
  44: <core::fmt::Arguments as core::fmt::Debug>::fmt
             at src/libcore/fmt/mod.rs:415
  45: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
  46: env_logger::fmt::Builder::build::{{closure}}
  47: <env_logger::Logger as log::Log>::log::{{closure}}
  48: <env_logger::Logger as log::Log>::log
  49: log::__private_api_log
  50: electrs::p2p::Connection::recv
  51: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  52: rayon_core::scope::ScopeBase::complete
  53: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  54: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  55: rayon_core::registry::WorkerThread::wait_until_cold
  56: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-09-19T09:59:16.498Z INFO  electrs::db] closing DB at /mnt/ext/electrs/db/bitcoin
```
With `verbose = 2` in `electrs.conf`:
```
bitcoin@raspberrypi:~ $ RUST_BACKTRACE=1 electrs --conf /mnt/ext/electrs/electrs.conf >electrs-ok.log 2>&1
```
yields:
```
Config { network: Bitcoin, db_path: "/mnt/ext/electrs/db/bitcoin", daemon_dir: "/mnt/ext/bitcoin", daemon_auth: CookieFile("/mnt/ext/bitcoin/.cookie"), daemon_rpc_addr: V4(127.0.0.1:8332), daemon_p2p_addr: V4(127.0.0.1:8333), electrum_rpc_addr: V4(127.0.0.1:50001), monitoring_addr: V4(127.0.0.1:4224), wait_duration: 10s, index_batch_size: 10, index_lookup_limit: Some(200), auto_reindex: true, ignore_mempool: false, sync_once: false, server_banner: "Welcome to electrs 0.9.0-rc1 (Electrum Rust Server)!", args: [] }
[2021-09-19T10:01:57.781Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2021-09-19T10:01:57.871Z INFO  electrs::db] "/mnt/ext/electrs/db/bitcoin": 1245 SST files, 1.738909187 GB, 0.138772966 Grows
[2021-09-19T10:02:00.026Z INFO  electrs::chain] loading 265450 headers, tip=000000000000000ae000f6cd888c9bf0f62616117dd531104d180e7425697411
[2021-09-19T10:02:02.185Z INFO  electrs::chain] chain updated: tip=000000000000000ae000f6cd888c9bf0f62616117dd531104d180e7425697411, height=265450
[2021-09-19T10:02:02.223Z INFO  electrs::index] indexing 2000 blocks: [265451..267450]
```
and continues to run without any error.

**Comment by romanz** [comment]
Many thanks!

```
  50: electrs::p2p::Connection::recv
```
It seems that [our logging](https://github.com/romanz/electrs/blob/a53048f2ef72fc0cef137ef3c589dc6077aafd86/src/p2p.rs#L65) causes `rust-bitcoin` to "debug print" a specific block, which probably causes the panic above.
I'll try to reproduce it locally.

**Comment by romanz** [comment]
In case the underlying block storage device was corrupted, bitcoin `p2p` protocol will serve the wrong bytes since there is no verification of the block data here:
https://github.com/bitcoin/bitcoin/blob/58e02395bad59359cc0210f2ab633d0a82827ba4/src/node/blockstorage.cpp#L413-L446
https://github.com/bitcoin/bitcoin/blob/58e02395bad59359cc0210f2ab633d0a82827ba4/src/net_processing.cpp#L1804-L1810
Could you please share the few last `[... TRACE electrs::p2p] recv: Block` log lines?
They may help us to find the offending block :)

**Comment by Kixunil** [comment]
> IIUC, `data_len` has to be "-1" for this to happen

Or `usize::MAX` so that it overflows. This would also explain why it only happens in case of 32-bit systems. I'm not sure how such script would ever get into the chain but I guess it could be in an output script (burning the coins in the process).

To confirm this we should test with debug assertions. @dematerializer could you modify `Cargo.toml` in `electrs` directory and add:

```toml
[profile.release]
debug-assertions = true
```

recompile and run again?

Although it'd still be nice to get exact transaction causing this so we can add it as a test case for `rust-bitcoin` in the future.

**Comment by dematerializer** [comment]
This is the full log: [electrs-panic.log](https://github.com/romanz/electrs/files/7191965/electrs-panic.log)

**Comment by Kixunil** [comment]
@romanz check my attempt at fixing in https://github.com/rust-bitcoin/rust-bitcoin/pull/658

I'm very confused by that test though.

**Comment by Kixunil** [comment]
Ah, shit, I see now. :)

**Comment by romanz** [comment]
@dematerializer IIUC, the "problematic" block is [000000000000000b7e48f88e86ceee3e97b4df7c139f5411d14735c1b3c36791](https://blockstream.info/block/000000000000000b7e48f88e86ceee3e97b4df7c139f5411d14735c1b3c36791), height=265458.
Could you please retrieve it using bitcoin-cli?
```
$ bitcoin-cli getblock 000000000000000b7e48f88e86ceee3e97b4df7c139f5411d14735c1b3c36791
```

**Comment by dematerializer** [comment]
Here comes the block: [block_265458.txt](https://github.com/romanz/electrs/files/7192022/block_265458.txt)
Do you still need me to rebuild and run electrs with debug assertions enabled?

**Comment by Kixunil** [comment]
> Do you still need me to rebuild and run electrs with debug assertions enabled?

I'm very confident it'd confirm my hypothesis and thus become a strong argument for my PR. :)
However, it'd require rebuild of whole `electrs` (long time), so if you don't want to do that you can try my fix - add to `Cargo.toml` this **instead of debug-assertions**

```toml
[patch.crates-io.bitcoin]
git = "https://github.com/Kixunil/rust-bitcoin/"
branch = "script-fmt-overflow-fix"
```

This will only rebuild `bitcoin` dependency and the binary, so should be significantly faster.

**Comment by romanz** [comment]
The block contents looks correct:
```
$ bitcoin-cli getblock 000000000000000b7e48f88e86ceee3e97b4df7c139f5411d14735c1b3c36791 0 | sha256sum 
3286900c88b2648048d89487621b5736737cbff7798946a541668475173bda3f  -
$ sha256sum block_265458.txt 
3286900c88b2648048d89487621b5736737cbff7798946a541668475173bda3f  block_265458.txt
```

**Comment by Kixunil** [comment]
I believe it's caused by transaction ebc9fa1196a59e192352d76c0f6e73167046b9d37b8302b6bb6968dfd279b767 - bitcoin-cli prints `[error]` for it's `scriptPubkey`

**Comment by romanz** [comment]
```
bitcoin-cli getrawtransaction ebc9fa1196a59e192352d76c0f6e73167046b9d37b8302b6bb6968dfd279b767 1 000000000000000b7e48f88e86ceee3e97b4df7c139f5411d14735c1b3c36791
{
  "in_active_chain": true,
  "txid": "ebc9fa1196a59e192352d76c0f6e73167046b9d37b8302b6bb6968dfd279b767",
  "hash": "ebc9fa1196a59e192352d76c0f6e73167046b9d37b8302b6bb6968dfd279b767",
  "version": 1,
  "size": 249,
  "vsize": 249,
  "weight": 996,
  "locktime": 0,
  "vin": [
    {
      "txid": "6d7ed9914625c73c0288694a6819196a27ef6c08f98e1270d975a8e65a3dc09a",
      "vout": 1,
      "scriptSig": {
        "asm": "30450221009d41dc793ba24e65f571473d40b299b6459087cea1509f0d381740b1ac863cb6022039c425906fcaf51b2b84d8092569fb3213de43abaff2180e2a799d4fcb4dd0aa[ALL] 02d5ede09a8ae667d0f855ef90325e27f6ce35bbe60a1e6e87af7f5b3c652140fd",
        "hex": "4830450221009d41dc793ba24e65f571473d40b299b6459087cea1509f0d381740b1ac863cb6022039c425906fcaf51b2b84d8092569fb3213de43abaff2180e2a799d4fcb4dd0aa012102d5ede09a8ae667d0f855ef90325e27f6ce35bbe60a1e6e87af7f5b3c652140fd"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 0.00000001,
      "n": 0,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "01",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.00000001,
      "n": 1,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "0201",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.00000001,
      "n": 2,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "4c",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.00000001,
      "n": 3,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "4c0201",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.00000001,
      "n": 4,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "4d",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.00000001,
      "n": 5,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "4dffff01",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.00000001,
      "n": 6,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "4e",
        "type": "nonstandard"
      }
    },
    {
      "value": 0.00000001,
      "n": 7,
      "scriptPubKey": {
        "asm": "[error]",
        "hex": "4effffffff01",
        "type": "nonstandard"
      }
    }
  ],
  "hex": "01000000019ac03d5ae6a875d970128ef9086cef276a1919684a6988023cc7254691d97e6d010000006b4830450221009d41dc793ba24e65f571473d40b299b6459087cea1509f0d381740b1ac863cb6022039c425906fcaf51b2b84d8092569fb3213de43abaff2180e2a799d4fcb4dd0aa012102d5ede09a8ae667d0f855ef90325e27f6ce35bbe60a1e6e87af7f5b3c652140fdffffffff080100000000000000010101000000000000000202010100000000000000014c0100000000000000034c02010100000000000000014d0100000000000000044dffff010100000000000000014e0100000000000000064effffffff0100000000",
  "blockhash": "000000000000000b7e48f88e86ceee3e97b4df7c139f5411d14735c1b3c36791",
  "confirmations": 435799,
  "time": 1382508379,
  "blocktime": 1382508379
}
```

**Comment by romanz** [comment]
Debug formatting works on 64-bit machine:
```
Transaction { version: 1, lock_time: 0, input: [TxIn { previous_output: OutPoint { txid: 6d7ed9914625c73c0288694a6819196a27ef6c08f98e1270d975a8e65a3dc09a, vout: 1 }, script_sig: Script(OP_PUSHBYTES_72 30450221009d41dc793ba24e65f571473d40b299b6459087cea1509f0d381740b1ac863cb6022039c425906fcaf51b2b84d8092569fb3213de43abaff2180e2a799d4fcb4dd0aa01 OP_PUSHBYTES_33 02d5ede09a8ae667d0f855ef90325e27f6ce35bbe60a1e6e87af7f5b3c652140fd), sequence: 4294967295, witness: [] }], output: [TxOut { value: 1, script_pubkey: Script(OP_PUSHBYTES_1 <push past end>) }, TxOut { value: 1, script_pubkey: Script(OP_PUSHBYTES_2 <push past end>) }, TxOut { value: 1, script_pubkey: Script(<unexpected end>) }, TxOut { value: 1, script_pubkey: Script( OP_PUSHDATA1 <push past end>) }, TxOut { value: 1, script_pubkey: Script(<unexpected end>) }, TxOut { value: 1, script_pubkey: Script( OP_PUSHDATA2 <push past end>) }, TxOut { value: 1, script_pubkey: Script(<unexpected end>) }, TxOut { value: 1, script_pubkey: Script( OP_PUSHDATA4 <push past end>) }] }
```

**Comment by dematerializer** [comment]
@Kixunil

> I'm very confident it'd confirm my hypothesis and thus become a strong argument for my PR. :)
> However, it'd require rebuild of whole `electrs` (long time)

I rebuilt electrs with debug assertions enabled, did not take that long. Now here's the output of the re-run: [electrs-panic-with-assertions.log](https://github.com/romanz/electrs/files/7192093/electrs-panic-with-assertions.log)

> However, it'd require rebuild of whole electrs (long time), so if you don't want to do that you can try my fix - add to Cargo.toml this instead of debug-assertions

And here is the result of the re-run of electrs built with your patch: it creates massive debug output but does not seem to fail.

**Comment by Kixunil** [comment]
@romanz indeed, if you look at those outputs it seems like someone was testing weird edge cases, the last one contains a large push: `4effffffff01`, ffffffff is `usize::MAX` on 32-bit machines, so 64 bits will correctly compute `index + data_let` and then reject it because of it being too long while on 32 bits it overflows and causes it to be computed as `index - 1` which is not detected as longer than script leading to a panic later.

Thank God this was not C code, would be an ugly vulnerability.

@dematerializer that's weird the panic message doesn't confirm overflow but the fix works anyway. Did cargo write `Compiling bitcoin` when you recompiled?

**Comment by dematerializer** [comment]
@Kixunil 
> @dematerializer that's weird the panic message doesn't confirm overflow but the fix works anyway. Did cargo write `Compiling bitcoin` when you recompiled?

Unfortunately I'm not able to remember that and I cannot retrieve the old output either when I built with assertions enabled. I did not specifically recompile, just did it with `cargo build --locked --release` after modifying `Cargo.toml`. Should I have done it differently?

**Comment by Kixunil** [comment]
No worries, I'm going to test it differently anyway - by adding a test case into `rust-bitcoin` library and compiling/running for 32-bit architecture. This will be useful to avoid regressions.

The test case is:

```rust
assert_eq!(hex_script!("4effffffff01").asm(), " OP_PUSHDATA4 <push past end>");
```

Added to the script fmt tests.

**Comment by Kixunil** [comment]
Yep, the test fails in case of version before my fix and passes after my fix. I'm now certain my fix is correct. :)

**Comment by Kixunil** [comment]
FTR I just realized why `debug-assertions` didn't help. Overflow checking actually uses a different option to set it: `overflow-checks = true`. @dematerializer if you happen to enjoy recompiling you can try it but I don't see a good reason to think it was something else at this point. :)

**Comment by romanz** [comment]
https://github.com/romanz/electrs/commit/52dd59c117f7a8c06fdb7f023146bcd9f6d40b5c should resolve this issue (at least until https://github.com/rust-bitcoin/rust-bitcoin/pull/658 is merged and a new `rust-bitcoin` version is released).
Many thanks to @Kixunil and @dematerializer for debugging and fixing this issue!

**Comment by Kixunil** [comment]
Good to have a workaround prepared, maybe wait a bit and see if we can get point release of `bitcoin` and use that instead?

**Comment by romanz** [comment]
Sounds good, I plan to do another RC in a ~week :)

**Comment by xanoni** [comment]
Oof... saw the ping, all good here?

**Comment by romanz** [comment]
Yes :)
The bug was in `rust-bitcoin` Debug formatting of non-standard scripts: https://github.com/romanz/electrs/issues/490#issuecomment-922496191

**Comment by Kixunil** [comment]
To add, it's not a huge issue, just don't trace on 32 bit architectures and you're fine.
