### ISSUE TITLE
Bug: initial sync do not support graceful exit using SIGINT

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#494]
**Describe the bug**
Since initial sync doesn't use [WAL](https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log) when writing to rocksdb (for performance reasons) and signal handlers are registered after the initial sync is over, sending a SIGINT/SIGTERM results in an empty index DB.
Therefore, interrupting the initial sync will require a full resync (from genesis block).

**Electrs version**
0.9.0-rc1

**Expected behavior**
We should resume from the last block indexed and successfully written to the DB.

**Comment by Kixunil** [comment]
0.10 milestone? This sounds like a pretty sad bug that may be reasonably fixed in 0.9. Is there some difficulty?

**Comment by romanz** [comment]
Good point - I'll try to do it this week :)

**Comment by romanz** [comment]
Should be fixed in 0.9.0-rc2 :)
