### ISSUE TITLE
Bug: Electrs 0.9.0-rc1 uses overall more storage than less when reindexing

### ISSUE THREAD

**Issue by dematerializer** [romanz/electrs#502]
Sorry for being late with this bug report, but reindexing a previously fully indexed electrs `0.8.x` db with `0.9.0-rc1` results in two `electrs/db` subdirectories: `electrs/db/mainnet` (~76GB) **and** `electrs/db/bitcoin` (~30GB).

```
admin@raspberrypi:~ $ du -h /mnt/ext/electrs/db
76G	/mnt/ext/electrs/db/mainnet
30G	/mnt/ext/electrs/db/bitcoin
106G	/mnt/ext/electrs/db
```

Is this normal behaviour? Because this is contrary to the release tweet stating that [Index DB uses ~60% less storage](https://twitter.com/roman_zeyde/status/1439173165163425792) but in the end it uses **more** storage overall. Maybe it should be mentioned in the [Upgrading section of the usage guide](https://github.com/romanz/electrs/blob/master/doc/usage.md#upgrading) to manually delete the old `electrs/db/mainnet` directory?

**Comment by dematerializer** [comment]
I already deleted the old `electrs/db` directory and indexed from scratch with `0.9.0-rc2`, so I would have a hard time reproducing this on my node again.

**Comment by romanz** [comment]
Many thanks for reporting this issue!
`mainnet` was the old name for the DB directory in 0.8.x releases.
It was indeed changed in 0.9 - and I forgot to update the release notes :)

**Comment by romanz** [comment]
It should be safe to delete the old `db/mainnet` directory after upgrading to 0.9.x release.
