### ISSUE TITLE
Config: "blockchain.scripthash.get_balance called for unsubscribed scripthash"

### ISSUE THREAD

**Issue by aitorjs** [romanz/electrs#508]
I'm calling to `blockchain.scripthash.get_balance` from netcat like this:

```bash
echo '{"jsonrpc": "2.0", "method": "blockchain.scripthash.get_balance", "params": ["93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1"], "id": 1}' | netcat 127.0.0.1 60001
```

I get the result but I get this warning in the console:

```bash
[2021-09-27T16:17:04.902Z WARN  electrs::electrum] blockchain.scripthash.get_balance called for unsubscribed scripthash: 93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1
```
[this line of code](https://github.com/romanz/electrs/blob/master/src/electrum.rs#L242)

If I call from javascript using netcat, I get the warning commented before and this error:
```bash
[2021-09-27T16:19:04.995Z ERROR electrs::server] 13: disconnecting due to failed to send response: "{\"id\":0,\"jsonrpc\":\"2.0\",\"result\":{\"confirmed\":0,\"unconfirmed\":0}}\n"
```
so client data event is never called and I dont get the answer.

The javascript code I'm using to call `blockchain.scripthash.get_balance` runs ok on [this](https://github.com/romanz/electrs/commit/5854b20811044b1dd84dc32eaef7b0b0a642dbc6) commit.

I try to subscribe to scripthash 93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1 like this:

```bash
$ echo '{"jsonrpc": "2.0", "method": "blockchain.scripthash.subscribe", "params": ["93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1"], "id": 1}' | netcat 127.0.0.1 60001

> {"id":1,"jsonrpc":"2.0","result":"f7dd2df65f0eb38f413b46c242a9b11da184aada073d797fde3ce32fb33f107e"}
```

I try netcat to get_balance but I still get the warning. 

¿What I'm missing? 
Thanks! :)

**Comment by Kixunil** [comment]
Hi, could you please fill the issue template? We are missing crucial information such as *electrs version* which is required to investigate.

**Comment by romanz** [comment]
Many thanks for reporting this issue!
electrs is using subscriptions to cache the status of each scripthash per JSON RPC connection.
So I suggest sending both the subscription and the "get_balance" request from the same connection:
```
$ cat requests.txt 
{"jsonrpc": "2.0", "method": "blockchain.scripthash.subscribe", "params": ["93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1"], "id": 1}
{"jsonrpc": "2.0", "method": "blockchain.scripthash.get_balance", "params": ["93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1"], "id": 2}
$ netcat localhost 60001 < requests.txt 
{"id":1,"jsonrpc":"2.0","result":"f7dd2df65f0eb38f413b46c242a9b11da184aada073d797fde3ce32fb33f107e"}
{"id":2,"jsonrpc":"2.0","result":{"confirmed":0,"unconfirmed":0}}
```

**Comment by aitorjs** [comment]
I try. Thanks!

I'll see too if subscribing to the hash script using javascript as a client, it responds with the data. 
I will tell you! :)

**Comment by aitorjs** [comment]
I tried the solution proposed. The warning dissapear but calling get_balance from javascriptthe warning doesnt matter because before return the response the connection is closed with error: `ERROR electrs::server] 3: disconnecting due to failed to send response: "{\"id\":2,\"jsonrpc\":\"2.0\",\"result\":{\"confirmed\":0,\"unconfirmed\":0}}\n"

This is the nodejs code I'm using:

```js
/* For use:
- Nodejs installed. Tried on nodejs 14.15.0.
- cargo run --release --bin electrs -- -vv --daemon-dir /home/detailorg/.bitcoin --network testnet --db-dir /home/detailorg/.electrs/testnet3/db --electrum-rpc-addr 127.0.0.1:60001 --index-lookup-limit 20000
- npm install  node-netcat
- node electrs.js
*/
const Netcat = require('node-netcat');
const client = new Netcat.client("60001", "localhost");
// tb1qtc30sjwymczkzj6tszautpeflemyhudmpv2w7m
const scriptHash = "890e72c3b00f21691f1859e8e30a27646fd7f46fe5b2265cc8ade212c92f417c";

client.start();

client.once('open', () => {
  console.log("open");
  client.send(`{ "jsonrpc": "2.0", "id": 2, "method": "blockchain.scripthash.get_balance", "params": ["${scriptHash}"] }`, true);
});

client.on('data', data => {
  console.log("Never get here", data);
});

client.on('error', data => {
  console.log("Error", data);
});

client.on('close', data => {
  console.log("close", data);
});

```

Result:
```bash
$ node electrs.js
> open
> close
```

¿Why could the connection is closed before return the response?
Thanks! :)
`

**Comment by romanz** [comment]
I am not familiar with `node-netcat`, but I can suggest using a plain TCP socket for sending and receiving JSON RPCs:
```python
import socket
import sys

s = socket.create_connection(('localhost', 60001))
r = s.makefile('r')  # used to read responses line-by-line

s.sendall(b'{"jsonrpc": "2.0", "method": "blockchain.scripthash.subscribe", "params": ["93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1"], "id": 1}\n')
sys.stdout.write(r.readline())

s.sendall(b'{"jsonrpc": "2.0", "method": "blockchain.scripthash.get_balance", "params": ["93df2ed6d3031610206a9ef6ee5d7c2bc538d6689ffb5ce964144b2b90bdc9e1"], "id": 2}\n')
sys.stdout.write(r.readline())
```

**Comment by romanz** [comment]
Also, you can consider using https://github.com/ZenGo-X/node-electrum-client...

**Comment by romanz** [comment]
Looking at it, we shouldn't shutdown both read and write sides of the socket here:
https://github.com/romanz/electrs/blob/6fff80e9afe6cea2fd9d904fd9863518cfdefee5/src/server.rs#L199
Please try the following branch:
https://github.com/romanz/electrs/compare/fix-shutdown

**Comment by romanz** [comment]
@aitorjs The bug should be now fixed in `master`, thanks again for the report!
