### ISSUE TITLE
Bug: Wrong documentation of `--no-default-features`

### ISSUE THREAD

**Issue by erikarvstedt** [romanz/electrs#517]
[usage.md#dynamic-linking](https://github.com/romanz/electrs/blob/34a8549d2e436c52a394e4c35169c9b5efc65fe9/doc/usage.md#dynamic-linking) recommends to enable dynamic linking with `--no-default-features` and states that  `--no-default-features [is] only related to rocksdb linking`. 
But in version 0.9.0 this also disables the `metrics` feature. How does one enable both dynamic linking and `metrics`?

**Comment by Kixunil** [comment]
Ah, I had this thought in mind that we forgot something - this was it.

`--no-default-features --features=metrics` should work.

**Comment by Kixunil** [comment]
Actually, I think with new rocksdb no arguments are needed, just env vars. Will check.

**Comment by Kixunil** [comment]
Yep, works, going to make a PR.

**Comment by erikarvstedt** [comment]
Building with `ROCKSDB_INCLUDE_DIR` and `ROCKSDB_LIB_DIR` and without `--no-default-features` does indeed enable dynamic linking (check with`ldd`) but the binary size increases from `4.7M` to `7M`.

**Comment by Kixunil** [comment]
Sure, those 2.3M is prometheus code.

**Comment by erikarvstedt** [comment]
Yeah, right, sorry.
Thanks for the fix!
