### ISSUE TITLE
Compiling: error[E0308]: mismatched types

### ISSUE THREAD

**Issue by duckartes** [romanz/electrs#52]
> error[E0308]: mismatched types
>    --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/sysconf-0.3.3/src/page/hugepage.rs:346:23
>     |
> 346 |     if unsafe { lstat(path.as_ptr() as *const i8, &mut s) } < 0 {
>     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected u8, found i8
>     |
>     = note: expected type `*const u8`
>                found type `*const i8`
> 
> error: aborting due to previous error
> 
> For more information about this error, try `rustc --explain E0308`.
> error: Could not compile `sysconf`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
>

**Comment by romanz** [comment]
Sorry for the delayed response...

**Comment by romanz** [comment]
Could you please attach your `rustc` version?
```
$ rustc --version
```

**Comment by romanz** [comment]
AFAIU, this issue should be fixed by https://github.com/ZeroCostGoods/sysconf.rs/pull/18.

**Comment by romanz** [comment]
Many thanks for the quick merge, @gmjosack !
Could you please let me know when the new version will be published on https://crates.io/crates/sysconf?

**Comment by gmjosack** [comment]
Up now https://crates.io/crates/sysconf/0.3.4

**Comment by romanz** [comment]
Thanks a lot, the issue should be fixed at https://github.com/romanz/electrs/commit/6af64b6106e5f24a7a05293beb43580ffc0f45d5 :)
