### ISSUE TITLE
Bug: electrs v0.9.0 exits with error on powerpc64le-linux-gnu

### ISSUE THREAD

**Issue by flatcloud0b3** [romanz/electrs#520]
First off all, congratulation on the v0.9.0 release & thanks for the great work :D

**Describe the bug**

Been compiling and running Electrs as part of the [Power-Dojo](https://github.com/flatcloud0b3/power-dojo/blob/main/doc/DOCKER_setup.md#architecture) stack, before the v0.9.0 release, on powerpc64le & Debian (buster & bullseye). 

v0.8.* worked fine with the startup script used by Power-Dojo :

```
#!/bin/bash
set -e

indexer_options=(
  -vvvv
  --index-batch-size="$INDEXER_BATCH_SIZE"
  --jsonrpc-import
  --db-dir="/home/indexer/db"
  --electrum-rpc-addr="$NET_DOJO_INDEXER_IPV4:50001"
  --daemon-rpc-addr="$BITCOIND_IP:$BITCOIND_RPC_PORT"
  --txid-limit="$INDEXER_TXID_LIMIT"
  --blocktxids-cache-size-mb="$INDEXER_BLK_TXIDS_CACHE_SIZE_MB"
)

if [ "$COMMON_BTC_NETWORK" == "testnet" ]; then
  bitcoind_options+=(--network="testnet")
else
  bitcoind_options+=(--network="mainnet")
fi

electrs "${indexer_options[@]}"
```

After upgrading to v0.9.0 it doesnt recognize `--blocktxids-cache-size-mb`, `--txid-limit` & `--jsonrpc-import`

If i comment these options out it manages to start but fails with this error :

    indexer      | [2021-09-30T13:59:44.036Z INFO  electrs::db] "/home/indexer/db/bitcoin": 10 SST files, 0.00000805 GB, 0.00000001 Grows
    indexer      | [2021-09-30T13:59:44.036Z DEBUG electrs::db] DB Some(Config { compacted: false, format: 0 })
    indexer      | [2021-09-30T13:59:44.050Z DEBUG bitcoincore_rpc::client] JSON-RPC request: getblockchaininfo []
    indexer      | [2021-09-30T13:59:44.051Z DEBUG bitcoincore_rpc::client] JSON-RPC request: getnetworkinfo []
    indexer      | [2021-09-30T13:59:44.052Z DEBUG bitcoincore_rpc::client] JSON-RPC request: getblockchaininfo []
    indexer      | [2021-09-30T13:59:44.053Z INFO  electrs::db] closing DB at /home/indexer/db/bitcoin
    indexer      | Error: bitcoin p2p failed to connect: 127.0.0.1:8333
    indexer      | 
    indexer      | Caused by:
    indexer      |     Connection refused (os error 111)

It tries to connect to localhost like so : `127.0.0.1:8333` - but bitcoind ip addr is `172.28.1.5`. With the previous versions, this was not an issue & I am not sure why it is doing so. 

**Electrs version**
v0.9.0

**To Reproduce**
Compile electrs v0.9.0 on a ppc64le machine and run it as part of a dojo stack with the startup script as above.

**Expected behavior**
Expected it to run fine like it did with the v0.8.* releases

**OS Info**
    Headless Server running Debian Bullseye, Linux 4.19.0-17-powerpc64le #1 SMP Debian 4.19.194-3 (2021-07-18) ppc64le GNU/Linux

**Comment by Kixunil** [comment]
Please read the release notes/upgrade instruction. It is true that they don't mention switches being removed, which should be fixed but apparently you didn't configure bitcoind address (which also isn't entirely clear in instructions but should be at least a hint?)

**Comment by flatcloud0b3** [comment]
thank you for the clarification of the upgrade procedure. Saw the tweet and decided to upgrade. got it working, thanks again.

**Comment by Kixunil** [comment]
I suspected so. @romanz perhaps another tweet about making sure to read upgrade guide? :)

**Comment by flatcloud0b3** [comment]
one question : We also use Bitcoin P2P protocol instead of reading blocks from disk or JSON RPC

why this swap? is it performance related? or resource usage related?

**Comment by Kixunil** [comment]
P2P is significantly faster than RPC and directly reading from disk is way too reckless (if Core changes file format we would be screwed).

**Comment by romanz** [comment]
> I suspected so. @romanz perhaps another tweet about making sure to read upgrade guide? :)

https://twitter.com/roman_zeyde/status/1443625216295452674 :)
