### ISSUE TITLE
Suggestion: Consider future use of `waitfornewblock`

### ISSUE THREAD

**Issue by erikarvstedt** [romanz/electrs#522]
Since version 0.9.0, electrs uses the `waitfornewblock` RPC fn (via [rust-bitcoincore-rpc](https://github.com/rust-bitcoin/rust-bitcoincore-rpc) method `wait_for_new_block`) which is marked as hidden and reserved for testing. It was once [consided for removal](https://github.com/bitcoin/bitcoin/pull/10519).

This might brake deployments that use RPC whitelists which only include public calls.
The implementation might also have robustness issues as mentioned [here](https://github.com/bitcoin/bitcoin/pull/10519#issuecomment-323094194).

Electrs should or either stop using this fn or lobby to make it public. Nicolas Dorier is also [very interested](https://github.com/bitcoin/bitcoin/pull/10519#issuecomment-371250615) in using it for btcpayserver.

**Comment by Kixunil** [comment]
Thanks for heads up! That seems to make three projects using them. Would like to look into making them public.

**Comment by romanz** [comment]
Maybe we can use p2p inv messages (announcing new blocks) instead of relying on a hidden RPC.
Please take a look at https://github.com/romanz/electrs/compare/p2p-waitfornewblock :)

**Comment by Kixunil** [comment]
If I understand the code correctly two things (receiver loop and block reader) may attempt to read from same connection at the same time leading to lost or corrupt messages. I'd also like to see `Option<Sender<()>>` without `Option`.

Will try to think of a safer design.

**Comment by Kixunil** [comment]
Oh, it looks like it creates another connection? That would fix sync issue but it looks like bitcoind doesn't like too many connections...

**Comment by romanz** [comment]
> Oh, it looks like it creates another connection?

Yes - it was the simplest fix :)

> but it looks like bitcoind doesn't like too many connections...

I agree, we should reuse the same p2p connection for both getting headers/block data and notifications.

**Comment by romanz** [comment]
Should be resolved in `master`.
