### ISSUE TITLE
Batching supported for get_balance and other methods  ?

### ISSUE THREAD

**Issue by iangregsondev** [romanz/electrs#524]
Hi,

Is batching supported ? I was looking at the code and I saw some commits but i wasn't sure if its ready.

I normally use the API protocol methods an electrumx for my docs but these would be non-standard calls right ?

Do you have a list of the API calls - new ones that support batches ? or anything else that's not in the standard 1.4 spec ?

For example, i have a wallet and this wallet can contain multiple pub / priv keys - and i wish to get the full balance of everything for that wallet. So calling something like this 

get_balance

but multiple times, it would be handy if batching is available.

Thanks for any help

**Comment by romanz** [comment]
0.9.0 release support JSON RPC batching - see here for an example:
https://github.com/romanz/electrs/blob/2bc61b73d0942e21573a5257e2d5589f8e3d65c7/contrib/history.py#L66-L69
