### ISSUE TITLE
Bug: Electrs 0.9.0 won't start with "p2p failed to recv"

### ISSUE THREAD

**Issue by danyR85** [romanz/electrs#525]
**Describe the bug**
After upgrading to electrs v0.9 (from 0.8.11) electrs won't start. excerpt from the log:

```
Oct 02 07:33:59 sang-drax electrs[32393]: [2021-10-02T04:33:59.425Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Oct 02 07:34:00 sang-drax electrs[32393]: [2021-10-02T04:34:00.268Z INFO  electrs::db] "/mnt/ext/electrs/db/bitcoin": 185 SST files, 0.000148925 GB, 0.000000021 Grows
Oct 02 07:34:30 sang-drax electrs[32393]: [2021-10-02T04:34:30.444Z INFO  electrs::db] closing DB at /mnt/ext/electrs/db/bitcoin
Oct 02 07:34:30 sang-drax electrs[32393]: Error: failed to get headers
Oct 02 07:34:30 sang-drax electrs[32393]: Caused by:
Oct 02 07:34:30 sang-drax electrs[32393]:     0: p2p failed to recv
Oct 02 07:34:30 sang-drax electrs[32393]:     1: I/O error: unexpected end of file
Oct 02 07:34:30 sang-drax systemd[1]: electrs.service: Main process exited, code=exited, status=1/FAILURE
Oct 02 07:34:30 sang-drax systemd[1]: electrs.service: Failed with result 'exit-code'.
```

**Additional context**
I see a similar issue was encountered by @openoms in [issue #2548 raspiblitz](https://github.com/rootzoll/raspiblitz/issues/2548)

I changed bitcoin.conf accordingly but it didn't seem to help:

excerpt from bitcoin.conf:

```
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
maxconnections=40
maxuploadtarget=5000


#electrs 0.9.0 setting
whitelist=download@127.0.0.1`
```

**Electrs version**
elects v0.9.0

**To Reproduce**
1. sudo systemctl start electrs
2. sudo journalctl -f -u electrs
4. See above error

**Expected behavior**
electrs finishes startup and begin reindex process

**Configuration**

<details>
<summary>electrs.toml</summary>
```

```
network = "bitcoin"
daemon_dir= "/mnt/ext/bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8332"

electrum-rpc-addr = "127.0.0.1:50001"
db_dir = "/mnt/ext/electrs/db"
index_lookup_limit = 1000

verbose = 2
timestamp = true
```
```

</details>

**System running electrs**
 - Deployment method: raspibolt guide - with adjustments to comments made by @romanz and @Kixunil 
 - OS name and version : Raspbian GNU/Linux 10 (buster) on RPi4

**Electrum client**
Electrum 4.1.5

**Comment by openoms** [comment]
try setting:
```
daemon_p2p_addr = "127.0.0.1:8332" 
```

to port 8333
```
daemon_p2p_addr = "127.0.0.1:8333" 
```

This is a communication error to Core,
```
 Error: failed to get headers
```

Not related to the issue mentioned.

**Comment by danyR85** [comment]
It worked, Thanks!

* Currently indexing, Should I close?

**Comment by openoms** [comment]
Yes, since it is solved. Can remove the bug label too.

**Comment by danyR85** [comment]
typo in the electrs config, thanks to @openoms for finding it
