### ISSUE TITLE
Bug: Upgraded electrs 0.8.11 --> 0.9.0 and when start the core-dump

### ISSUE THREAD

**Issue by mariusb** [romanz/electrs#536]
**Describe the bug**
Have upgraded upgraded electrs from 0.8.11 to 0.9.0 and when starting via systecrl I get:
sudo systemctl status electrs.service 
● electrs.service - Electrs
     Loaded: loaded (/etc/systemd/system/electrs.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Wed 2021-10-06 13:08:49 SAST; 5s ago
    Process: 169369 ExecStart=/home/marius/electrs/target/release/electrs --db-dir ./db --electrum-rpc-addr=0.0.0.0:50001 (code=dumped, signal=ILL)
   Main PID: 169369 (code=dumped, signal=ILL)

Oct 06 13:08:49 mbbtcnode systemd[1]: electrs.service: Failed with result 'core-dump'.

**Electrs version**
Latest: 0.9.0

**To Reproduce**
Upgraded using steps here:  https://github.com/romanz/electrs/blob/master/doc/usage.md

**Expected behavior**
Electrs to be running

**Configuration**

<details>
<summary>electrs.toml</summary>

```
type error message here
```

</details>

Environment variables: `ELECTRS_X=Y;...`
Arguments: `--foo`

**System running electrs**
 Linux running Ubuntu 20.04
bitcoin core v22
Rust version:  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Electrum client**
Client name (if not upstream desktop Electrum) and version:

**Additional context**

**Comment by romanz** [comment]
Many thanks for reporting this issue!
Could you please share the machine/device hardware spec?
Also, could you please run electrs from command-line and share the logs?

**Comment by romanz** [comment]
Not sure but https://github.com/romanz/electrs/issues/193 may be relevant.

**Comment by Kixunil** [comment]
Maybe also share core dump? Unless you're using `auth` there should be no private information.

**Comment by Kixunil** [comment]
Since you used systemd `journalctl --no-pager -u electrs` should be enough to get logs.

**Comment by mariusb** [comment]
From the above command:
Oct 06 13:45:16 mbbtcnode systemd[1]: Started Electrs.
Oct 06 13:45:16 mbbtcnode electrs[1616]: Config { network: Bitcoin, db_path: "./db/bitcoin", daemon_dir: "/home/marius/.bitcoin", daemon_auth: UserPass("marius", "<sensitive>"), daemon_rpc_addr: V4(127.0.0.1:8332), daemon_p2p_addr: V4(127.0.0.1:8333), electrum_rpc_addr: V4(0.0.0.0:50001), monitoring_addr: V4(127.0.0.1:4224), wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: Some(200), auto_reindex: true, ignore_mempool: false, sync_once: false, server_banner: "Welcome to electrs 0.9.0 (Electrum Rust Server)!", args: [] }
Oct 06 13:45:16 mbbtcnode systemd[1]: electrs.service: Main process exited, code=dumped, status=4/ILL
Oct 06 13:45:16 mbbtcnode systemd[1]: electrs.service: Failed with result 'core-dump'.

**Comment by mariusb** [comment]
Had a look at #193 , do you think downgrading rocksdb to 0.12.2 will help?

**Comment by Kixunil** [comment]
Did you compile with static or dynamic linking? You could try the other.

**Comment by mariusb** [comment]
Also tried with dynamic: ROCKSDB_INCLUDE_DIR=/usr/include ROCKSDB_LIB_DIR=/usr/lib cargo build --locked --release
and the same result:
● electrs.service - Electrs
     Loaded: loaded (/etc/systemd/system/electrs.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Wed 2021-10-06 16:49:32 SAST; 15s ago
    Process: 2429 ExecStart=/home/marius/electrs/target/release/electrs --db-dir ./db --electrum-rpc-addr=0.0.0.0:50001 (code=dumped, signal=ILL)
   Main PID: 2429 (code=dumped, signal=ILL)

Oct 06 16:49:32 mbbtcnode systemd[1]: electrs.service: Failed with result 'core-dump'.

**Comment by romanz** [comment]
Could you please try running using Docker on Debian 11, from `p2p-bullseye` branch?
```
$ docker run --rm -it debian:bullseye-slim /bin/bash
# apt git install cargo clang cmake build-essential librocksdb-dev
# git clone -b p2p-bullseye https://github.com/romanz/electrs && cd electrs/
# ROCKSDB_INCLUDE_DIR=/usr/include ROCKSDB_LIB_DIR=/usr/lib cargo build --locked --no-default-features --release
# ./target/release/electrs -vvv
```

**Comment by romanz** [comment]
Maybe we'll need to cherry-pick https://github.com/rust-rocksdb/rust-rocksdb/commit/81a9edea83473012378e808606cdd92c1212c076 into our RocksDB fork...

**Comment by romanz** [comment]
@mariusb Could you please run the following on your machine:
```
$ git clone https://github.com/romanz/rust-rocksdb/ -b 2021-09/electrs-build
$ cd rust-rocksdb && cargo test --release --all
```

**Comment by mariusb** [comment]
> If the above fails, could you please also run:
> 
> ```
> $ git clone https://github.com/rust-rocksdb/rust-rocksdb/
> $ cd rust-rocksdb && cargo test --release --all
> ```

And from the above:
   Compiling librocksdb-sys v6.20.3 (/home/marius/rust-rocksdb/librocksdb-sys)
error: failed to run custom build command for `librocksdb-sys v6.20.3 (/home/marius/rust-rocksdb/librocksdb-sys)`

Caused by:
  process didn't exit successfully: `/home/marius/rust-rocksdb/target/release/build/librocksdb-sys-52742987e5dc8597/build-script-build` (exit status: 101)
  --- stderr
  error: header 'rocksdb/include/rocksdb/c.h' does not exist.
  thread 'main' panicked at 'unable to generate rocksdb bindings: ()', librocksdb-sys/build.rs:44:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Kixunil** [comment]
I believe @romanz meant `apt-get` instead of `apt git` :)

**Comment by mariusb** [comment]
> You can try adding `--network host --volume $HOME/.bitcoin:/root/.bitcoin:ro` to the `docker run` invocation - to allow it to access the bitcoind cookie and connect to JSON RPC port.

Even with this suggestion it did not find bitcoin core - here is the command I used to start docker:
`sudo docker run --network host --volume /home/marius/.bitcoin:/root/.bitcoin:ro --rm -it debian:bullseye-slim /bin/bash`

Here is the final part of the docker output:
root@mbbtcnode:/electrs# ./target/release/electrs -vvv
Config { network: Bitcoin, db_path: "./db/bitcoin", daemon_dir: "/root/.bitcoin", daemon_auth: CookieFile("/root/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: Some(200), auto_reindex: true, ignore_mempool: false, sync_once: false, server_banner: "Welcome to electrs 0.9.0 (Electrum Rust Server)!", args: [] }
[2021-10-08T08:02:02.784Z DEBUG electrs::metrics::metrics_fake] metrics collection is disabled
[2021-10-08T08:02:04.624Z INFO  electrs::db] "./db/bitcoin": 0 SST files, 0 GB, 0 Grows
[2021-10-08T08:02:04.625Z DEBUG electrs::db] DB None
[2021-10-08T08:02:04.915Z INFO  electrs::db] closing DB at ./db/bitcoin
Error: electrs failed

Caused by:
    0: failed to open bitcoind cookie file: /root/.bitcoin/.cookie
    1: No such file or directory (os error 2)

**Comment by romanz** [comment]
It seems that your bitcoind cookie is not stored under `/home/marius/.bitcoin`.
Please update this path to the directory where bitcoind writes its RPC authentication cookie - bitcoind should log it on startup:
```
2021-10-09T06:39:49Z Generated RPC authentication cookie /home/user/.bitcoin/.cookie
```

**Comment by romanz** [comment]
I can suggest using the following `Dockerfile` for building an electrs image from `p2p-bullseye` branch:
```
FROM debian:bullseye-slim as base
RUN apt-get update -qqy
RUN apt-get install -qqy librocksdb-dev=6.11.4-3

### Electrum Rust Server ###
FROM base as electrs-build
RUN apt-get install -qqy cargo clang cmake build-essential

# Install electrs
WORKDIR /build/electrs
COPY . .
ENV ROCKSDB_INCLUDE_DIR=/usr/include
ENV ROCKSDB_LIB_DIR=/usr/lib
RUN cargo install --locked --path .

FROM base as result
# Copy the binaries
COPY --from=electrs-build /root/.cargo/bin/electrs /usr/bin/electrs

WORKDIR /
```
You can build an image and tag it using:
```
$ docker build . --rm -t electrs:latest
```
Them you can run it:
```
$ docker run --network host --volume $HOME/.bitcoin:/root/.bitcoin:ro --volume $PWD/db:/db --rm -t electrs:latest electrs -vv
```

**Comment by romanz** [comment]
> The reason why I do not have a cookie file is that I have rpcuser & rpcpassword in my bitcoin.conf file which I need to connect Specter wallet to my bitcoin core node.

Got it, thanks!
I can suggest using the `auth` configuration option to specify user & password - note that it work only from a configuration file (not commandline):
https://github.com/romanz/electrs/blob/master/doc/usage.md#electrs-configuration (see "Authentication" section).

**Comment by mariusb** [comment]
> can suggest using the `auth` configuration option to specify user & password - note that it work only from a configuration file (not commandline):

I do specify the rpcuser and rpcpassword in the config.toml file located in /home/marius/.electrs

I will see if I can get the docker image build, connect to my node and see what the results will be.  My docker knowledge is however very limited so it might take some time.  

Another option is to downgrade to a version that was working -- my previous working version was 0.8.11 .. not sure if there was any versions between that and 0.9.0

**Comment by romanz** [comment]
> I do specify the rpcuser and rpcpassword in the config.toml file located in /home/marius/.electrs

You can probably map `/home/marius/.electrs` into your container environment by adding the following argument:
```bash
$ docker run --network host \
  --volume $HOME/.bitcoin:/root/.bitcoin:ro \
  --volume $HOME/.electrs:/root/.electrs:ro \  # <-- to share config.toml with the container
  --volume $PWD/db:/db \
  --rm -t electrs:latest electrs -vv
```
cc: @lukechilds @Code1110 @janhn, the authors of Docker-related electrs PR :)

**Comment by mariusb** [comment]
> I can suggest using the following `Dockerfile` for building an electrs image from `p2p-bullseye` branch:
> 
> ```
> FROM debian:bullseye-slim as base
> RUN apt-get update -qqy
> RUN apt-get install -qqy librocksdb-dev=6.11.4-3
> 
> ### Electrum Rust Server ###
> FROM base as electrs-build
> RUN apt-get install -qqy cargo clang cmake build-essential
> 
> # Install electrs
> WORKDIR /build/electrs
> COPY . .
> ENV ROCKSDB_INCLUDE_DIR=/usr/include
> ENV ROCKSDB_LIB_DIR=/usr/lib
> RUN cargo install --locked --path .
> 
> FROM base as result
> # Copy the binaries
> COPY --from=electrs-build /root/.cargo/bin/electrs /usr/bin/electrs
> 
> WORKDIR /
> ```
> 
> You can build an image and tag it using:
> 
> ```
> $ docker build . --rm -t electrs:latest
> ```
> 
> Them you can run it:
> 
> ```
> $ docker run --network host --volume $HOME/.bitcoin:/root/.bitcoin:ro --volume $PWD/db:/db \
>   --rm -t electrs:latest electrs -vv
> ```

Sorry by mistake closed the issue

Hmm tried to build the docker from this and get the following error:
```
Removing intermediate container 4d7f0201eca8
 ---> 94bc5b867b5c
Step 6/13 : WORKDIR /build/electrs
 ---> Running in 7f32a5e2a6af
Removing intermediate container 7f32a5e2a6af
 ---> 8cb680e33808
Step 7/13 : COPY . .
 ---> 5cabeabbb425
Step 8/13 : ENV ROCKSDB_INCLUDE_DIR=/usr/include
 ---> Running in f69a33e45b65
Removing intermediate container f69a33e45b65
 ---> ea03f77d1ccd
Step 9/13 : ENV ROCKSDB_LIB_DIR=/usr/lib
 ---> Running in 5c2262eef57c
Removing intermediate container 5c2262eef57c
 ---> 4581f3159713
Step 10/13 : RUN cargo install --locked --path .
 ---> Running in b0ae756934ca
error: `/build/electrs` does not contain a Cargo.toml file. --path must point to a directory containing a Cargo.toml file.
The command '/bin/sh -c cargo install --locked --path .' returned a non-zero code: 101

```

**Comment by romanz** [comment]
Closing for now, since the original core dump issue seems to be "worked-around" :)

**Comment by mariusb** [comment]
Thanks @romanz, updated today to v0.9.2 and started electrs as a service.

Took about 9 hours to rebuild the db and it is running perfectly.

Thanks for resolving this issue.

**Comment by romanz** [comment]
Cool, happy it worked :)
