### ISSUE TITLE
0.9.0 Performance on rPi

### ISSUE THREAD

**Issue by Transisto** [romanz/electrs#539]
is 250 address lookup per minute normal?

public electrumX and blockstream esplora server takes about 3 seconds to lookup 1600 addresses vs 6.5 minutes for electrs.

So Electrs on a rPi is about 120 times slower than with public servers.

**Comment by Transisto** [comment]
![0 9 0](https://user-images.githubusercontent.com/388716/136496705-1d452e89-f0a5-43a9-b0de-179e11471a8d.gif)

**Comment by romanz** [comment]
Could you please reproduce the slowness issue on a testnet wallet (so you could share the xpub here) and attach a DEBUG log?

**Comment by romanz** [comment]
For example, you can use `all all all all all all all all all all all all` mnemonic with `m/44'/1'/0'` derivation - it results in the following testnet master key:
`tpubDDKn3FtHc74CaRrRbi1WFdJNaaenZkDWqq9NsEhcafnDZ4VuKeuLG2aKHm5SuwuLgAhRkkfHqcCxpnVNSrs5kJYZXwa6Ud431VnevzzzK3U`
It currently has 73 transactions (see attached JSON).
[electrum-history.json.gz](https://github.com/romanz/electrs/files/7309289/electrum-history.json.gz)

**Comment by romanz** [comment]
@Transisto BTW, could you please compare `0.8.*` performance to `0.9.0` one?

**Comment by Transisto** [comment]
> @Transisto BTW, could you please compare `0.8.*` performance to the `0.9.0` on your device?

I've tested on somewhat same hardware but 0.8 on umbrel instead of 0.9.0 on mynode,
![umbrel tor](https://user-images.githubusercontent.com/388716/136714982-79e26366-58d2-4263-9810-fae2020025e3.gif)

The connection is over Tor so maybe that's why it can't go all the way to 1600 address without restarting, 
But overall it's about 6x faster.  It did 1250 address lookup in 1min instead of 250

**Comment by Transisto** [comment]
I updated umbrel to 4.4 with electrs 0.9.0 and the speed became the exact same as on the 0.9.0 on mynode.

6 times slower than 0.8.11

**Comment by romanz** [comment]
Could you maybe test `xpub6BiVtCpG9fQPxnPmHXG8PhtzQdWC2Su4qWu6XW9tpWFYhxydCLJGrWBJZ5H6qTAHdPQ7pQhtpjiYZVZARo14qHiay2fvrX996oEP42u8wZy`?
It's generated from `all all all all all all all all all all all all` mnemonic with `m/44'/0'/0'` derivation (p2pkh script type).

**Comment by romanz** [comment]
You can also use https://blockstream.info/address/1BitcoinEaterAddressDontSendf59kuE (currently at ~400 transactions)

**Comment by romanz** [comment]
See https://github.com/romanz/electrs/issues/539#issuecomment-940229419 - most of the time is spent waiting for p2p blocks to be received and parsed :(

**Comment by romanz** [comment]
https://github.com/romanz/electrs/pull/550 has better performance :)
```
$ curl -s localhost:4224 | grep 'p2p_.*_sum'; echo ''; curl -s localhost:4224 | grep blockchain.scripthash.subscribe | tail -n 5
p2p_blocks_duration_sum{step="process"} 1.7307969639999996
p2p_blocks_duration_sum{step="request"} 0.0023362269999999993
p2p_blocks_duration_sum{step="response"} 3.7773380029999997
p2p_blocks_duration_sum{step="total"} 5.511748266999999
p2p_recv_duration_sum{step="parse_alert"} 0.000000742
p2p_recv_duration_sum{step="parse_block"} 1.155298684
p2p_recv_duration_sum{step="parse_headers"} 0.000014537000000000002
p2p_recv_duration_sum{step="parse_ping"} 0.00000015
p2p_recv_duration_sum{step="parse_verack"} 0.00000007
p2p_recv_duration_sum{step="parse_version"} 0.000002965
p2p_recv_duration_sum{step="recv"} 36.851074396999984
p2p_recv_duration_sum{step="wait"} 0.002211042000000002
p2p_recv_size_sum{message="alert"} 168
p2p_recv_size_sum{message="block"} 475522181
p2p_recv_size_sum{message="headers"} 13
p2p_recv_size_sum{message="ping"} 8
p2p_recv_size_sum{message="verack"} 0
p2p_recv_size_sum{message="version"} 103
p2p_send_duration_sum{step="send"} 0.01149267300000001
p2p_send_duration_sum{step="wait"} 37.997768204999986

rpc_duration_bucket{method="blockchain.scripthash.subscribe",le="5"} 348
rpc_duration_bucket{method="blockchain.scripthash.subscribe",le="10"} 348
rpc_duration_bucket{method="blockchain.scripthash.subscribe",le="+Inf"} 348
rpc_duration_sum{method="blockchain.scripthash.subscribe"} 7.556884960999998
rpc_duration_count{method="blockchain.scripthash.subscribe"} 348
```

**Comment by romanz** [comment]
https://github.com/romanz/electrs/pull/550 performance:
```
$ curl -s localhost:4224 | grep 'p2p_.*_sum'; echo ''; curl -s localhost:4224 | grep blockchain.scripthash.subscribe | tail -n 5
p2p_blocks_duration_sum{step="process"} 3.8600059359999994
p2p_blocks_duration_sum{step="request"} 0.001956654000000002
p2p_blocks_duration_sum{step="response"} 4.332786441999998
p2p_blocks_duration_sum{step="total"} 8.195770834000005
p2p_recv_duration_sum{step="parse_alert"} 0.000000711
p2p_recv_duration_sum{step="parse_block"} 1.2511216259999993
p2p_recv_duration_sum{step="parse_headers"} 0.000012413
p2p_recv_duration_sum{step="parse_ping"} 0.000000381
p2p_recv_duration_sum{step="parse_verack"} 0.000000562
p2p_recv_duration_sum{step="parse_version"} 0.000003426
p2p_recv_duration_sum{step="recv"} 26.222933034999997
p2p_recv_duration_sum{step="wait"} 0.002772557999999998
p2p_recv_size_sum{message="alert"} 168
p2p_recv_size_sum{message="block"} 475522181
p2p_recv_size_sum{message="headers"} 11
p2p_recv_size_sum{message="ping"} 8
p2p_recv_size_sum{message="verack"} 0
p2p_recv_size_sum{message="version"} 103
p2p_send_duration_sum{step="send"} 0.017353894000000012
p2p_send_duration_sum{step="wait"} 27.460560092999994

rpc_duration_bucket{method="blockchain.scripthash.subscribe",le="5"} 348
rpc_duration_bucket{method="blockchain.scripthash.subscribe",le="10"} 348
rpc_duration_bucket{method="blockchain.scripthash.subscribe",le="+Inf"} 348
rpc_duration_sum{method="blockchain.scripthash.subscribe"} 10.033779470999992
rpc_duration_count{method="blockchain.scripthash.subscribe"} 348
```

**Comment by romanz** [comment]
It is released in `0.9.2`.

**Comment by romanz** [comment]
Closing for now, please reopen if the regression persists.

**Comment by Transisto** [comment]
about 280 addresses lookup per minutes, on 0.9.3, hardly any improvement
1600 addresses checked in 5.75 minutes

**Comment by romanz** [comment]
Could you please also check [`status-cache`](https://github.com/romanz/electrs/compare/status-cache) performance?

**Comment by Transisto** [comment]
> Could you please also check [`status-cache`](https://github.com/romanz/electrs/compare/status-cache) branch performance?

I'm not equipped to do that at the moment.
I can ask someone else running a node on a rPi

**Comment by Kixunil** [comment]
Maybe try with `--skipmerklecheck`?

**Comment by craigraw** [comment]
> Maybe try with --skipmerklecheck?

I thought this was now the default?

**Comment by romanz** [comment]
IIUC, electrum does verify the merkle proofs (by default):
https://github.com/spesmilo/electrum/blob/88a1c1a618062db0ad49ba3b98d6e47e9e80d5d9/electrum/commands.py#L1438

**Comment by Kixunil** [comment]
Yeah, I think @craigraw thought I meant to pass it into `electrs` but I actually meant to pass it to Electrum.

**Comment by Transisto** [comment]
I tested the newer version that's running on mynode, 0.9.3 and it does 400 address lookups per minutes.

That's still far from the 1250 it was doing on 0.8.9

**Comment by romanz** [comment]
FYI: https://www.sparrowwallet.com/docs/server-performance.html is a great benchmarking and discussion.

**Comment by Kixunil** [comment]
Heh, wanted to ping you regarding that article, I particularly agree with this:

> We can be relatively sure of two trends continuing into the next few years - wallet depths will increase, and storage costs will decrease. For this reason, it may make sense for current and future implementations to consider a larger, more inclusive index rather than a dependence on Bitcoin Core’s database for address-to-transaction lookups.

However I wouldn't like to store the whole chain twice.

Just got an interesting idea: build an external daemon for storing the chain that can be read from disk directly and make a dynamically linked library part of the API. This library will read things directly from disk and if there's ever any change in format the library will get updated together with the daemon. This bypasses communication but still is backwards-compatible. What do you think?

**Comment by craigraw** [comment]
> However I wouldn't like to store the whole chain twice.

Agreed - what would be more accurate is "rather than a dependence on Bitcoin Core’s database for _address-to-txid+height_ lookups". IMO it is critical to be able for a scalable address index to do this lookup internally. With this information one can construct a script hash status necessary for the `blockchain.scripthash.subscribe` method (called for all used addresses on wallet load), and the data necessary for the `blockchain.scripthash.get_history` method. The actual transaction can be fetched from Bitcoin Core, but by the much more efficient method of retrieving it via its txid rather than its block height. 

I do concede this requires more data storage, both for storing the txids and enabling `txindex` in Bitcoin Core. IMO the tradeoff is worth it.

**Comment by Transisto** [comment]
I don't see a problem in storing the chain twice if it mean more than one person can use the same node at once.

Current implementation performance makes it not sufficient for a single, moderately active, user.
