### ISSUE TITLE
Bug: "Disconnecting due to failed to send response: ..."

### ISSUE THREAD

**Issue by Transisto** [romanz/electrs#540]
`2: disconnecting due to failed to send response: "[{\"id\":\"m/1/0\",\"jsonrpc\":\"2.0\",\"result\":\"f0 ...
`
![image](https://user-images.githubusercontent.com/388716/136494732-a91451a0-28a9-4b3c-8342-14f89639e7ad.png)

The line that start with 0\",\"result\ is about 20 pages long when wrapped in a text editor.

**Comment by romanz** [comment]
It usually happen when the client gets disconnected while the server is trying to send a response.
