### ISSUE TITLE
Use separate crate for Bitcoin JSONRPC handling

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#57]
Use [rust-bitcoin-rpc](https://github.com/jeandudey/rust-bitcoin-rpc) or [rust-jsonrpc](https://github.com/apoelstra/rust-jsonrpc), instead of reimplementing Bitcoin JSONRPC.

**Comment by shesek** [comment]
Sorry, wrong `refs`! :)

**Comment by stevenroose** [comment]
Once we stabilize https://github.com/rust-bitcoin/rust-bitcoincore-rpc with a jsonrpc update, I might give this a shot :)

**Comment by romanz** [comment]
Thanks, much appreciated!

**Comment by romanz** [comment]
Forgot to resolve long time ago :)
