### ISSUE TITLE
Updating to Electrs 0.9.1: crashes while reindexing "receiving on an empty and disconnected channel"

### ISSUE THREAD

**Issue by got3nks** [romanz/electrs#582]
I recently updated a Raspberry node to use Electrs 0.9.1. It already crashed few times during the database upgrade with the following error (only the block hash is different).

```
Oct 20 17:07:49 ViresInNumeris electrs[18635]: Error: electrs failed
Oct 20 17:07:49 ViresInNumeris electrs[18635]: Caused by:
Oct 20 17:07:49 ViresInNumeris electrs[18635]:     0: sync failed
Oct 20 17:07:49 ViresInNumeris electrs[18635]:     1: failed to get block 00000000000002812446872f1d4ded709da88c68697efa3925014e6c67355507
Oct 20 17:07:49 ViresInNumeris electrs[18635]:     2: receiving on an empty and disconnected channel
```

What is it caused by and how to provent it from happening again?

**Comment by romanz** [comment]
Thanks for reporting this issue!
Could you please share your bitcoind configuration?

**Comment by romanz** [comment]
Please use `-whitelist=download@127.0.0.1` as described in https://github.com/romanz/electrs/blob/master/doc/usage.md#bitcoind-configuration

**Comment by Septem151** [comment]
> Please use `-whitelist=download@127.0.0.1` as described in https://github.com/romanz/electrs/blob/master/doc/usage.md#bitcoind-configuration

Just to let you know, there is no section for #bitcoind-configuration on that usage doc page.

**Comment by Kixunil** [comment]
We reorganized docs since then and it's now in https://github.com/romanz/electrs/blob/master/doc/config.md#bitcoind-configuration
