### ISSUE TITLE
Feature: Support or silently ignore Addr bitcoin messages

### ISSUE THREAD

**Issue by peterfigure** [romanz/electrs#596]
**Is your feature request related to a problem? Please describe.**
Logs filling up with warnings

**Describe the solution you'd like**
Implement support for the Addr bitcoin message type: https://en.bitcoin.it/wiki/Protocol_documentation#addr

**Describe alternatives you've considered**
Perhaps there's a way to turn off this advertising in bitcoind if it's of no relevance to electrs, though it might be to other services in a lightning node? 

**Additional context**
example log entry (payload altered):
```
WARN  electrs::p2p] unexpected message: Unknown { command: CommandString("addr"), payload: [1, 111, 200, 111, 97, 9, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 111, 198, 10, 111, 111, 141] }
```

**Comment by jblachly** [comment]
> Many thanks for reporting this issue! Should be fixed now in `master`.

I just built from master and am seeing this during initial indexing:

```
[2021-10-29T19:04:55.138Z INFO  electrs::index] indexing 2000 blocks: [184861..186860]
[2021-10-29T19:05:00.036Z WARN  electrs::p2p] unexpected message: Unknown { command: CommandString("addr"), payload: [redacted as not sure if this is secure] }
[2021-10-29T19:05:08.467Z INFO  electrs::chain] chain updated: tip=000000000000006915c714833ea3a9be99dbbbd31fe9a40ea06194ccaa7b02b2, height=186860
```

**Comment by romanz** [comment]
Thanks for the heads-up :)
Should be fixed by https://github.com/romanz/electrs/commit/44bc27d7ca23b5545fe95a53b5dc6b18d2843a56.
