### ISSUE TITLE
curl rpc request results in "parse error"

### ISSUE THREAD

**Issue by tiran133** [romanz/electrs#601]
Hello,

maybe I just missing something but i'm trying to use curl to query rpc

If I use netcat its working fine.
```
:/# echo '{"jsonrpc": "2.0", "method": "server.version", "params": ["", "1.4"], "id": 0}' | netcat 127.0.0.1 50001

{"id":0,"jsonrpc":"2.0","result":["electrs/0.9.1","1.4"]}
```

But wenn I use curl I always get the following "parse error" 7 times.

```
:/# curl --data '{"jsonrpc": "2.0", "method": "server.version", "params": ["", "1.4"], "id":0}' 127.0.0.1:50001

{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
{"error":{"code":-32700,"message":"parse error"},"id":null,"jsonrpc":"2.0"}
```
I also tried adding json header with -H 'Content-Type:application/json;' 

or making a post  request -X POST

It always results in the same "parse error"

What am I missing?

Appreciate your help. Thank you

**Comment by romanz** [comment]
Please use `netcat` instead of `curl`.

**Comment by tiran133** [comment]
Yes I saw that. 

I was trying to get it working in python and had already written some code to use with curl with bitcoin-core.

Anyway I did some more research and I use "aiorpcX" https://github.com/kyuupichan/aiorpcX  now wich works just fine.

Thanks again.

**Comment by chrisguida** [comment]
Curious, why does curl not work? Is it impossible for curl to communicate with electrs' jsonrpc api?
