### ISSUE TITLE
Use `gettxoutproof` RPC instead of reimplementing Merkle proof logic

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#613]
e.g. see [EPS implementation](https://github.com/chris-belcher/electrum-personal-server/blob/e2baad860a26b55cc879d523ba6dee84b50a45ec/electrumpersonalserver/server/merkleproof.py#L94).

It should probably be more efficient :)

**Comment by Kixunil** [comment]
I doubt that Core has proofs cached and if it doesn't I would expect the computation time to be same as electrs and it adds RPC overhead. But if you want to give it a shot and benchmark it go ahead. :)

**Comment by romanz** [comment]
The serialized format of `gettxoutproof` is non-trivial to parse correctly:
https://github.com/bitcoin/bitcoin/blob/3a36ec83d024a1343bee8e390833eb1fd7a3705d/src/merkleblock.h#L20-L53
https://github.com/bitcoin/bitcoin/blob/3a36ec83d024a1343bee8e390833eb1fd7a3705d/src/merkleblock.cpp#L67
Also, both imlementations need to read & parse the block, as well as compute all of its txids:
https://github.com/bitcoin/bitcoin/blob/3a36ec83d024a1343bee8e390833eb1fd7a3705d/src/rpc/rawtransaction.cpp#L298-L308
So indeed, we probably won't have a significant performance gain from switching to use `gettxoutproof`.
