### ISSUE TITLE
Regression: Curl is not contained in the docker image any more

### ISSUE THREAD

**Issue by schildbach** [romanz/electrs#617]
**Describe the bug**
0.9.1 had curl, 0.9.2 hasn't. This leads to Docker health checks failing.

Can we get it back?

**Comment by Kixunil** [comment]
If the problem is in Docker file it'll be probably fastest if you send a PR with what you want.

**Comment by schildbach** [comment]
Would you be open for including a standard docker health check? That would make my PR kind of complete (-:

**Comment by Kixunil** [comment]
I personally don't care as I don't use Docker. If it's standard then it's most likely a good idea to add it. I *guess* that @romanz will view it similarly but let's not assume things. :)

**Comment by romanz** [comment]
> I _guess_ that @romanz will view it similarly 

I do :)

**Comment by schildbach** [comment]
See #624

**Comment by Kixunil** [comment]
Should be closed now?
