### ISSUE TITLE
Prepare an "asciinema" screencast for a quickstart installation

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#619]
> Maybe we can use https://asciinema.org/ to prepare a short screencast that shows how to install and run electrs on a Linux machine? This way, beginner users will also have the commands' output available (which can help with troubleshooting).

_Originally posted by @romanz in https://github.com/romanz/electrs/issues/606#issuecomment-956156699_

**Comment by romanz** [comment]
@Kixunil @k3tan172 WDYT about https://asciinema.org/a/jrh0CqCnImvtIOnW7N4uachkR?

**Comment by romanz** [comment]
TIL that you can install https://asciinema.org client using `sudo apt install asciinema` :)

**Comment by Kixunil** [comment]
Could the waiting parts be sped up?

**Comment by romanz** [comment]
The `speed` option allows running it faster:
https://asciinema.org/a/jrh0CqCnImvtIOnW7N4uachkR?rows=30&speed=3

**Comment by romanz** [comment]
Manually starting electrs sync:
https://asciinema.org/a/kGPYuL75Ww3hi0pw3DOziv0DT?speed=3&cols=200
