### ISSUE TITLE
Introduce skip-list

### ISSUE THREAD

**Issue by prusnak** [romanz/electrs#635]
Currently there is an [`index_lookup_limit` setting](https://github.com/romanz/electrs/blob/cd348e72de9071549755170e9709ae922e023083/internal/config_specification.toml#L111-L115) which limits the size of transaction history for each indexed entry.

I think it would be better to implement a "skip-list" which would contain the list of popular addresses which will be skipped. That way we could still provide the full history for all entries (except the skipped ones) and resolve the DoS issue.

**Comment by Kixunil** [comment]
I think pagination would solve this issue more fundamentally but given that it's not speced yet I'd accept this workaround.

However, I wonder how much this limit even helps. `electrs` is assumed to **not** be publicly accessible, so someone can DoS their own server or it's a legit big request - just wait more. Maybe we should set it to unlimited by default?

**Comment by prusnak** [comment]
> I think pagination would solve this issue

Sure, pagination would be the best ...

> Maybe we should set it to unlimited by default?

That would be ideal in combination with what I am proposing - so people running public instances have an easy way how to not serve the results for popular addresses.

**Comment by Kixunil** [comment]
> people running public instances

I recommend those to run [Blockstream fork of electrs](https://github.com/Blockstream/electrs) which is optimized for public/big-scale server usage as opposed to this implementation which is optimized for personal usage.

**Comment by prusnak** [comment]
> which is optimized for public/big-scale server usage as opposed to this implementation which is optimized for personal usage

If that is the case, then I agree that the upstream (this repo) should set `index_lookup_limit` to unlimited by default. And maybe we could update the documentation that if you plan to run electrs as a service for public you should consider running the Blockstream fork.

**Comment by Kixunil** [comment]
Hmm, I'd swear we had this documented... Will do.

**Comment by romanz** [comment]
Opened #637.

**Comment by romanz** [comment]
> I think it would be better to implement a "skip-list" which would contain the list of popular addresses which will be skipped.

Would adding a comma-separated `--skip-addresses` config option would work?

**Comment by prusnak** [comment]
> Would adding a comma-separated `--skip-addresses` config option work?

I think so.

That said, I am perfectly OK with not implementing and closing this after https://github.com/romanz/electrs/pull/636 and https://github.com/romanz/electrs/pull/637 have been merged.

**Comment by romanz** [comment]
> That said, I am perfectly OK with not implementing and closing this after #636 and #637 have been merged.

Sounds good, let's keep it simple (for now) :)
