### ISSUE TITLE
Build: `Segmentation fault` right after `Updating crates.io index` on 64bit Pi4

### ISSUE THREAD

**Issue by asvdf** [romanz/electrs#648]
**Have you read the documentation?**
Yes. (Please, read usage.md first if you did not.)

**Did you double-check that you installed all dependencies?**
Yes. (Please, double check the dependencies if you didn't.)

**Which command failed?**
`cargo build --locked --release` (with or without `--no-default-features`)

**What was the error message?**

<details>
<summary>Error message</summary>

```
    Updating crates.io index
Segmentation fault

```

</details>

**System**
5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux
rustc version: rustc 1.41.1
cargo version: cargo 1.42.1

**Compilation**
Linking: static
Cross compilation: no
Target architecture: aarch64

**Aditional context**

Following Raspibolt v3, on which I didn't notice any differences from the build instructions on this repository; only peculiarity of my system, is that I disabled swap, as I am running a RAID1 on btrfs which does not support swap, but I have a 8GB board.
As per https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1830277.html I also spent time on configuration, and added
`git = "2.20.1"`
 in 
`~/rust/electrs/Cargo.toml`
and created `~/rust/electrs/.cargo/config.toml` as
```
[env]
CARGO_NET_GIT_FETCH_WITH_CLI = true
```
...still segmentation fault.

**Comment by asvdf** [comment]
I decided in the meantime to go the Personal Server way, as I don't have many wallets to manage, nor plan to be an Uncle Jim, nor intend to publish my server for others to use, but since I can't just delete this issue, and closing an issue which is fundamentally open, I leave to you the decision to delete/close it, or elaborate on it in case other users might need help on the same issue.

**Comment by Kixunil** [comment]
Yeah, known issue, not caused by electrs :(
Did you try setting env var directly? Do you have `git` installed?

Note that editing `Cargo.toml` will not help you at all.

It makes sense to me to close the issue (not our fault) but since people experience the problem it could lead to others opening it again.

**Comment by Kixunil** [comment]
Tried to reproduce, this fixes it for me: `CARGO_NET_GIT_FETCH_WITH_CLI=true cargo build` (or other `cargo` commands)

**Comment by asvdf** [comment]
Yes I have `git` installed, @Kixunil suggestion could probably let it build, and is promising as maybe my `config.toml` wasn't being picked up for whatever reason.
I accept the suggestion and close the issue, but still the suggestion above might very well be the one, thank you!
