### ISSUE TITLE
Use BIP158 filters to skip subscription syncing over new blocks

### ISSUE THREAD

**Issue by romanz** [romanz/electrs#655]
Following https://github.com/romanz/electrs/discussions/651

**Comment by romanz** [comment]
Unfortunately, BIP158 filter requires having the original script ([to be hashed using SipHash24](https://docs.rs/bitcoin/0.27.1/src/bitcoin/util/bip158.rs.html#421)) but the Electrum protocol provides us the a [scripthash](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-basics.html#script-hashes) i.e. SHA256(script).

**Comment by prusnak** [comment]
Ah, right. That is ... unfortunate. :-/
