### ISSUE TITLE
LTC support

### ISSUE THREAD

**Issue by TheSlackOne** [romanz/electrs#675]
**Is your feature request related to a problem? Please describe.**
ElectRS does not support Litecoin.

**Describe the solution you'd like**
Support Litecoin. I can help out with this if I can get a minimum support from the developers.

**Describe alternatives you've considered**
Get a working Litecoin indexer. 

**Additional context**
I already have ElectRS working for Bitcoin. I think it is fast and robust, I need a similar solution for Litecoin. I'm a developer (not a Rust one but I think I can do it anyway) and I think I could help out if you guys provide me some support.

What do you think, should I start with this?

**Comment by Kixunil** [comment]
I suggest you to get first into habit of [reading the documentation](https://github.com/romanz/electrs#altcoins) before you start to develop production cryptographic software.
