### ISSUE TITLE
Bug: running electrs fails due to "0: sync failed" "1: failed to get DB size" "2: No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by jblachly** [romanz/electrs#682]
**Describe the bug**
Periodically (days to weeks) electrs -- which otherwise runs normally -- crashes with the following (previous two normal appearing log lines included; crash time is not logged)

```
[2022-02-08T11:03:12.668Z INFO  electrs::index] indexing 1 blocks: [722323..722323]
[2022-02-08T11:03:12.783Z INFO  electrs::chain] chain updated: tip=000000000000000000053cc10a59e6ab46e971b16f7e70334accf89ca9339eca, height=722323
[2022-02-08T11:03:33.089Z INFO  electrs::db] closing DB at /home/ubuntu/db/bitcoin
Error: electrs failed

Caused by:
    0: sync failed
    1: failed to get DB size
    2: No such file or directory (os error 2)
```

**Electrs version**
This error has happened across multiple versions, including releases and non-releases. Most recently, I am on commit 04089ee6515302ea1c535723feb2ce69eafba590 (Jan 21 2022)

**To Reproduce**
1. Create LXC VM container for bitcoind 
2. Run bitcoind on VM
3. Create separate isolated LXC VM container for electrs
4. Configure electrs to point to bitcoind on private LAN
5. The only client accessing electrs is Sparrow
6. Wait days to weeks -- I have never caught electrs in the process of crashing (i.e., it may or may not be client-induced)

**Expected behavior**
Should not crash, or at a minimum, the crash log should be more diagnostic including a timestamp

**Configuration**

<details>
<summary>electrs.toml</summary>

```
# bitcoind rpc endpoint auth (since on different machine, no cookie)
auth="username:password"

# The listening RPC address of bitcoind, port is usually 8332
daemon_rpc_addr = "bitcoindvmhostname.local:8332"

# The listening P2P address of bitcoind, port is usually 8333
daemon_p2p_addr = "bitcoindvmhostname.local:8333"

# Directory where the index should be stored. It should have at least 70GB of free space.
db_dir = "/home/ubuntu/db"

electrum_rpc_addr = "0.0.0.0:50001"

# How much information about internal workings should electrs print. Increase before reporting a bug.
verbose = 2

# performance
# Number of blocks to get in a single p2p protocol request from bitcoind
# default: 10
index_batch_size = 100
```

</details>

Environment variables: none
Arguments: none

**System running electrs**

electrs built from source with cargo

```
$ uname -a
Linux electrs 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Electrum client**
Client name (if not upstream desktop Electrum) and version: Sparrow 1.5.6 (latest; but electrs has crashed in past also)

**Additional context**
VM type is LXC/LXD container

8 GB of free space (note this is on top of a full index)

Only non-default electrs setting is `index_batch_size`

I have subsequently increased verbosity to 3

**Comment by Kixunil** [comment]
Where the hell does that message come from?! I can't find it in `electrs` nor `rocksdb`.

**Comment by jblachly** [comment]
I assume the errors itself are unwound through `anyhow`, but I don't know what is supplying them to `anyhow`

**Comment by romanz** [comment]
@jblachly Does the issue reproduce?

**Comment by romanz** [comment]
I think that it may have caused by 632fe4c622a7f554e1922daa36599c5b762e796c - probably due to a compaction deleting some RocksDB SST files while trying to compute the DB size...

**Comment by jblachly** [comment]
@romanz 

I'm now running a later commit (bb382a6dcee193584a4495e64aa30eace645fee1) from Nov 2022 and everything appears stable for months.
