### ISSUE TITLE
How to compare electrs blockhash with bitcoind

### ISSUE THREAD

**Issue by prushin** [romanz/electrs#694]
Hi,

Electrs rpc method "blockchain.block.header" returns something like:  "000000301c2a4ab4e7adc60aa4fcc5e570dad5ad1a660ad0d5a65c3f6bb15477ecb123482836632c00f869a45b5cf2b0b3ba09bb884252212437922ed003083542404165b31d2762ffff7f2001000000" (80 bytes hex encoded)

Is it possible somehow to compare it with Bitcoind block hash which is 32 bytes hex encoded?

**Comment by Kixunil** [comment]
Of course, just hash it with sha256 twice. :)

Shell example:

```bash
echo 000000301c2a4ab4e7adc60aa4fcc5e570dad5ad1a660ad0d5a65c3f6bb15477ecb123482836632c00f869a45b5cf2b0b3ba09bb884252212437922ed003083542404165b31d2762ffff7f2001000000 | xxd -r -p | sha256sum | awk '{print $1}' | xxd -r -p | sha256sum | awk '{print $1}' | sed 's/\(..\)/\1\n/g' | tac | tr -d '\n'
```
