### ISSUE TITLE
Connecting to electrs server from other machine

### ISSUE THREAD

**Issue by annaparker** [romanz/electrs#71]
Hello,

I have successfully installed and run electrs server on my OVH server. Now I want to connect it from my home by command:
`electrum-3.2.3.exe --oneserver --server=X.X.X.X:50001:t`

Unfortunately it won't connect. Seems it's because netstat says:
`tcp        0      0 127.0.0.1:50001         0.0.0.0:*               LISTEN      0          4362703    5391/target/release`

The question is: how to add option to listen on 0.0.0.0 to be able to connect from other than localhost?
BTW: Is it possible to run public electrs server? I would love to.

**Comment by annaparker** [comment]
Yes, of course, thank you. Just for testing I have tried firstly without TLS. The problem is electrs is listening on localhost only, can you implement an option in the future to listening on specified IP? Thanks.

**Comment by romanz** [comment]
You can change the IP address using the `--electrum-rpc-addr` flag:
https://github.com/romanz/electrs/blob/fce7bd15b0d6203c96f6da28b165b52b15b568af/src/config.rs#L137

**Comment by annaparker** [comment]
```
root@ubuntu:~/electrs# cargo run --release -- -vvv --timestamp --db-dir ./db --cookie="USER:PW" --index-batch-size=10 --electrum-rpc-addr=X.X.X.X
    Finished release [optimized] target(s) in 5.34s
     Running `target/release/electrs -vvv --timestamp --db-dir ./db '--cookie=USER:PW' --index-batch-size=10 --electrum-rpc-addr=X.X.X.X`
thread 'main' panicked at 'invalid Electrum RPC address: AddrParseError(())', libcore/result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by romanz** [comment]
Not sure what may cause this issue...
Could you please re-run it with higher verbosity (`-vvvv`)?

**Comment by romanz** [comment]
Could you please run the electrum client also with higher verbosity?

**Comment by romanz** [comment]
> After restarts, it works.

Great :)
