### ISSUE TITLE
Config: db starts sync and stops

### ISSUE THREAD

**Issue by dimdelizonas** [romanz/electrs#719]
```
./target/release/electrs --conf="config.toml"
Starting electrs 0.9.7 on x86_64 linux with Config { network: Bitcoin, db_path: "/home/dimitris/electrs/db/bitcoin", daemon_dir: "/home/dimitris/.bitcoin", daemon_auth: CookieFile("/home/dimitris/electrs/cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: None, reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.7 (Electrum Rust Server)!", args: [] }
[2022-05-22T19:33:32.702Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2022-05-22T19:33:32.702Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:50001
[2022-05-22T19:33:32.789Z INFO  electrs::db] "/home/dimitris/electrs/db/bitcoin": 7 SST files, 0.000005635 GB, 0.000000007 Grows
[2022-05-22T19:34:03.472Z INFO  electrs::db] closing DB at /home/dimitris/electrs/db/bitcoin
Error: electrs failed

Caused by:
    0: bitcoind RPC polling failed
    1: daemon not available
    2: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
```
I can't find anything regarding a solution to this.

**Comment by tadeubas** [comment]
Is Electrs running on docker, Ubuntu for Windows (with WSL2), or a virtual machine different than the one running Bitcoin Core ? If so the ip will not be `127.0.0.1`.

Also check the Bitcoin Core `bitcoin.conf` file has:
```
# [rpc]
# Accept command line and JSON-RPC commands.
server=1
```

You can also config this at the GUI:
![image](https://user-images.githubusercontent.com/5518496/175922170-ad84d043-54d1-435f-b43a-294132d98434.png)

Windows firewall will ask for the first time if you allow the application to access the network, if you clicked no, then the firewall will block electrs.
![image](https://user-images.githubusercontent.com/5518496/175924383-fe86a8f2-fdcf-445e-b814-f3f3ebdc210b.png)

 To check for that type at Windows start menu `Windows Defender Firewall`, click on the link `Allow an app or feature through Windows Defender Firewall`, then check if `electrs` is allowed.
![image](https://user-images.githubusercontent.com/5518496/175924459-bab83d58-690f-4f44-ad29-3d02cf34d219.png)

**Comment by romanz** [comment]
@dimdelizonas Any updates?
