### ISSUE TITLE
Bug: Prometheus metrics should be prefixed with electrs_

### ISSUE THREAD

**Issue by cornfeedhobo** [romanz/electrs#722]
**Describe the bug**
Prometheus metrics aren't prefixed

**Electrs version**
`0.9.4`

**To Reproduce**
1. Configure and start electrs
2. Query the metrics port
3. See no prefix

**Expected behavior**

Changelog says this is prefixed as of 2019?

**System running electrs**
 - Deployment method: cri
 - OS name and version k3os

**Comment by romanz** [comment]
Good catch, thanks!
