### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by MintsandShovels** [romanz/electrs#729]
**Describe the bug**
I am following the raspibolt.org instructions to set up a bitcoin node + all the other utilities.  I am currently trying to connect to my server using an Electrum wallet.  

The Electrs logfile gives me the following error (with sequential timestamps):

Jun XX XX:XX:XX raspibolt electrs[1569]: [2022-06-13T23:16:43.169Z WARN  electrs::electrum] RPC blockchain.estimatefee failed: failed to estimate fee: JSON-RPC error: RPC error response: RpcError { code: -32603, message: "Fee estimation disabled", data: None }

on the Electrum Wallet I get a complementary message:

W/i | interface.[**raspibolt.local OR onion address.onion**:50002] | disconnecting due to RPCError(2, 'Fee estimation disabled')

This also is a repeating message when the Electrum wallet is trying to connect to the server.

The GUI on the electrum wallet shows it trying to connect from a red status to a circular status but never goes through, and the aforementioned CLI logs continue to repeat.

**Electrs version**
0.9.8 (newest) 

**To Reproduce**
1. Configure and start electrs (raspibolt.org instructions)
2. Connect with electrum client using raspibolt local or onion address
4. Wait
5. See error
And I did install and configure the tor background service on the OS running my electrum wallet.

**Expected behavior**
I expected the Electrum wallet to connect and render a green light (for raspibolt.local) or a blue light (for proxy tor connection). 

**Configuration**
Electrs configured exactly as instructed here: https://raspibolt.org/guide/bitcoin/electrum-server.html

<details>
<summary>electrs.toml</summary>

Electrs log:
```
Jun XX XX:XX:XX raspibolt electrs[1569]: [2022-06-13T23:16:43.169Z WARN  electrs::electrum] RPC blockchain.estimatefee failed: failed to estimate fee: JSON-RPC error: RPC error response: RpcError { code: -32603, message: "Fee estimation disabled", data: None }
```
or Electrum Wallet log:

```
W/i | interface.[**raspibolt.local OR onion address.onion**:50002] | disconnecting due to RPCError(2, 'Fee estimation disabled')
```
</details>

Environment variables: `ELECTRS_X=Y;...`
Arguments: `--foo`

**System running electrs**
 Raspberry Pi OS Lite (64-bit)

**Electrum client**
Client name (if not upstream desktop Electrum) and version:
Electrum-4.2.2

**Additional context**

First time submitting an issue, please let me know what else I need to add.

**Comment by bmml1** [comment]
Hello,

I think you forgot to disable the initial sync optimization. This is not a problem with electrs.

Try:
`sudo nano /home/bitcoin/.bitcoin/bitcoin.conf`

`#dbcache=2000`
`#blocksonly=1`

`sudo systemctl restart bitcoind`

**Comment by MintsandShovels** [comment]
Thanks I redid the whole process and made sure to annotate that.  And now it works!  Huzzaaahhh!!!
