### ISSUE TITLE
After installed Electrum wallet code=exited, status=1/FAILURE

### ISSUE THREAD

**Issue by Pitorru** [romanz/electrs#732]
Well after I installed electrum wallet and restart my computer happened this.

electrs.service - Electrs
     Loaded: loaded (/etc/systemd/system/electrs.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2022-06-18 22:19:11 CEST; 18s ago
    Process: 9792 ExecStart=/home/climbingbitcoin/electrs/target/release/electrs --log-filters INFO --conf=/home/climbingbitcoin/electrs/electrs.conf (code=exited, status=1/FAILURE)
   Main PID: 9792 (code=exited, status=1/FAILURE)
        CPU: 4ms

Electrs is not starting anymore and bitcoind.service is active IDK what happened it was working well before I restarted my computer.

**Comment by Pitorru** [comment]
Now is tellling me this:

● electrs.service - Electrs
     Loaded: loaded (/etc/systemd/system/electrs.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2022-06-18 22:46:25 CEST; 22s ago
    Process: 7376 ExecStart=/home/bitcoin/electrs/target/release/electrs --log-filters INFO --conf=/home/climbingbitcoin/electrs/electrs.conf (code=exited, status=203/EXEC)
   Main PID: 7376 (code=exited, status=203/EXEC)
        CPU: 2ms

**Comment by romanz** [comment]
Sorry for the (very) delayed response...
Does the issue still happen?

**Comment by romanz** [comment]
Please re-open if the issue persists.
