### ISSUE TITLE
Is there a list of all possible run flags anywhere?

### ISSUE THREAD

**Issue by duckartes** [romanz/electrs#74]
Such as --db-dir etc.

**Comment by romanz** [comment]
It is defined at https://github.com/romanz/electrs/blob/master/src/config.rs.
It can be also generated by running `electrs --help`.

**Comment by duckartes** [comment]
Coolio. 

Is there a way we can go about documenting optimal configurations depending on the system it is being run on? And perhaps even move towards an auto-optimal-choosing values depending on specs of system?
