### ISSUE TITLE
Bug: LOG file huge.

### ISSUE THREAD

**Issue by fwittingham** [romanz/electrs#763]
**Describe the bug**
The LOG file grows every day 1GB and never rotate or deleted himself. 

Here my electrs.conf file:

```
# RaspiBolt: electrs configuration
# /data/electrs/electrs.conf

# Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/home/bitcoin/.bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"

# Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/data/electrs/db"
index_lookup_limit = 1000

# Logging
log_filters = "INFO"
timestamp = true
```

**Electrs version**
Last build. 

<details>
File location: /electrs/db/bitcoin

sudo journalctl -f -u electrs"
-- Journal begins at Sat 2022-08-13 16:49:39 -05. --
Aug 16 13:04:23 RaspiBolt electrs[2759989]: [2022-08-16T18:04:23.878Z INFO  electrs::electrum] your wallet uses less efficient method of querying electrs, consider contacting the developer of your wallet. Reason: blockchain.scripthash.get_history called for unsubscribed scripthash

</details>

**System running electrs**
Raspibolt V3.0 
Raspberry Pi 4 4GB

**Comment by romanz** [comment]
Is it the RocksDB log file (under `/data/electrs/db/bitcoin/`)?
If so, it should be rotated automatically (https://github.com/romanz/electrs/blob/dd021952ba7e268ff939fb4e87f1e5d7cfac5140/src/db.rs#L100).

**Comment by fwittingham** [comment]
Yes the "LOG" is under default path. But the problem persist.

**Comment by romanz** [comment]
@fwittingham could you please check if the issue also reproduces on the #773 branch (`bump-msrv`)?
