### ISSUE TITLE
Run Electrs in docker container

### ISSUE THREAD

**Issue by pratapc65** [romanz/electrs#811]
Hello Team, 
I have the bitcoin core running a docker and want to run electrs in a docker. Please can you provide a sample electrs dockerfile.
Regards,
Pratap.

**Comment by Kixunil** [comment]
It's literally there.

**Comment by Kixunil** [comment]
No clue, I'm not familiar with docker.

**Comment by romanz** [comment]
Maybe it's better to ask @runcitadel (https://github.com/runcitadel/docker-electrs) or @getumbrel (https://github.com/getumbrel/docker-electrs).

CC: @schildbach (following https://github.com/romanz/electrs/issues/323)
