### ISSUE TITLE
Bug: Electrs does not work behind Caddy reverse proxy

### ISSUE THREAD

**Issue by nicheosala** [romanz/electrs#813]
**Describe the bug**
Electrs JSON RPC is not reachable behind a [Caddy](https://caddyserver.com/) reverse proxy.

**Electrs version**
v0.9.10

**To Reproduce**
1. Configure and start electrs
2. Try to estabilish a connection to Electrs, using any client (BitBox App, Bitkipi)
3. The connection fails.
- Electrs' console log does not give any pieces of information
- Caddy's console log only gives TLS realted debug messages
- This, instead, is BitBox App output:
``` 
Failed: invalid character 'H' looking for beginning of value
``` 
- This is Bitkipi output:
``` 
The connection to the specified server failed.
``` 

**Expected behavior**
Clients should be able to communicate with electrs correctly.

**Configuration**

```
# Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/home/bitcoin/.bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"

# Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/data/electrs/db"

# Logging
log_filters = "INFO"
timestamp = true
```

**System running electrs**
 - Deployment method: [Raspibolt guide](https://raspibolt.org/guide/bitcoin/electrum-server.html)
 - OS name and version: Raspberry Pi OS (Linux raspberrypi 5.15.76-v8+) installed on Raspberry Pi 4B
 
**Electrum client**
Client name and version:
- BitBox App 4.35.1
- Bitkipi for Android 1.5.0
- Caddy v2.6.2

**Additional context**
This is the Caddyfile I am using, i.e. the Caddy configuration file:
```
electrs.example.com {
    reverse_proxy 127.0.0.1:50001
}
```

If I try to run Electrs behind a Nginx reverse proxy, everything works fine. This is the working Nginx configuration:

```
upstream electrs {
  server 127.0.0.1:50001;
}

server {
  listen 443 ssl;
  proxy_pass electrs;
}
```

The issue [has already been reported to the Caddy community](https://caddy.community/t/jsonrpc-reverse-proxy-to-electrum-server-not-working/17746/7), but they kindly asked to rreach Electrs for clarifications.

**Comment by Kixunil** [comment]
> Caddy 2 is a powerful, enterprise-ready, open source **web** server with

Electrs doesn't use web protocol, so you can't use a web server to do the proxying.

**Comment by nicheosala** [comment]
Oh, thank you. But: why does Electrs work behind Nginx reverse proxy instead?

**Comment by Kixunil** [comment]
Because the suggested nginx configuration doesn't use HTTP but a raw stream. Perhaps we should clarify that one.

**Comment by nicheosala** [comment]
Thanks!
