### ISSUE TITLE
Add documentation for at least main structs

### ISSUE THREAD

**Issue by dpc** [romanz/electrs#83]
Hi, I'm just investigating the implementation, and one thing that would really help is adding comments for each of the main structs. It shouldn't take too much time for someone that already knows what is what, and greatly speeds up navigating around.

Thanks!

**Comment by romanz** [comment]
Thanks for reporting this issue!
I'll try to add more documentation during the next week :)

**Comment by dpc** [comment]
@romanz Sure it can!

**Comment by xanoni** [comment]
Really old, guess it can be closed, given I see some basic docs now.
