### ISSUE TITLE
Bug: Prometheus monitoring steps are wrong

### ISSUE THREAD

**Issue by smartm0use** [romanz/electrs#830]
Monitoring steps described [here](https://github.com/romanz/electrs/blob/master/doc/monitoring.md) could not work because of "field scrape_configs already set in type config.plain".
Default config file located in "/etc/prometheus/prometheus.yml" already has that line.

**Comment by romanz** [comment]
Thanks for reporting this issue!

I've updated the steps in #832 - please take a look.
