### ISSUE TITLE
Feature: Implement `blockchain.transaction.id_from_pos` method

### ISSUE THREAD

**Issue by EshaanAgg** [romanz/electrs#834]
Implement `blockchain.transaction.id_from_pos` protocol method as described in the [specs here](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-transaction-id-from-pos).

I would like to work on this issue @romanz

**Comment by romanz** [comment]
Please do

**Comment by EshaanAgg** [comment]
I was trying to implement the same as follows:
![image](https://user-images.githubusercontent.com/96648934/216323228-87f98ad8-3880-4f3b-9835-8c0fac597ab3.png)
I am facing a problem in line `411`, where I am unable to figure out how to get the `tx_pos`th transaction from the `txids`. Any pointers for this?

**Comment by EshaanAgg** [comment]
Sure :)

**Comment by romanz** [comment]
Use `txids[*tx_pos]` (since `tx_pos` is `&usize`):
```
error[E0277]: the type `[bitcoin::Txid]` cannot be indexed by `&usize`
   --> src/electrum.rs:420:18
    |
420 |         let tx = txids[tx_pos];
    |                  ^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
    |
    = help: the trait `SliceIndex<[bitcoin::Txid]>` is not implemented for `&usize`
    = note: required because of the requirements on the impl of `std::ops::Index<&usize>` for `Vec<bitcoin::Txid>`
```
https://github.com/romanz/electrs/actions/runs/4074792155/jobs/7020360062

**Comment by EshaanAgg** [comment]
Thanks a lot @romanz! Rust type errors still get the better of me sometimes :)
Updated the PR.
