### ISSUE TITLE
Feature: Implement `blockchain.scripthash.get_mempool` method for RPC

### ISSUE THREAD

**Issue by EshaanAgg** [romanz/electrs#839]
Implement `blockchain.scripthash.get_mempool` as described in the documentation [here](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#blockchain-scripthash-get-mempool), so that we provide support for all methods

**Comment by EshaanAgg** [comment]
I would like to work on this issue.

**Comment by romanz** [comment]
Sounds good, please do :)
