### ISSUE TITLE
Feature: Implement `server.add_peer` method for RPC

### ISSUE THREAD

**Issue by EshaanAgg** [romanz/electrs#840]
Implement `server.add_peer` as described in the documentation [here](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#server-add-peer), so that we provide support for all methods

**Comment by romanz** [comment]
Not sure - what is the benefit of supporting this RPC?
https://electrumx-spesmilo.readthedocs.io/en/latest/peer_discovery.html

**Comment by EshaanAgg** [comment]
My bad. This method was itself dropped in `ElectrumX 1.2.1` so supporting it wouldn't be of much use.
