### ISSUE TITLE
rust-bitcoincore-rpc instead of electrs-bitcoincore-rpc

### ISSUE THREAD

**Issue by losh11** [romanz/electrs#857]
From what I'm able to tell both libraries are identical, except from changes to the library name, and `electrs-bitcoincore-rpc` is missing a few commits. Is there any reason why electrs uses a fork?

**Comment by Kixunil** [comment]
That one is actually [unmaintained](https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/253). I plan to properly fork it (and add async while I'm at it.) But I will not have time for it until April.

**Comment by romanz** [comment]
I have created https://crates.io/crates/electrs-bitcoincore-rpc only to allow releasing and using https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/253 (to fix https://github.com/romanz/electrs/issues/792).

**Comment by romanz** [comment]
Will be happy to switch back to https://crates.io/crates/bitcoincore-rpc when 0.17.0 is released :)
