### ISSUE TITLE
Build: cargo build on OSX Monterey linking errors

### ISSUE THREAD

**Issue by hodlbear** [romanz/electrs#858]
**Which command failed?**
`cargo build --locked --release`

**What was the error message?**

<summary>Various linking errors due to rust-toolchain pinning to 1.48.0</summary>

You will see various linking errors containing something like
```
... is not mach-o or llvm bitcode ...
```

**System**
OS name and version: OSX 12.6.3 (Monterey)
rustc version: 1.48.0
cargo version: 1.48.0

**Compilation**
Linking: static
Cross compilation: no
Target architecture: x86_64

**Additional context**
From what I understand building a Universal MacOS binary isn't supported on OSX versions >= 12.0 (so Monterey and up) using older versions of rustc / cargo.
It will result in linking errors similar to above.
This "problem" then is due to the rust-toolchain file in the repo pinning to specific rust toolchain version (1.48.0).
Not sure if pinning is necessary, but I suspect more people will run into this when building on OSX Monterey.
I updated to rust 1.68.0 and updated rust-toolchain file accordingly and was able to build succesfully.

This could perhaps be added to the build instructions for OSX.

**Comment by Kixunil** [comment]
I think `cargo +1.48.0 build --release` should work. Anyway, agree with documenting.

**Comment by hodlbear** [comment]
> cargo +stable build --release

that works

**Comment by romanz** [comment]
https://github.com/romanz/electrs/pull/773 will bump MSRV to 1.63 - it will be released when Debian Bookworm will become stable.

**Comment by Kixunil** [comment]
Hey @hodlbear does the error message looks similar to this one? https://github.com/Kixunil/bip21/actions/runs/4425685474/jobs/7762823597

**Comment by hodlbear** [comment]
Yes, the message is similar but for for serde instead of secp256k1, message below:

Compiling serde v1.0.142
<...>
note: ld: in /Users/hodlbear/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-38540dcacc9fd218.rlib(lib.rmeta), archive member 'lib.rmeta' with length 209784 is not mach-o or llvm bitcode file '/Users/hodlbear/.rustup/toolchains/1.48.0-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-38540dcacc9fd218.rlib'
<...>
error: could not compile `serde`

**Comment by Kixunil** [comment]
Ah, OK, thanks! That's very helpful.

**Comment by romanz** [comment]
@hodlbear Could you please try latest `master` (since #773 is merged)?

**Comment by hodlbear** [comment]
> @hodlbear Could you please try latest `master` (since #773 is merged)?

Nice, I tried v0.10.0-rc.1 with  a  ``cargo build --locked --release`` and had no problems.
