### ISSUE TITLE
Config:

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [romanz/electrs#874]
**Have you read the documentation?**
Yes. (Please, read usage.md first if you did not.)

**How did you configure electrs?**

Installed electrs with this manual: https://raspibolt.org/guide/bitcoin/electrum-server.html

<details>
<summary>Since few days electrs won’t start and connecting with sparrow and/or electrum-wallet anymore</summary>

```
Since few days I got some issue with the electrum server, because it didn’t connect with my sparrow and/or bitBox-wallet. and electrum wallet also not connecting.

It worked till two or three weeks ago, but now electrs didn’t start anymore.

What can I do in this case, should i remove the whole electrs on my node and reinstall? if yes, can somebody put me in here the related commands for doing that?

netdiver, [11 Apr 2023 at 11:16:02]:
seems there is a «corruption: block checksum mismatch» no matter why. is there a chance to repair this, with resyncing or reindexing something? and if yes, which commands should I use for that?


```

</details>

Environment variables: `ELECTRS_X=Y;...`
Arguments: `--foo`

**Debug output of configuration**
```
[2023-04-11T09:17:05.350Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
[2023-04-11T09:17:05.351Z INFO  electrs::server] serving Electrum RPC on 127.0.0.1:50001
Error: electrs failed

Caused by:
    0: failed to open DB: /data/electrs/db/bitcoin
    1: IO error: while open a file for lock: /data/electrs/db/bitcoin/LOCK: Permission denied
```

**Expected behavior**
It worked till few days ago as expected. The server was running and there wasn’t any problems with connecting my wallets with my own node.

**Actual behavior**
Electrs didn’t start up anymore. because of this error:

```
electrs::db] "/data/electrs/db/bitcoin": 222 SST files, 39.053241353 GB, 4.894821533 Grows
thread 'main' panicked at 'DB::put failed: Error { message: "Corruption: block checksum mismatch: expected 3421043951, got 725249767  in /data/electrs/db/bitcoin/388074.sst offset 114425579 size 2556" }', src/db.rs:338:14
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```

**Comment by romanz** [comment]
Unfortunately, it seems that there is a corruption in your index DB... 
Could you please check your disk for errors?

**Comment by n-e-t-d-i-v-e-r** [comment]
thx for your response:

sudo systemctl stop electrs
sudo systemctl disable electrs
sudo su - electrs
rm /data/electrs/db/bitcoin/388074.sst
rm -r /data/electrs/db
exit
sudo systemctl enable electrs
sudo systemctl start electrs
sudo systemctl status electrs

meanwhile i deleted the whole electrs db and reindexing it again. not sure why I’ll get this during the reindexing:

ERROR electrs::server] 131: disconnecting due to failed to send response: "{\"error\":{\"code\":-32603,\"message\":\"unavailable index\"},\"id\":2,\"jsonrpc\":\"2.0\"}\n"

WARN  electrs::server] 131: failed to shutdown TCP connection Transport endpoint is not connected (os error 107)

but the syncing is still running.

BTW: I have no idea how to check disk errors on my external SSD drive. are there any terminal-commands to do that?

**Comment by romanz** [comment]
It's OK to get `"unavailable index"` errors during initial indexing - please wait until it's over.

> BTW: I have no idea how to check disk errors on my external SSD drive. are there any terminal-commands to do that?

I can suggest using https://linux.die.net/man/8/fsck

**Comment by n-e-t-d-i-v-e-r** [comment]
i have no idea how this "block checksum mismatch" error could occur on my external SSD. the fact was that i deleted the entire electrum-db and did a complete db-sync. now everything is running smoothly again and the electrum-server restarts. also the wallets can be connected to their own node again. 

if someone should encounter a similar problem, you can see above the necessary terminal commands with which you can solve this.

i therefore close this case.
