### ISSUE TITLE
Add protections to example systemd file

### ISSUE THREAD

**Issue by Kixunil** [romanz/electrs#876]
Electrs runs just fine with things like `NoNewPrivileges`, we should document this. (would've opened a PR but have to run).

**Comment by romanz** [comment]
[contrib/electrs.service](https://github.com/romanz/electrs/blob/86d074204ca4a9fae14c3eefaaf5a0011fff9a33/contrib/electrs.service) seems to contain the relevant settings... did you mean to update [doc/config.md](https://github.com/romanz/electrs/blob/master/doc/config.md#sample-systemd-unit-file)?

**Comment by Kixunil** [comment]
Oh, yeah. We should sync those files or maybe just refer to the example from the doc to avoid de-sync in the future.
