### ISSUE TITLE
bitcoind RPC polling failed

### ISSUE THREAD

**Issue by random9brat** [romanz/electrs#878]
**How did you configure electrs?**

I used docker stack of 5 conteiners, use some volumes and created networking... bitcoind conteiner is reachable, telneting from electrs container to bitcoind container is working on port 8332...but Im getting this error:

Error: electrs failed

Caused by:
    0: bitcoind RPC polling failed
    1: daemon not available
    2: JSON-RPC error: transport error: Didn't receive response data in time, timed out.
    
Credentials are fine, port is reachable, daemon_dir is reachable via docker volume sharing...

I cant use cookie because other services are using RPC bitcoin auth...

If anyone helps me I can send 20.000 sats <3

P.S. didnt want to tag it as a bug but question, sry.

**Comment by antonilol** [comment]
> I cant use cookie because other services are using RPC bitcoin auth...

use bitcoind [rpcauth](https://github.com/bitcoin/bitcoin/blob/master/share/rpcauth/rpcauth.py) instead of user/pass in the bitcoin.conf, this way you can use cookie and user/pass
the linked script generates the password hash to put in bitcoin.conf

**Comment by random9brat** [comment]
im trying to understand how this rpcauth works: 

# The config option `rpcauth` can be added to server startup argument. It is set at initialization time
# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to bitcoin.conf:
# rpcauth=ishwar:ishwardev***
# Your password:ishwardev***
#
# On client-side, you add the normal user/password pair to send commands:
#rpcuser=ishwar
#rpcpassword=ishwardev***

🤔

**Comment by random9brat** [comment]
im trying to understand how this rpcauth works: 

# The config option `rpcauth` can be added to server startup argument. It is set at initialization time
# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to bitcoin.conf:
# rpcauth=ishwar:ishwardev
# Your password:ishwardev
#
# On client-side, you add the normal user/password pair to send commands:
#rpcuser=ishwar
#rpcpassword=ishwardev

🤔

**Comment by romanz** [comment]
Thanks for reporting this issue!

Could you please attach the electrs logs?
(if possible, use `DEBUG` or even `TRACE` verbosity)

**Comment by random9brat** [comment]
where could I search for logs for electrs?

**Comment by romanz** [comment]
> where could I search for logs for electrs?

They are usually are printed to stderr.

**Comment by romanz** [comment]
@random9brat Any updates?

**Comment by random9brat** [comment]
I kinda switched to bitcoin core and electrum on the same container. Couldnt make it work so had to switch to this way...

But I cant connect from electrum wallet to electrum server since I only get 50001 port exposed and from what I can see here he is searching for 50002, how can I open that?

**Comment by romanz** [comment]
> But I cant connect from electrum wallet to electrum server since I only get 50001 port exposed and from what I can see here he is searching for 50002, how can I open that?

You can use `address:50001:t` notation (https://github.com/romanz/electrs/blob/master/doc/usage.md#electrum-client) to see if it's possible to connect to the server via TCP (without SSL).

> EDIT: and even tho my electrs::index indexing 2000 blocks is working I still cant access from telnet 192.168.4.9 50001, he is saying there is no connection listening...

Is it still indexing? Could you please share the recent log output?

> EDIT 2: also didnt know what "They are usually are printed to stderr." , stiderr means

stderr is the [standard error stream](https://en.wikipedia.org/wiki/Standard_streams), usually directed to the console when running a process - but it also can be redirected into a log file. How are you running electrs?

**Comment by random9brat** [comment]
Ok so I did run it, it was working (connected to it via electrum wallet) and then when I rerun it with screen command (so it can work in the background) it kinda crashed with this error:

2023-05-21T21:24:56.324Z ERROR electrs::server] 0: disconnecting due to failed to send response: "{\"id\":2,\"jsonrpc\":\"2.0\",\"result\":0.00023152}\n"

And I cant connect to it anymore from the same LAN with C:\Program Files (x86)\Electrum>electrum-4.2.1.exe --oneserver --server ipadress:50002:s

Electrum wallet cant see it anymore within connected nodes...

**Comment by romanz** [comment]
Ping :)

**Comment by random9brat** [comment]
Nah i coudltn do it... I tried everything... Installed it on the same docker container where btc node is and it worked... I couldnt have them separate...

**Comment by alevchuk** [comment]
fwiw, i was getting the same timeout. i realized by bitcoin node was not caught up. Once sync finished, electrs stopped timing out.

So maybe you just need to wait until bitcoin logs start saying "progress=1.000000"
