### ISSUE TITLE
Config:   Electrs failed: Address already in use

### ISSUE THREAD

**Issue by g0vann** [romanz/electrs#879]
** Intro**
Last week I hade some problems with my node on a Raspberry pi 4, so i already had a working setup based on raspibolt . I decided to format the ssd and reinstall the full node, always following the steps in the raspibolt guide.

**Have you read the documentation?**
Yes. Current version "0.9.13"

**How did you configure electrs?**
First of all, raspibolt let ge you an SSL certfificate for 10 years and it sets you up with an nginx reverse proxy. I allowed ufw incoming rule for Electrs on 50002:

_sudo ufw status_ 

```
`> Status: active
>
> To                         Action      From
> --                         ------      ----
> 22/tcp                   ALLOW       Anywhere
> 50002/tcp                   ALLOW       Anywhere       # allow Elcetrum SSL
> 22/tcp  (v6)                 ALLOW       Anywhere (v6)
> 50002/tcp  (v6)                  ALLOW       Anywhere (v6)       # allow Elcetrum SSL
```

And the Electrs conf:

_/data/electrs/electrs.conf_

```
`# RaspiBolt: electrs configuration
# /data/electrs/electrs.conf

# Bitcoin Core settings
network = "bitcoin"
daemon_dir= "/home/bitcoin/.bitcoin"
daemon_rpc_addr = "127.0.0.1:8332"
daemon_p2p_addr = "127.0.0.1:8333"

# Electrs settings
electrum_rpc_addr = "127.0.0.1:50001"
db_dir = "/data/electrs/db"

# Logging
log_filters = "INFO"
timestamp = true`
```

Electrs synched the whole blockchain as I can see trough the journal but I can't  connect to my electrs server form the outside, both in the local network and trough the Tor address:

_electrs --conf /data/electrs/electrs.conf_

```
`Starting electrs 0.9.13 on aarch64 linux with Config { network: Bitcoin, db_path: "/data/electrs/db/bitcoin", daemon_dir: "/home/bitcoin/.bitcoin", daemon_auth: CookieFile("/home/bitcoin/.bitcoin/.cookie"), daemon_rpc_addr: 127.0.0.1:8332, daemon_p2p_addr: 127.0.0.1:8333, electrum_rpc_addr: 127.0.0.1:50001, monitoring_addr: 127.0.0.1:4224, wait_duration: 10s, jsonrpc_timeout: 15s, index_batch_size: 10, index_lookup_limit: Some(1000), reindex_last_blocks: 0, auto_reindex: true, ignore_mempool: false, sync_once: false, disable_electrum_rpc: false, server_banner: "Welcome to electrs 0.9.13 (Electrum Rust Server)!", args: [] }
[2023-05-19T07:09:42.744Z INFO  electrs::metrics::metrics_impl] serving Prometheus metrics on 127.0.0.1:4224
Error: electrs failed

Caused by:
    Address already in use (os error 98)
thread 'metrics'panicked at 'called' 'Resault::unwrap()' on an 'Err' value: 0s {code:98, kind: AddrInUse, message: 'Address already in use'}', src/metrics.rs
```
`

If i try:

_lsof -i :5001_

it only shows up this line

`electrs 6302 electrs    3u   IPv4   19066   0t0    localhost:50001   (LISTEN)`

Of course if i try to connect sparrow through my local address and port 50002 i get the following error message:

```
Could not connect:

PKIX path validation failed: java.security.cert.CertPathValidatorException:
Path does not chain with any of the trust anchros

PKIX path validation failed: java.security.cert.CertPathValidatorException:
Path does not chain with any of the trust anchros
```

I honestly can't figure out what kind of problem it is, I created the rule and port for Elcetrs, set the NGINX proxy and diligently follow all the steps of the Raspibolt. Maybe there is some problem with the SSL certificate I created while? maybe having created one with the same command months ago, now it conflicts me? What tests can I do?

**Comment by romanz** [comment]
Many thanks for reporting this issue!
```
Caused by:
    Address already in use (os error 98)
thread 'metrics'panicked at 'called' 'Resault::unwrap()' on an 'Err' value: 0s {code:98, kind: AddrInUse, message: 'Address already in use'}', src/metrics.rs
```
Seems that there is another process bound on the Prometheus metrics exporter's port (4224 by default)
https://github.com/romanz/electrs/blob/f3dd8041823b1d3974240c4901fbc3dd370a0513/src/metrics.rs#L30

**Comment by romanz** [comment]
Could you try to connect Sparrow to you RPi over port 50001 (i.e. without SSL)?

**Comment by romanz** [comment]
No problem :)
