### ISSUE TITLE
Bug: server.version implementation is incorrect

### ISSUE THREAD

**Issue by giahuy98** [romanz/electrs#886]
**Describe the bug**

The `server.version` method should accept a version within the range `[protocol_min, protocol_max]`, currently if a client calls `server.version` with parameters `["1.3", "1.4.2"]`, will be rejected.

Look like the issue is at this code: https://github.com/romanz/electrs/blob/master/src/electrum.rs#L442

Reference: https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#server.version

**Electrs version**
latest

**To Reproduce**
1. Configure and start electrs
2. Connect with electrum with jsonrpc request `{"jsonrpc": "2.0", "method": "server.version", "params": ["client_name",  ["1.3", "1.4.2"]], "id": 0}`
3. Wait

**Expected behavior**
Allow client to connect

**Electrum client**
Nunchuk

**Comment by romanz** [comment]
Thanks for reporting this issue!

**Comment by romanz** [comment]
@giahuy98 Could you please try the #887?

**Comment by giahuy98** [comment]
@romanz It still doesn't work.

```
echo '{"jsonrpc": "2.0", "method": "server.version", "params": ["1.3",  "1.4.2"], "id": 0}' | netcat 127.0.0.1 60401
{"error":{"code":1,"message":"unsupported request Single(\"1.4.2\") by 1.3"},"id":0,"jsonrpc":"2.0"}
```

```
echo '{"jsonrpc": "2.0", "method": "server.version", "params": ["1.4"], "id": 0}' | netcat 127.0.0.1 60401
{"error":{"code":-32602,"message":"invalid params"},"id":0,"jsonrpc":"2.0"}
```

```
echo '{"jsonrpc": "2.0", "method": "server.version", "params": ["1.4",  "1.4"], "id": 0}' | netcat 127.0.0.1 60401
{"id":0,"jsonrpc":"2.0","result":["electrs/0.9.13","1.4"]}
```

**Comment by romanz** [comment]
Please try testing with the following JSON (note the [`client_name` part](https://electrumx-spesmilo.readthedocs.io/en/latest/protocol-methods.html#server.version)):
```
$ echo '{"jsonrpc": "2.0", "method": "server.version", "params": ["client_name",  ["1.3", "1.5"]], "id": 0}' | nc localhost 50001
```

**Comment by giahuy98** [comment]
My mistake, it works! Thank you.
