### ISSUE TITLE
Build: warning: the following packages contain code that will be rejected by a future version of Rust: bindgen v0.55.1, nom v5.1.2

### ISSUE THREAD

**Issue by ElectrumBSV** [romanz/electrs#895]
**Have you read the documentation?**
Yes. (Please, read usage.md first if you did not.)

**Did you double-check that you installed all dependencies?**
Yes. (Please, double check the dependencies if you didn't.)

**Which command failed?**
`cargo build`
commands work fine but got the error message below
**What was the error message?**

<details>
warning: the following packages contain code that will be rejected by a future version of Rust: bindgen v0.55.1, nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`

<summary>Error message</summary>

```
type error message here
```

warning: the following packages contain code that will be rejected by a future version of Rust: bindgen v0.55.1, nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`

**System**
OS name and version: (If Linux, the distribution name and version)
Pop OS
rustc version: (run `rustc --version`)
rustc 1.70.0 (90c541806 2023-05-31)

cargo version: (run `cargo --version`; not guaranteed to be same as rustc version!)
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

**Compilation**
Linking: static/dynamic
Cross compilation: yes/no
unsure
Target architecture: (uname -m on Linux if not cross-compiling)

**Additional context**
Any additional information that seems to be relevant.

**Comment by romanz** [comment]
Which system/machine are you using?
How did you install Rust?

**Comment by ElectrumBSV** [comment]
> Which system/machine are you using? How did you install Rust?

System 76 Bonobo-Pop OS (derivative of linux)
can't remember how i installed Rust...

**Comment by ElectrumBSV** [comment]
> Could you please attach the full log of the following command (from your electrs repository):
> 
> ```
> $ git log -1
> $ cargo build --all --features metrics_process --release
> ```

user@pop-os:~/electrs$ git log -1
commit 46881ed884843f73d74dba2f12d85d5d35b38467 (HEAD, tag: v0.9.14)
Author: Roman Zeyde <me@romanzey.de>
Date:   Fri Jun 9 20:15:39 2023 +0300

    Bump version

user@pop-os:~/electrs$ cargo build --all --features metrics_process --release

  Downloaded miniz_oxide v0.4.4
  Downloaded hex v0.4.3
  Downloaded crc32fast v1.2.1
  Downloaded procfs v0.10.1
  Downloaded adler v1.0.2
  Downloaded byteorder v1.4.3
  Downloaded flate2 v1.0.22
  Downloaded 7 crates (312.0 KB) in 0.66s
   Compiling miniz_oxide v0.4.4
   Compiling crc32fast v1.2.1
   Compiling adler v1.0.2
   Compiling bitflags v1.2.1
   Compiling byteorder v1.4.3
   Compiling hex v0.4.3
   Compiling prometheus v0.13.0
   Compiling electrs v0.9.14 (/home/hodl/electrs)
   Compiling flate2 v1.0.22
   Compiling procfs v0.10.1
    Finished release [optimized] target(s) in 12.33s
warning: the following packages contain code that will be rejected by a future version of Rust: bindgen v0.55.1, nom v5.1.2
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`

**Comment by romanz** [comment]
See https://github.com/rust-bakery/nom/issues/1659.
