### ISSUE TITLE
Bug: Running electrs on AWS instance, even when disowning process, causes the process to die when terminal is closed.

### ISSUE THREAD

**Issue by 21FingerSukuna** [romanz/electrs#898]
I have successfully installed the Eletrcs server on an AWS instance. When I run it locally and send curl requests it works perfectly. When I run it on our public IP address as long as I'm SSH'ed into the AWS instance the server works fine, however once I exit the terminal window it kills the process and the server.

I've tried disowning the process to no avail.

**Comment by romanz** [comment]
Consider using systemd for running electrs:
https://github.com/romanz/electrs/blob/master/doc/config.md#sample-systemd-unit-file

**Comment by 21FingerSukuna** [comment]
Exactly what I needed. Thanks! Works perfectly now!

**Comment by 21FingerSukuna** [comment]
Exactly what I needed! Works perfectly now.
