### ISSUE TITLE
failed to read cookie from "/home/bitcoin/.bitcoin/.cookie"

### ISSUE THREAD

**Issue by gabridome** [romanz/electrs#9]
I suppose the file is not present because I have the rpcuser and
rpcpassword variables set.

Is it possible to set them in alternative to the cookie file?

**Comment by romanz** [comment]
Thanks for reporting this issue!
Great suggestion, will add this feature soon :)

**Comment by romanz** [comment]
It seems that in case your username and password are set to `USER` and `PASSWORD` respectively at `bitcoin.conf`, you can create your own `~/.bitcoin/.cookie` file containing the following line:
```
USER:PASSWORD
```
And the latest version of the code should use it for correct authentication.

Please let me know if this works for you.

**Comment by gabridome** [comment]
It does work but if you create the file BEFORE restarting bitcoind, the daemon will delete the file (.cookie).

I had no chance to see what happens if I restart AFTER the creation. I just created it while bitcoind was running (right now it is indexing). 

For now it works. I'll tell you eventually if restarting the bitcoind daemon the .cookie file is deleted.

**Comment by romanz** [comment]
Oops... you're right - `bitcoind` deletes the `.cookie` file even if it didn't create it:
https://github.com/bitcoin/bitcoin/blob/79e677950b32f31f06f4a72aeb59997bbeae152c/src/rpc/server.cpp#L323

**Comment by gabridome** [comment]
Well I'd say it now works, even if it is not possible to connect and I receive a:

```
thread 'reader' panicked at 'failed to read a request: Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }', libcore/result.rs:945:5
```
in the middle of a big number of:
````
WARN - no mempool entry 9dfb275aa98f916d0ff4a2fb970af2c69340b87691afd3de77fb4023f0a0086f: missing fees section"
````

**Comment by romanz** [comment]
This is indeed wierd...
BTW, which `bitcoind` version are you using?
```
$ bitcoind --version
```

**Comment by gabridome** [comment]
Bitcoin Core Daemon version v0.16.99.0-4781813
C

**Comment by romanz** [comment]
The panic above seems to happen probably due to Electrum client sending non-UTF8 values.
I'll open a separate issue for debugging this.
