### ISSUE TITLE
Requests fail if params member omitted

### ISSUE THREAD

**Issue by sangaman** [romanz/electrs#90]
In testing/playing with electrs, I noticed that if I send a request such as `{"method":"server.banner","id":1,"jsonrpc":"2.0"}` I get this error:

```
ERROR - [192.168.1.170:39576] connection handling failed: Error: invalid command: {"id":1,"jsonrpc":"2.0","method":"server.banner"}
```

If I include `params` in the request, like `{"method":"server.banner","id":123,"jsonrpc":"2.0","params":[""]}
`, it works.

However, according to the [JSON-RPC 2.0 spec](https://www.jsonrpc.org/specification), the params member MAY be omitted. I figure it would make sense to relax this requirement, it could conflict with certain clients.

**Comment by romanz** [comment]
Should be fixed in `master` now.

**Comment by sangaman** [comment]
Thanks! I'll test it out soon.

**Comment by sangaman** [comment]
Confirmed working for me, thanks!
