### ISSUE TITLE
"waiting for RPC warmup" too verbose

### ISSUE THREAD

**Issue by tjaderxyz** [romanz/electrs#907]
If you start electrs before bitcoind is ready it keeps printing "waiting for RPC warmup:" messages on INFO level every second. 

https://github.com/romanz/electrs/blob/c91dc5488fcdaf21dd4cdc33122c5fdd11b04e1c/src/daemon.rs#L48-L56

I think that is too excessive for INFO, as it is the default log level. bitcoind could take several minutes to finish warming up.

I suggest this message be lowered to DEBUG or some rate limiting be implemented for it.

**Comment by romanz** [comment]
Thanks for reporting this issue - will be fixed in #908.
