### ISSUE TITLE
server.ping method unimplemented

### ISSUE THREAD

**Issue by sangaman** [romanz/electrs#91]
[server.ping](https://electrumx.readthedocs.io/en/latest/protocol-methods.html#server-ping) is listed as part of the electrum protocol, however it is not implemented in electrs. I can see it's missing from `handle_command` in rpc.rs and making the request results in this error:

```
ERROR - [192.168.1.170:40226] connection handling failed: Error: unknown method server.ping []
```

This causes a bunch of failed requests when electrs is used with [btc-rpc-explorer](https://github.com/janoside/btc-rpc-explorer/).

**Comment by romanz** [comment]
Thanks for reporting this issue!
Should be fixed in `master` now.

**Comment by sangaman** [comment]
Thank you! I'll test this as well.

**Comment by sangaman** [comment]
Working for me with the changes from the PR, thanks!
