### ISSUE TITLE
Improve configuration documentation

### ISSUE THREAD

**Issue by newearthmartin** [romanz/electrs#930]
The configuration page in the docs skips basic usage examples and jumps into more specific topics directly.

IMO the configuration page should explain how to run a basic instance, explain what the different ports mean, how to get it to connect to an electrum client. Then it can go into improving it by adding SSL, tor, etc.

In my case, I have tried to set it up but I'm guessing many things and electrum does not connect. For example, some questions that arose:

- Should I use `0.0.0.0:50001` to tell it to allow connections from other machines in my LAN?
- Why is it that the electrum client uses all ports 50002 and electrs uses 50001?
- Will the electrum client connect even though I'm not using HTTPS?

It could also explain the meaning of `:t` for plain HTTP connections.

**Comment by SpinningMyWheels** [comment]
There's also some confusion between which is the Start9 host and which is the machine hosting the control software when setting things up.

**Comment by newearthmartin** [comment]
I'd be happy to write this if you think my observations are correct
