### ISSUE TITLE
Bug: Doesn't work since update to Bitcoin 0.25

### ISSUE THREAD

**Issue by 21FingerSukuna** [romanz/electrs#932]
As of today our electrs server just stopped working... Everytime we try to re-run it we get the same error...

"Config { log: StdErrLog { verbosity: Trace, quiet: false, show_level: true, timestamp: Off, modules: [], writer: "stderr", color_choice: Auto, show_module_names: false }, network_type: Testnet, db_path: "./db/testnet", daemon_dir: "/home/ubuntu/.bitcoin/testnet3", blocks_dir: "/home/ubuntu/.bitcoin/testnet3/blocks", daemon_rpc_addr: 127.0.0.1:18332, cookie: None, electrum_rpc_addr: 127.0.0.1:60001, http_addr: 127.0.0.1:3001, http_socket_file: None, monitoring_addr: 127.0.0.1:14224, jsonrpc_import: false, light_mode: false, address_search: false, index_unspendables: false, cors: None, precache_scripts: None, utxos_limit: 500, electrum_txs_limit: 500, electrum_banner: "Welcome to electrs-esplora 0.4.1" }
thread 'main' panicked at 'failed to start monitoring HTTP server at 127.0.0.1:14224', src/metrics.rs:71:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

**Comment by dandoii** [comment]
I'm having the same issue as well

**Comment by antonilol** [comment]
> electrum_banner: "Welcome to electrs-esplora 0.4.1"

are you using the blockstream fork?

i have no issues with bitcoin core 25 with (this) electrs

**Comment by 21FingerSukuna** [comment]
@antonilol Yes it was an issue with the blockstream fork. Has been resolved!
