### ISSUE TITLE
Config: Point to a specific configuration file

### ISSUE THREAD

**Issue by JWBurgers** [romanz/electrs#962]
Is there any way to stop the service from wanting a configuration file at "/home/electrs/.electrs/config.toml."?

I am unable to point at a specific directory for reading the configuration file in my service file. Below is a copy of my service file.

`[Service]`
`ExecStart=/btc-server/electrs/bin/electrs --conf /etc/electrs/electrs.toml --log-filters INFO`
`Type=simple`

The service continuously fails to start because it wants to read a configuration file at /home/electrs/.electrs/config.toml. But there is no such file, it should just look at "/etc/electrs/electrs.toml".

**Comment by JWBurgers** [comment]
I spent some more time on this issue yesterday and realized it was the "ProtectHome=True" setting that affected the start of the service. Even though I had given a specific location for the configuration file, in order to start up Electrs still requires the possibility of access to the home directory, in case I suppose that someone provides that location for the configuration file. 

The "ProtectHome=True" setting is fairly standard. It would be good if it had no impact as long as a configuration file location is specified upon execution.

**Comment by romanz** [comment]
Thanks!
https://github.com/romanz/electrs/pull/686 should help with this issue.

**Comment by Kixunil** [comment]
That's definitely the right solution, I forgot to document it so I did in #963
