### ISSUE TITLE
A question about electrs' forks

### ISSUE THREAD

**Issue by angusscott** [romanz/electrs#967]
This is in part a feature request, and part trying to trace down some versions from the repo history, so apologies up front for the type of request this is, as I've recently inherited this codebase/workflow, so don't have all the historical context

We are aiming to upgrade to the latest version of electrs, we've been building from a branch named origin/perf, with the latest commit being https://github.com/romanz/electrs/commit/c51aac74f77fe6a62033cb2b9d47492483ed2fb2

We are leveraging these HTTP endpoints:

GET /address/<address>
GET /address/<address>/txs/chain

I recently built electrs from the latest main, and appears to be that these endpoints don't work, neither with main or from the current perf branch. 

Ideally I would like to upgrade, and this is the limiting factor currently

**Comment by romanz** [comment]
Good question!

The [`perf` branch](https://github.com/romanz/electrs/commits/perf) eventually was forked into https://github.com/Blockstream/electrs which supports the mentioned [HTTP endpoints](https://github.com/blockstream/esplora/blob/master/API.md) via the https://github.com/Blockstream/esplora backend.

There is also the https://github.com/mempool/electrs fork, exposing a bit [different endpoints](https://mempool.space/docs/api/rest). 

Hope this helps :)

**Comment by angusscott** [comment]
Perfect, couldn't have asked for a better reply. Thanks @romanz
