### ISSUE TITLE
Feature: Support donation address configuration

### ISSUE THREAD

**Issue by monkey-jsun** [romanz/electrs#992]
**Is your feature request related to a problem? Please describe.**

ElectrumX has a feature that allows one to configure a BTC address to receive donation.  I actually have received some in the past.

Can electrs do the same?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kixunil** [comment]
No and I would advise against doing so. ElectrumX is designed for publicly-facing servers, electrs is not. Unless you got donation from someone trusted this suggests you're trying to make public electrs instance. There's no DoS protection so it's best to use other software for it. And even if you've set up an authenticated tunnel with people you trust not to DoS your server it'd be better to use xpub or a LNURL. We could probably support xpub, the dependency is already there but still, the previous warning applies.

**Comment by monkey-jsun** [comment]
sounds good for its purpose.  close now.
