### ISSUE TITLE
DB seems to be corrupted after running out of disk space

### ISSUE THREAD

**Issue by sha-265** [romanz/electrs#996]
**Describe the bug**
Unable to start Electrs, after I ran out of disk space, Electrs stop working.

The log shows:

> Error: electrs failed
>
>Caused by:
>    0: failed to open DB: /data/electrs-db/bitcoin
>    1: IO error: No such file or directoryWhile open a file for random read: /data/electrs-db/bitcoin/233685.ldb: No such file or directory

Any suggestions?

**Electrs version**
0.9.13

**Comment by Kixunil** [comment]
I'm afraid you'll have to delete the database and resync. :( But it's weird that rocksdb doesn't handle out of space errors more reasonably.

**Comment by romanz** [comment]
@sha-265 Did the resync succeed?

**Comment by romanz** [comment]
@sha-265 Ping :)

**Comment by romanz** [comment]
Sounds good, thanks!
